# Generated by Django 5.1.3 on 2025-11-23 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import partos.models


class Migration(migrations.Migration):
    dependencies = [
        ("partos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="parto",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partos_creados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="parto",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partos_modificados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modificado por",
            ),
        ),
        migrations.AlterField(
            model_name="parto",
            name="edad_gestacional_parto",
            field=models.CharField(
                help_text="Ej: 39+2",
                max_length=10,
                validators=[partos.models.validar_edad_gestacional],
                verbose_name="Edad Gestacional al Parto",
            ),
        ),
    ]
