# Generated by Django 5.1.3 on 2025-11-23 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("embarazos", "0001_initial"),
        ("pacientes", "0001_initial"),
        ("partos", "0002_parto_created_by_parto_modified_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="parto",
            name="partos_pacient_9e7fcb_idx",
        ),
        migrations.RemoveField(
            model_name="parto",
            name="embarazo_id",
        ),
        migrations.RemoveField(
            model_name="parto",
            name="medico_responsable_id",
        ),
        migrations.RemoveField(
            model_name="parto",
            name="paciente_id",
        ),
        migrations.AddField(
            model_name="parto",
            name="embarazo",
            field=models.ForeignKey(
                blank=True,
                db_column="embarazo_id",
                help_text="Embarazo asociado al parto",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="partos",
                to="embarazos.embarazo",
                verbose_name="Embarazo",
            ),
        ),
        migrations.AddField(
            model_name="parto",
            name="medico_responsable",
            field=models.ForeignKey(
                blank=True,
                db_column="medico_responsable_id",
                help_text="Médico que atiende el parto",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partos_atendidos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Médico Responsable",
            ),
        ),
        migrations.AddField(
            model_name="parto",
            name="paciente",
            field=models.ForeignKey(
                blank=True,
                db_column="paciente_id",
                help_text="Paciente del parto",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="partos",
                to="pacientes.paciente",
                verbose_name="Paciente",
            ),
        ),
        migrations.AddIndex(
            model_name="parto",
            index=models.Index(
                fields=["paciente", "-fecha_parto"], name="partos_pacient_9e7fcb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="parto",
            index=models.Index(fields=["embarazo"], name="partos_embaraz_d2bca6_idx"),
        ),
    ]
