# Generated by Django 5.1.3 on 2025-11-24 16:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partos", "0003_remove_parto_partos_pacient_9e7fcb_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApgarScoreDetallado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "minuto_evaluacion",
                    models.IntegerField(
                        help_text="1, 5, 10, 15, 20 minutos...",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ],
                        verbose_name="Minuto de Evaluación",
                    ),
                ),
                (
                    "frecuencia_cardiaca",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (2, "2")],
                        help_text="0=Ausente, 1=<100, 2=>100",
                        verbose_name="Frecuencia Cardíaca",
                    ),
                ),
                (
                    "esfuerzo_respiratorio",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (2, "2")],
                        help_text="0=Ausente, 1=Débil/irregular, 2=Fuerte/llanto",
                        verbose_name="Esfuerzo Respiratorio",
                    ),
                ),
                (
                    "tono_muscular",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (2, "2")],
                        help_text="0=Flácido, 1=Flexión leve, 2=Movimiento activo",
                        verbose_name="Tono Muscular",
                    ),
                ),
                (
                    "irritabilidad_refleja",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (2, "2")],
                        help_text="0=Sin respuesta, 1=Mueca, 2=Llanto vigoroso",
                        verbose_name="Irritabilidad Refleja",
                    ),
                ),
                (
                    "coloracion",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (2, "2")],
                        help_text="0=Azul/pálido, 1=Cuerpo rosado/extremidades azules, 2=Completamente rosado",
                        verbose_name="Coloración",
                    ),
                ),
                (
                    "observaciones_evaluador",
                    models.TextField(
                        blank=True,
                        help_text="Detalles relevantes durante la evaluación",
                        verbose_name="Observaciones del Evaluador",
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="apgar_evaluados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Evaluador",
                    ),
                ),
                (
                    "recien_nacido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apgar_scores_detallados",
                        to="partos.reciennacido",
                        verbose_name="Recién Nacido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apgar Score Detallado",
                "verbose_name_plural": "Apgar Scores Detallados",
                "db_table": "apgar_scores_detallados",
                "ordering": ["recien_nacido", "minuto_evaluacion"],
                "indexes": [
                    models.Index(
                        fields=["recien_nacido", "minuto_evaluacion"],
                        name="apgar_score_recien__0a3ce6_idx",
                    ),
                    models.Index(
                        fields=["fecha_registro"], name="apgar_score_fecha_r_3ed60c_idx",
                    ),
                ],
                "unique_together": {("recien_nacido", "minuto_evaluacion")},
            },
        ),
        migrations.CreateModel(
            name="ComplicacionParto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_complicacion",
                    models.CharField(
                        choices=[
                            ("hemorragia", "Hemorragia"),
                            ("distocia", "Distocia"),
                            ("sufrimiento_fetal", "Sufrimiento Fetal"),
                            ("desgarro_severo", "Desgarro Severo"),
                            ("rotura_uterina", "Rotura Uterina"),
                            ("prolapso_cordon", "Prolapso de Cordón"),
                            ("desprendimiento_placenta", "Desprendimiento de Placenta"),
                            ("eclampsia", "Eclampsia"),
                            ("embolia_liquido", "Embolia de Líquido Amniótico"),
                            ("otra", "Otra Complicación"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Complicación",
                    ),
                ),
                (
                    "severidad",
                    models.CharField(
                        choices=[
                            ("leve", "🟢 Leve"),
                            ("moderada", "🟡 Moderada"),
                            ("severa", "🔴 Severa"),
                            ("critica", "🚨 Crítica"),
                        ],
                        default="leve",
                        max_length=20,
                        verbose_name="Severidad",
                    ),
                ),
                (
                    "momento_deteccion",
                    models.DateTimeField(
                        help_text="Cuándo se detectó la complicación",
                        verbose_name="Momento de Detección",
                    ),
                ),
                (
                    "descripcion_detallada",
                    models.TextField(
                        help_text="Descripción completa de la complicación",
                        verbose_name="Descripción Detallada",
                    ),
                ),
                (
                    "tratamiento_realizado",
                    models.TextField(
                        blank=True,
                        help_text="Intervenciones y tratamientos aplicados",
                        verbose_name="Tratamiento Realizado",
                    ),
                ),
                (
                    "medicamentos_utilizados",
                    models.TextField(
                        blank=True,
                        help_text="Lista de medicamentos con dosis",
                        verbose_name="Medicamentos Utilizados",
                    ),
                ),
                (
                    "resolucion_complicacion",
                    models.CharField(
                        choices=[
                            ("resuelto", "Resuelto"),
                            ("en_tratamiento", "En Tratamiento"),
                            ("requiere_seguimiento", "Requiere Seguimiento"),
                        ],
                        default="resuelto",
                        max_length=20,
                        verbose_name="Estado de Resolución",
                    ),
                ),
                (
                    "requirio_cirugia",
                    models.BooleanField(
                        default=False, verbose_name="¿Requirió cirugía?",
                    ),
                ),
                (
                    "tipo_cirugia",
                    models.CharField(
                        blank=True,
                        help_text="Descripción de procedimiento quirúrgico",
                        max_length=200,
                        verbose_name="Tipo de Cirugía",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, verbose_name="Observaciones Adicionales",
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "medico_responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complicaciones_atendidas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Médico que Atendió",
                    ),
                ),
                (
                    "parto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complicaciones",
                        to="partos.parto",
                        verbose_name="Parto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Complicación del Parto",
                "verbose_name_plural": "Complicaciones del Parto",
                "db_table": "complicaciones_parto",
                "ordering": ["-momento_deteccion"],
                "indexes": [
                    models.Index(
                        fields=["parto", "-momento_deteccion"],
                        name="complicacio_parto_i_e0933a_idx",
                    ),
                    models.Index(
                        fields=["tipo_complicacion"],
                        name="complicacio_tipo_co_2aa978_idx",
                    ),
                    models.Index(
                        fields=["severidad"], name="complicacio_severid_074f39_idx",
                    ),
                ],
            },
        ),
    ]
