# Generated by Django 5.1.3 on 2025-11-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partos", "0004_apgarscoredetallado_complicacionparto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parto",
            name="fecha_ingreso",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora en que la paciente ingresa para el parto",
                null=True,
                verbose_name="Fecha y Hora de Ingreso",
            ),
        ),
    ]
