# Generated by Django 5.1.3 on 2025-11-30 06:55

from django.db import migrations


def fix_paciente_from_embarazo(apps, schema_editor):
    """Backfill paciente field for all Parto records where paciente is NULL
    but embarazo and embarazo.paciente are valid.

    This fixes the 'No especificado' display issue in the dashboard.
    """
    Parto = apps.get_model("partos", "Parto")

    partos_sin_paciente = Parto.objects.filter(
        paciente__isnull=True, embarazo__isnull=False,
    ).select_related("embarazo")

    fixed_count = 0
    for parto in partos_sin_paciente:
        if (
            parto.embarazo
            and hasattr(parto.embarazo, "paciente")
            and parto.embarazo.paciente
        ):
            parto.paciente = parto.embarazo.paciente
            parto.save(update_fields=["paciente"])
            fixed_count += 1

    if fixed_count > 0:
        print("[OK] Fixed %d parto(s) - assigned paciente from embarazo" % fixed_count)
    else:
        print("[OK] No partos needed fixing")


def reverse_fix(apps, schema_editor):
    """Reverse is not applicable - we don't want to set paciente back to NULL"""


class Migration(migrations.Migration):
    dependencies = [
        ("partos", "0005_alter_parto_fecha_ingreso"),
    ]

    operations = [
        migrations.RunPython(fix_paciente_from_embarazo, reverse_fix),
    ]
