# Generated by Django 5.1.3 on 2025-12-03 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacientes", "0003_paciente_contacto_emergencia_nombre_and_more"),
        ("partos", "0006_fix_paciente_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parto",
            name="paciente",
            field=models.ForeignKey(
                db_column="paciente_id",
                help_text="Paciente del parto",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="partos",
                to="pacientes.paciente",
                verbose_name="Paciente",
            ),
        ),
    ]
