# Generated by Django 5.1.3 on 2025-12-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partos", "0007_alter_parto_paciente"),
    ]

    operations = [
        migrations.AddField(
            model_name="parto",
            name="apoyo_psicologico_realizado",
            field=models.BooleanField(
                default=False, verbose_name="¿Se proporcionó apoyo psicológico?",
            ),
        ),
        migrations.AddField(
            model_name="parto",
            name="metodo_evacuacion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aspiracion", "Aspiración por Vacío (AMEU)"),
                    ("legrado", "Legrado Uterino"),
                    ("medico", "Método Médico (Misoprostol)"),
                    ("expectante", "Manejo Expectante"),
                ],
                help_text="Método utilizado para evacuación uterina en caso de aborto",
                max_length=50,
                null=True,
                verbose_name="Método de Evacuación",
            ),
        ),
        migrations.AddField(
            model_name="parto",
            name="observaciones_aborto",
            field=models.TextField(
                blank=True,
                help_text="Detalles adicionales del manejo del aborto",
                verbose_name="Observaciones del Aborto",
            ),
        ),
        migrations.AddField(
            model_name="parto",
            name="protocolo_duelo_aplicado",
            field=models.BooleanField(
                default=False, verbose_name="¿Se aplicó protocolo de duelo?",
            ),
        ),
        migrations.AddField(
            model_name="parto",
            name="tipo_aborto",
            field=models.CharField(
                blank=True,
                choices=[
                    ("espontaneo", "Espontáneo"),
                    ("inducido", "Inducido Terapéutico"),
                    ("incompleto", "Incompleto"),
                    ("completo", "Completo"),
                    ("diferido", "Diferido/Retenido"),
                    ("inevitable", "Inevitable"),
                ],
                help_text="Solo completar si edad gestacional < 20 semanas",
                max_length=30,
                null=True,
                verbose_name="Tipo de Aborto",
            ),
        ),
    ]
