# Generated by Django 5.1.3 on 2025-12-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partos", "0008_parto_apoyo_psicologico_realizado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parto",
            name="tipo_parto",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vaginal_espontaneo", "Vaginal Espontáneo"),
                    ("vaginal_instrumentado", "Vaginal Instrumentado"),
                    ("cesarea_electiva", "Cesárea Electiva"),
                    ("cesarea_urgencia", "Cesárea de Urgencia"),
                    ("cesarea_emergencia", "Cesárea de Emergencia"),
                ],
                help_text="Solo requerido para partos (≥ 20 semanas)",
                max_length=30,
                null=True,
                verbose_name="Tipo de Parto",
            ),
        ),
    ]
