# Generated by Django 6.0.5 on 2026-05-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partos", "0009_alter_parto_tipo_parto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complicacionparto",
            name="requirio_cirugia",
            field=models.BooleanField(default=False, verbose_name="¿Requirió cirugía"),
        ),
        migrations.AlterField(
            model_name="complicacionparto",
            name="severidad",
            field=models.CharField(
                choices=[
                    ("leve", " Leve"),
                    ("moderada", " Moderada"),
                    ("severa", " Severa"),
                    ("critica", " Crítica"),
                ],
                default="leve",
                max_length=20,
                verbose_name="Severidad",
            ),
        ),
        migrations.AlterField(
            model_name="parto",
            name="analgesia_utilizada",
            field=models.BooleanField(
                default=False, verbose_name="¿Se utilizó analgesia"
            ),
        ),
        migrations.AlterField(
            model_name="parto",
            name="apoyo_psicologico_realizado",
            field=models.BooleanField(
                default=False, verbose_name="¿Se proporcionó apoyo psicológico"
            ),
        ),
        migrations.AlterField(
            model_name="parto",
            name="desgarros",
            field=models.BooleanField(default=False, verbose_name="¿Hubo desgarros"),
        ),
        migrations.AlterField(
            model_name="parto",
            name="episiotomia",
            field=models.BooleanField(
                default=False, verbose_name="¿Se realizó episiotomía"
            ),
        ),
        migrations.AlterField(
            model_name="parto",
            name="hemorragia_postparto",
            field=models.BooleanField(
                default=False, verbose_name="¿Hemorragia postparto"
            ),
        ),
        migrations.AlterField(
            model_name="parto",
            name="induccion_parto",
            field=models.BooleanField(
                default=False, verbose_name="¿Se indujo el parto"
            ),
        ),
        migrations.AlterField(
            model_name="parto",
            name="monitoreo_fetal_continuo",
            field=models.BooleanField(
                default=False, verbose_name="¿Monitoreo fetal continuo"
            ),
        ),
        migrations.AlterField(
            model_name="parto",
            name="oxitocina_utilizada",
            field=models.BooleanField(
                default=False, verbose_name="¿Se utilizó oxitocina"
            ),
        ),
        migrations.AlterField(
            model_name="parto",
            name="parto_finalizado",
            field=models.BooleanField(default=False, verbose_name="¿Parto finalizado"),
        ),
        migrations.AlterField(
            model_name="parto",
            name="placenta_completa",
            field=models.BooleanField(default=True, verbose_name="¿Placenta completa"),
        ),
        migrations.AlterField(
            model_name="parto",
            name="protocolo_duelo_aplicado",
            field=models.BooleanField(
                default=False, verbose_name="¿Se aplicó protocolo de duelo"
            ),
        ),
        migrations.AlterField(
            model_name="parto",
            name="trabajo_parto_espontaneo",
            field=models.BooleanField(
                default=True, verbose_name="¿Trabajo de parto espontáneo"
            ),
        ),
        migrations.AlterField(
            model_name="reciennacido",
            name="llanto_inmediato",
            field=models.BooleanField(default=True, verbose_name="¿Llanto inmediato"),
        ),
        migrations.AlterField(
            model_name="reciennacido",
            name="malformaciones_congenitas",
            field=models.BooleanField(
                default=False, verbose_name="¿Malformaciones congénitas"
            ),
        ),
        migrations.AlterField(
            model_name="reciennacido",
            name="requirio_reanimacion",
            field=models.BooleanField(
                default=False, verbose_name="¿Requirió reanimación"
            ),
        ),
        migrations.AlterField(
            model_name="reciennacido",
            name="respiracion_espontanea",
            field=models.BooleanField(
                default=True, verbose_name="¿Respiración espontánea"
            ),
        ),
        migrations.AlterField(
            model_name="reciennacido",
            name="tono_muscular_normal",
            field=models.BooleanField(
                default=True, verbose_name="¿Tono muscular normal"
            ),
        ),
    ]
