# Generated by Django 6.0.5 on 2026-06-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partos", "0010_alter_complicacionparto_requirio_cirugia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parto",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="reciennacido",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
