# Generated by Django 5.2.7 on 2025-10-27 19:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('embarazos', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlPrenatal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_control', models.IntegerField(help_text='Número secuencial del control (1, 2, 3...)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Control')),
                ('fecha_control', models.DateField(help_text='Fecha en que se realizó el control prenatal', verbose_name='Fecha del Control')),
                ('semanas_gestacion', models.IntegerField(help_text='Semanas completas de gestación al momento del control', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(42)], verbose_name='Semanas de Gestación')),
                ('dias_gestacion', models.IntegerField(default=0, help_text='Días adicionales a las semanas completas (0-6)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Días adicionales')),
                ('peso_actual', models.DecimalField(decimal_places=2, help_text='Peso actual de la gestante en kilogramos', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('30.0')), django.core.validators.MaxValueValidator(Decimal('200.0'))], verbose_name='Peso Actual (kg)')),
                ('peso_pregestacional', models.DecimalField(blank=True, decimal_places=2, help_text='Peso antes del embarazo en kilogramos', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('30.0')), django.core.validators.MaxValueValidator(Decimal('200.0'))], verbose_name='Peso Pre-gestacional (kg)')),
                ('talla', models.DecimalField(decimal_places=2, help_text='Talla de la gestante en centímetros', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('130.0')), django.core.validators.MaxValueValidator(Decimal('200.0'))], verbose_name='Talla (cm)')),
                ('presion_arterial_sistolica', models.IntegerField(help_text='Presión sistólica en mmHg', validators=[django.core.validators.MinValueValidator(70), django.core.validators.MaxValueValidator(220)], verbose_name='Presión Arterial Sistólica (mmHg)')),
                ('presion_arterial_diastolica', models.IntegerField(help_text='Presión diastólica en mmHg', validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(140)], verbose_name='Presión Arterial Diastólica (mmHg)')),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, help_text='Frecuencia cardíaca materna en latidos por minuto', null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(200)], verbose_name='Frecuencia Cardíaca Materna (lpm)')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, help_text='Temperatura corporal en grados Celsius', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('35.0')), django.core.validators.MaxValueValidator(Decimal('42.0'))], verbose_name='Temperatura (°C)')),
                ('altura_uterina', models.DecimalField(decimal_places=1, help_text='Altura del fondo uterino en centímetros', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('50.0'))], verbose_name='Altura Uterina (cm)')),
                ('frecuencia_cardiaca_fetal', models.IntegerField(help_text='Frecuencia cardíaca fetal en latidos por minuto (normal: 110-160)', validators=[django.core.validators.MinValueValidator(90), django.core.validators.MaxValueValidator(180)], verbose_name='Frecuencia Cardíaca Fetal (lpm)')),
                ('presentacion_fetal', models.CharField(blank=True, choices=[('cefalica', 'Cefálica'), ('podalica', 'Podálica'), ('transversa', 'Transversa'), ('oblicua', 'Oblicua')], help_text='Posición del feto en el útero', max_length=20, null=True, verbose_name='Presentación Fetal')),
                ('movimientos_fetales', models.CharField(blank=True, choices=[('presentes', 'Presentes'), ('ausentes', 'Ausentes'), ('disminuidos', 'Disminuidos'), ('aumentados', 'Aumentados')], default='presentes', help_text='Percepción de movimientos fetales por la madre', max_length=20, null=True, verbose_name='Movimientos Fetales')),
                ('edema', models.CharField(choices=[('no', 'No'), ('leve', 'Leve'), ('moderado', 'Moderado'), ('severo', 'Severo'), ('generalizado', 'Generalizado')], default='no', help_text='Presencia y severidad de edema', max_length=20, verbose_name='Edema')),
                ('proteinuria', models.CharField(choices=[('negativa', 'Negativa'), ('trazas', 'Trazas'), ('positiva_1', '+'), ('positiva_2', '++'), ('positiva_3', '+++'), ('positiva_4', '++++')], default='negativa', help_text='Resultado de proteinuria en orina', max_length=20, verbose_name='Proteinuria')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales del control prenatal', null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró el control en el sistema', verbose_name='Fecha de Registro')),
                ('embarazo_id', models.ForeignKey(db_column='embarazo_id', on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='embarazos.embarazo', verbose_name='Embarazo')),
                ('medico_id', models.ForeignKey(blank=True, db_column='medico_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
                ('paciente', models.ForeignKey(db_column='paciente_id', on_delete=django.db.models.deletion.CASCADE, related_name='controles_prenatales', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Control Prenatal',
                'verbose_name_plural': 'Controles Prenatales',
                'db_table': 'controles_prenatales',
                'ordering': ['-fecha_control', '-numero_control'],
                'indexes': [models.Index(fields=['embarazo_id', '-fecha_control'], name='controles_p_embaraz_cd1232_idx'), models.Index(fields=['paciente', '-fecha_control'], name='controles_p_pacient_272e28_idx'), models.Index(fields=['fecha_control'], name='controles_p_fecha_c_713b92_idx'), models.Index(fields=['-fecha_registro'], name='controles_p_fecha_r_273aa5_idx')],
            },
        ),
    ]
