# Generated by Django 5.1.3 on 2025-11-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consultorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre identificador del consultorio (ej: 'Consultorio 1')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True,
                        help_text="Código interno (ej: 'CONS-01')",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        help_text="Descripción de ubicación general", max_length=100,
                    ),
                ),
                (
                    "piso",
                    models.CharField(
                        blank=True,
                        help_text="Piso o nivel (ej: 'Planta Baja', 'Piso 1')",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "edificio",
                    models.CharField(
                        blank=True,
                        help_text="Edificio (para clínicas con múltiples edificios)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "tipo_consultorio",
                    models.CharField(
                        choices=[
                            ("general", "Consulta General"),
                            ("ginecologia", "Ginecología"),
                            ("ecografia", "Ecografía"),
                            ("laboratorio", "Laboratorio"),
                            ("procedimientos", "Procedimientos"),
                            ("urgencias", "Urgencias"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                (
                    "capacidad_personas",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Capacidad máxima de personas (incluyendo paciente y médico)",
                    ),
                ),
                ("tiene_bano", models.BooleanField(default=False)),
                ("tiene_camilla", models.BooleanField(default=True)),
                ("tiene_ecografo", models.BooleanField(default=False)),
                (
                    "equipamiento",
                    models.TextField(
                        blank=True,
                        help_text="Lista de equipamiento disponible",
                        null=True,
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True, help_text="Consultorio disponible para asignación",
                    ),
                ),
                (
                    "en_mantenimiento",
                    models.BooleanField(
                        default=False,
                        help_text="Consultorio temporalmente fuera de servicio",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, help_text="Observaciones adicionales", null=True,
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Consultorio",
                "verbose_name_plural": "Consultorios",
                "db_table": "consultorios",
                "ordering": ["nombre"],
            },
        ),
    ]
