# Generated by Django 5.2.7 on 2025-10-27 19:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateField(verbose_name='Fecha de la Cita')),
                ('hora_cita', models.TimeField(verbose_name='Hora de la Cita')),
                ('duracion', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(120)], verbose_name='Duración (minutos)')),
                ('tipo_cita', models.CharField(choices=[('primera_vez', 'Primera Vez'), ('control', 'Control'), ('urgencia', 'Urgencia'), ('seguimiento', 'Seguimiento')], default='control', max_length=20, verbose_name='Tipo de Cita')),
                ('estado', models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No Asistió')], default='agendada', max_length=20, verbose_name='Estado')),
                ('motivo', models.TextField(help_text='Motivo por el cual solicita la cita', verbose_name='Motivo de Consulta')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales de la cita', verbose_name='Observaciones')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación')),
                ('recordatorio_enviado', models.BooleanField(default=False, verbose_name='Recordatorio Enviado')),
                ('fecha_recordatorio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recordatorio')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('confirmada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_confirmadas', to=settings.AUTH_USER_MODEL, verbose_name='Confirmada Por')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('medico', models.ForeignKey(limit_choices_to={'rol': 'medico'}, on_delete=django.db.models.deletion.CASCADE, related_name='citas_medico', to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'citas',
                'ordering': ['fecha_cita', 'hora_cita'],
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la Semana')),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio de atención', verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(help_text='Hora de fin de atención', verbose_name='Hora de Fin')),
                ('duracion_cita', models.IntegerField(default=30, help_text='Duración de cada cita en minutos', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(120)], verbose_name='Duración de Cita (minutos)')),
                ('activo', models.BooleanField(default=True, help_text='Si esta disponibilidad está activa', verbose_name='Activo')),
                ('fecha_inicio_vigencia', models.DateField(blank=True, help_text='Fecha desde la cual aplica esta disponibilidad', null=True, verbose_name='Fecha Inicio Vigencia')),
                ('fecha_fin_vigencia', models.DateField(blank=True, help_text='Fecha hasta la cual aplica esta disponibilidad', null=True, verbose_name='Fecha Fin Vigencia')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('medico', models.ForeignKey(limit_choices_to={'rol': 'medico'}, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
            ],
            options={
                'verbose_name': 'Disponibilidad',
                'verbose_name_plural': 'Disponibilidades',
                'db_table': 'disponibilidades',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No Asistió')], max_length=20, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No Asistió')], max_length=20, verbose_name='Estado Nuevo')),
                ('motivo_cambio', models.TextField(blank=True, verbose_name='Motivo del Cambio')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='citas.cita', verbose_name='Cita')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Realizó el Cambio')),
            ],
            options={
                'verbose_name': 'Historial de Cita',
                'verbose_name_plural': 'Historiales de Citas',
                'db_table': 'historial_citas',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['paciente', '-fecha_cita'], name='citas_pacient_382ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['medico', 'fecha_cita'], name='citas_medico__be679f_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['estado'], name='citas_estado_03180e_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha_cita', 'hora_cita'], name='citas_fecha_c_2198af_idx'),
        ),
        migrations.AddIndex(
            model_name='disponibilidad',
            index=models.Index(fields=['medico', 'dia_semana'], name='disponibili_medico__389f2e_idx'),
        ),
        migrations.AddIndex(
            model_name='disponibilidad',
            index=models.Index(fields=['activo'], name='disponibili_activo_f2c05b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidad',
            unique_together={('medico', 'dia_semana', 'hora_inicio', 'hora_fin')},
        ),
    ]
