# Generated by Django 5.2.7 on 2025-10-27 19:25

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Embarazo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("numero_gesta", models.IntegerField()),
                ("fecha_ultima_menstruacion", models.DateField()),
                ("fecha_probable_parto", models.DateField(blank=True, null=True)),
                (
                    "tipo_embarazo",
                    models.CharField(
                        choices=[
                            ("simple", "Simple"),
                            ("gemelar", "Gemelar"),
                            ("multiple", "Múltiple"),
                        ],
                        default="simple",
                        max_length=50,
                    ),
                ),
                (
                    "riesgo_embarazo",
                    models.CharField(
                        choices=[
                            ("bajo", "Bajo"),
                            ("medio", "Medio"),
                            ("alto", "Alto"),
                        ],
                        default="bajo",
                        max_length=50,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("finalizado", "Finalizado"),
                            ("perdida", "Pérdida"),
                        ],
                        default="activo",
                        max_length=50,
                    ),
                ),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "medico_responsable",
                    models.CharField(
                        blank=True,
                        db_column="medico_responsable",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        db_column="paciente_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embarazos",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "db_table": "embarazos",
                "ordering": ["-fecha_registro"],
            },
        ),
    ]
