# Generated by Django 5.1.3 on 2025-11-24 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("embarazos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="embarazo",
            name="medico_responsable",
            field=models.ForeignKey(
                blank=True,
                db_column="medico_responsable_id",
                limit_choices_to={"rol": "medico"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="embarazos_responsable",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
