# Generated by Django 5.1.3 on 2025-11-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("embarazos", "0002_alter_embarazo_medico_responsable"),
    ]

    operations = [
        migrations.AddField(
            model_name="embarazo",
            name="numero_abortos",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="embarazo",
            name="numero_cesareas",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="embarazo",
            name="numero_para",
            field=models.IntegerField(default=0),
        ),
    ]
