# Generated by Django 5.1.3 on 2025-12-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("embarazos", "0003_embarazo_numero_abortos_embarazo_numero_cesareas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="embarazo",
            name="peso_pregestacional",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Peso de la paciente antes del embarazo en kilogramos",
                max_digits=5,
                null=True,
                verbose_name="Peso Pregestacional (kg)",
            ),
        ),
        migrations.AddField(
            model_name="embarazo",
            name="talla_materna",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Altura de la paciente en centímetros",
                max_digits=5,
                null=True,
                verbose_name="Talla Materna (cm)",
            ),
        ),
    ]
