# Generated by Django 5.1.3 on 2026-01-02 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("embarazos", "0005_embarazo_created_by_embarazo_fecha_modificacion_and_more"),
        ("pacientes", "0006_paciente_created_by_paciente_updated_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvolucionEmbarazo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_evento", models.DateField()),
                (
                    "tipo_evento",
                    models.CharField(
                        choices=[
                            ("cita", "Cita"),
                            ("control", "Control Prenatal"),
                            ("ecografia", "Ecografía"),
                            ("laboratorio", "Laboratorio"),
                            ("urgencia", "Urgencia"),
                            ("otro", "Otro"),
                        ],
                        max_length=30,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "embarazo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evoluciones",
                        to="embarazos.embarazo",
                    ),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evoluciones_embarazo",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evolución de Embarazo",
                "verbose_name_plural": "Evoluciones de Embarazo",
                "db_table": "evolucion_embarazo",
                "ordering": ["-fecha_evento"],
            },
        ),
    ]
