# Generated by Django 5.1.3 on 2025-11-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="estado_paciente",
            field=models.CharField(
                choices=[
                    ("activo", "Activo"),
                    ("inactivo", "Inactivo"),
                    ("fallecido", "Fallecido"),
                ],
                default="activo",
                max_length=20,
                verbose_name="Estado del Paciente",
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="fecha_baja",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Baja del Sistema",
            ),
        ),
        migrations.AddIndex(
            model_name="paciente",
            index=models.Index(
                fields=["estado_paciente"], name="pacientes_estado__651ce4_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="paciente",
            constraint=models.UniqueConstraint(
                fields=("ci",), name="unique_paciente_ci",
            ),
        ),
    ]
