# Generated by Django 5.1.3 on 2025-11-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacientes", "0002_paciente_estado_paciente_paciente_fecha_baja_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="contacto_emergencia_nombre",
            field=models.CharField(
                blank=True,
                help_text="Nombre completo de la persona a contactar en caso de emergencia",
                max_length=200,
                null=True,
                verbose_name="Nombre del Contacto de Emergencia",
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="contacto_emergencia_relacion",
            field=models.CharField(
                blank=True,
                help_text="Ej: Esposo, Madre, Hermana, etc.",
                max_length=50,
                null=True,
                verbose_name="Relación con el Paciente",
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="contacto_emergencia_telefono",
            field=models.CharField(
                blank=True,
                help_text="Teléfono del contacto de emergencia",
                max_length=20,
                null=True,
                verbose_name="Teléfono de Emergencia",
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="factor_rh",
            field=models.CharField(
                blank=True,
                choices=[("positivo", "Positivo"), ("negativo", "Negativo")],
                max_length=10,
                null=True,
                verbose_name="Factor RH",
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="numero_seguro_social",
            field=models.CharField(
                blank=True,
                help_text="Número de afiliación al seguro social",
                max_length=50,
                null=True,
                verbose_name="Número de Seguro Social",
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="tipo_sangre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                ],
                max_length=5,
                null=True,
                verbose_name="Tipo de Sangre",
            ),
        ),
    ]
