# Generated by Django 5.1.3 on 2025-12-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacientes", "0003_paciente_contacto_emergencia_nombre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="altura_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Altura del paciente en centímetros",
                max_digits=5,
                null=True,
                verbose_name="Altura (cm)",
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="peso_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Peso del paciente en kilogramos",
                max_digits=5,
                null=True,
                verbose_name="Peso (kg)",
            ),
        ),
    ]
