# Generated by Django 5.1.3 on 2025-12-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacientes", "0004_paciente_altura_cm_paciente_peso_kg"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="estado_civil",
            field=models.CharField(
                blank=True,
                choices=[
                    ("soltero", "Soltero/a"),
                    ("casado", "Casado/a"),
                    ("divorciado", "Divorciado/a"),
                    ("viudo", "Viudo/a"),
                    ("union_libre", "Unión Libre"),
                ],
                max_length=20,
                null=True,
                verbose_name="Estado Civil",
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="ocupacion",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Ocupación",
            ),
        ),
    ]
