# Generated by Django 6.0.4 on 2026-04-24 23:17

from django.db import migrations

import pacientes.fields


class Migration(migrations.Migration):
    dependencies = [
        ("pacientes", "0006_paciente_created_by_paciente_updated_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="apellido_materno",
            field=pacientes.fields.EncryptedCharField(
                blank=True, max_length=255, null=True, verbose_name="Apellido Materno",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="apellido_paterno",
            field=pacientes.fields.EncryptedCharField(
                max_length=255, verbose_name="Apellido Paterno",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="ci",
            field=pacientes.fields.EncryptedCharField(
                max_length=255, unique=True, verbose_name="Cédula de Identidad",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="direccion",
            field=pacientes.fields.EncryptedTextField(
                blank=True, null=True, verbose_name="Dirección",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="email",
            field=pacientes.fields.EncryptedEmailField(
                blank=True, max_length=255, null=True, verbose_name="Correo Electrónico",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="nombre",
            field=pacientes.fields.EncryptedCharField(
                max_length=255, verbose_name="Nombre",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="telefono",
            field=pacientes.fields.EncryptedCharField(
                blank=True, max_length=255, null=True, verbose_name="Teléfono",
            ),
        ),
    ]
