# Generated by Django 6.0.4 on 2026-05-02 22:24

from django.db import migrations, models

import pacientes.fields


class Migration(migrations.Migration):
    dependencies = [
        ("pacientes", "0007_alter_paciente_apellido_materno_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="paciente",
            name="unique_paciente_ci",
        ),
        migrations.AddField(
            model_name="paciente",
            name="ci_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="HMAC-SHA256 del CI en texto plano — usado para constraint de unicidad",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Hash CI (unicidad)",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="ci",
            field=pacientes.fields.EncryptedCharField(
                max_length=255, verbose_name="Cédula de Identidad",
            ),
        ),
    ]
