# Generated by Django 6.0.5 on 2026-06-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pacientes",
            "0008_remove_paciente_unique_paciente_ci_paciente_ci_hash_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
