# Generated by Django 6.0.5 on 2026-06-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0009_alter_paciente_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="consentimiento_datos_aceptado",
            field=models.BooleanField(
                default=False,
                help_text="Ley 164 (Bolivia): consentimiento expreso previo del titular para la recoleccion y tratamiento de sus datos personales.",
                verbose_name="Consentimiento de Tratamiento de Datos Personales",
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="consentimiento_datos_fecha",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Consentimiento"
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="consentimiento_datos_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP al momento del Consentimiento"
            ),
        ),
    ]
