# Generated by Django 6.0.5 on 2026-07-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0010_paciente_consentimiento_datos_aceptado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="genero",
            field=models.CharField(
                choices=[("femenino", "Femenino")],
                default="femenino",
                max_length=20,
                verbose_name="Género",
            ),
        ),
    ]
