# Generated by Django 5.1.3 on 2025-11-24 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("controles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="controlprenatal",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="controles_creados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado Por",
            ),
        ),
        migrations.AddField(
            model_name="controlprenatal",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="controles_modificados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modificado Por",
            ),
        ),
    ]
