# Generated by Django 5.1.3 on 2025-11-24 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("controles", "0002_controlprenatal_created_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="controlprenatal",
            old_name="embarazo_id",
            new_name="embarazo",
        ),
        migrations.RenameField(
            model_name="controlprenatal",
            old_name="medico_id",
            new_name="medico",
        ),
    ]
