# Generated by Django 5.1.3 on 2025-11-27 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("controles", "0003_fix_foreignkey_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controlprenatal",
            name="frecuencia_cardiaca_fetal",
            field=models.IntegerField(
                blank=True,
                help_text="Frecuencia cardíaca fetal en latidos por minuto (normal: 110-160)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(90),
                    django.core.validators.MaxValueValidator(180),
                ],
                verbose_name="Frecuencia Cardíaca Fetal (lpm)",
            ),
        ),
    ]
