# Generated by Django 5.1.3 on 2025-12-12 09:28

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("controles", "0004_alter_controlprenatal_frecuencia_cardiaca_fetal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controlprenatal",
            name="altura_uterina",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Altura del fondo uterino en centímetros. Medible desde ~12 semanas.",
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("50.0")),
                ],
                verbose_name="Altura Uterina (cm)",
            ),
        ),
    ]
