# Generated by Django 5.2.7 on 2025-10-27 19:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('embarazos', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ecografia', models.DateField(verbose_name='Fecha de Ecografía')),
                ('tipo_ecografia', models.CharField(choices=[('primer_trimestre', 'Primer Trimestre (6-14 sem)'), ('segundo_trimestre', 'Segundo Trimestre (14-28 sem)'), ('tercer_trimestre', 'Tercer Trimestre (28-42 sem)'), ('doppler', 'Doppler'), ('4d', 'Ecografía 4D')], max_length=30, verbose_name='Tipo de Ecografía')),
                ('indicacion', models.CharField(choices=[('control_rutina', 'Control de Rutina'), ('sospecha_malformacion', 'Sospecha de Malformación'), ('control_crecimiento', 'Control de Crecimiento'), ('evaluacion_bienestar', 'Evaluación de Bienestar Fetal'), ('sangrado', 'Sangrado'), ('otro', 'Otro')], default='control_rutina', max_length=50)),
                ('edad_gestacional_semanas', models.IntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(42)])),
                ('edad_gestacional_dias', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('numero_fetos', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('vitalidad_fetal', models.BooleanField(default=True, verbose_name='Vitalidad Fetal')),
                ('frecuencia_cardiaca_fetal', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(90), django.core.validators.MaxValueValidator(180)])),
                ('indice_liquido_amniotico', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='ILA (cm)')),
                ('bolsillo_maximo', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Bolsillo Máximo (cm)')),
                ('localizacion_placenta', models.CharField(blank=True, max_length=100, verbose_name='Localización Placenta')),
                ('grado_madurez_placenta', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico Ecográfico')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('embarazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecografias', to='embarazos.embarazo')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecografias_realizadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecografias', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Ecografía',
                'verbose_name_plural': 'Ecografías',
                'db_table': 'ecografias',
                'ordering': ['-fecha_ecografia'],
            },
        ),
        migrations.CreateModel(
            name='BiometriaFetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diametro_biparietal', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='DBP (mm)')),
                ('circunferencia_cefalica', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='CC (mm)')),
                ('circunferencia_abdominal', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='CA (mm)')),
                ('longitud_femur', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='LF (mm)')),
                ('longitud_humero', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='LH (mm)')),
                ('peso_fetal_estimado', models.IntegerField(blank=True, null=True, verbose_name='Peso Fetal Est. (g)')),
                ('percentil_peso', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('ecografia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometria', to='ecografias.ecografia')),
            ],
            options={
                'verbose_name': 'Biometría Fetal',
                'verbose_name_plural': 'Biometrías Fetales',
                'db_table': 'biometria_fetal',
            },
        ),
        migrations.CreateModel(
            name='AnexosFetales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placenta_localizacion', models.CharField(blank=True, max_length=100)),
                ('placenta_grosor', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Grosor (mm)')),
                ('placenta_inserccion_cordon', models.CharField(blank=True, max_length=100)),
                ('numero_vasos_cordon', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('circular_cordon', models.BooleanField(default=False, verbose_name='Circular de Cordón')),
                ('liquido_amniotico_normal', models.BooleanField(default=True)),
                ('polihidramnios', models.BooleanField(default=False)),
                ('oligohidramnios', models.BooleanField(default=False)),
                ('ecografia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='ecografias.ecografia')),
            ],
            options={
                'verbose_name': 'Anexos Fetales',
                'verbose_name_plural': 'Anexos Fetales',
                'db_table': 'anexos_fetales',
            },
        ),
        migrations.CreateModel(
            name='AnatomiaFetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('craneo_normal', models.BooleanField(default=True)),
                ('cerebro_normal', models.BooleanField(default=True)),
                ('cerebelo_normal', models.BooleanField(default=True)),
                ('perfil_facial_normal', models.BooleanField(default=True)),
                ('labios_normales', models.BooleanField(default=True)),
                ('corazon_normal', models.BooleanField(default=True)),
                ('pulmones_normales', models.BooleanField(default=True)),
                ('estomago_normal', models.BooleanField(default=True)),
                ('rinones_normales', models.BooleanField(default=True)),
                ('vejiga_normal', models.BooleanField(default=True)),
                ('columna_normal', models.BooleanField(default=True)),
                ('extremidades_superiores_normales', models.BooleanField(default=True)),
                ('extremidades_inferiores_normales', models.BooleanField(default=True)),
                ('hallazgos_anormales', models.TextField(blank=True, verbose_name='Hallazgos Anormales')),
                ('ecografia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anatomia', to='ecografias.ecografia')),
            ],
            options={
                'verbose_name': 'Anatomía Fetal',
                'verbose_name_plural': 'Anatomías Fetales',
                'db_table': 'anatomia_fetal',
            },
        ),
        migrations.CreateModel(
            name='ImagenEcografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='ecografias/%Y/%m/', verbose_name='Archivo Imagen')),
                ('tipo_imagen', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('ecografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='ecografias.ecografia')),
            ],
            options={
                'verbose_name': 'Imagen de Ecografía',
                'verbose_name_plural': 'Imágenes de Ecografía',
                'db_table': 'imagenes_ecografia',
                'ordering': ['fecha_subida'],
            },
        ),
    ]
