# Generated by Django 5.1.3 on 2025-11-03 20:28

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecografias", "0001_initial"),
        ("embarazos", "0001_initial"),
        ("pacientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagenecografia",
            options={
                "ordering": ["ecografia", "orden"],
                "verbose_name": "Imagen de Ecografía",
                "verbose_name_plural": "Imágenes de Ecografía",
            },
        ),
        migrations.RemoveField(
            model_name="imagenecografia",
            name="archivo",
        ),
        migrations.RemoveField(
            model_name="imagenecografia",
            name="fecha_subida",
        ),
        migrations.AddField(
            model_name="anatomiafetal",
            name="genitales_visibles",
            field=models.BooleanField(default=False, verbose_name="Genitales Visibles"),
        ),
        migrations.AddField(
            model_name="anatomiafetal",
            name="hueso_nasal_presente",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Hueso Nasal Presente"
            ),
        ),
        migrations.AddField(
            model_name="anatomiafetal",
            name="sexo_fetal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("masculino", "Masculino"),
                    ("femenino", "Femenino"),
                    ("indeterminado", "Indeterminado"),
                ],
                max_length=20,
                verbose_name="Sexo Fetal",
            ),
        ),
        migrations.AddField(
            model_name="anatomiafetal",
            name="translucencia_nucal",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                verbose_name="Translucencia Nucal (mm)",
            ),
        ),
        migrations.AddField(
            model_name="anexosfetales",
            name="longitud_cervical",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                verbose_name="Longitud Cervical (mm)",
            ),
        ),
        migrations.AddField(
            model_name="anexosfetales",
            name="placenta_previa",
            field=models.BooleanField(default=False, verbose_name="Placenta Previa"),
        ),
        migrations.AddField(
            model_name="biometriafetal",
            name="cisterna_magna",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                verbose_name="Cisterna Magna (mm)",
            ),
        ),
        migrations.AddField(
            model_name="biometriafetal",
            name="diametro_abdominal_transverso",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name="DAT (mm)",
            ),
        ),
        migrations.AddField(
            model_name="biometriafetal",
            name="diametro_occipito_frontal",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Diámetro Occípito-Frontal",
                max_digits=4,
                null=True,
                verbose_name="DOF (mm)",
            ),
        ),
        migrations.AddField(
            model_name="biometriafetal",
            name="diametro_transverso_cerebelo",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Diámetro Transverso del Cerebelo",
                max_digits=3,
                null=True,
                verbose_name="DTC (mm)",
            ),
        ),
        migrations.AddField(
            model_name="biometriafetal",
            name="longitud_radio",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Longitud del Radio",
                max_digits=4,
                null=True,
                verbose_name="LR (mm)",
            ),
        ),
        migrations.AddField(
            model_name="biometriafetal",
            name="longitud_tibia",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Longitud de la Tibia",
                max_digits=4,
                null=True,
                verbose_name="LT (mm)",
            ),
        ),
        migrations.AddField(
            model_name="biometriafetal",
            name="relacion_cc_ca",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="Relación CC/CA",
            ),
        ),
        migrations.AddField(
            model_name="biometriafetal",
            name="relacion_lf_ca",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="Relación LF/CA",
            ),
        ),
        migrations.AddField(
            model_name="ecografia",
            name="calidad_estudio",
            field=models.CharField(
                choices=[
                    ("excelente", "Excelente"),
                    ("buena", "Buena"),
                    ("regular", "Regular"),
                    ("limitada", "Limitada"),
                ],
                default="buena",
                max_length=20,
                verbose_name="Calidad del Estudio",
            ),
        ),
        migrations.AddField(
            model_name="ecografia",
            name="limitaciones_tecnicas",
            field=models.TextField(
                blank=True,
                help_text="Ej: Posición fetal, obesidad materna, oligohidramnios",
                verbose_name="Limitaciones Técnicas",
            ),
        ),
        migrations.AddField(
            model_name="ecografia",
            name="proxima_ecografia_recomendada",
            field=models.DateField(
                blank=True, null=True, verbose_name="Próxima Ecografía Recomendada"
            ),
        ),
        migrations.AddField(
            model_name="ecografia",
            name="requiere_seguimiento",
            field=models.BooleanField(
                default=False, verbose_name="Requiere Seguimiento"
            ),
        ),
        migrations.AddField(
            model_name="imagenecografia",
            name="analisis_ia",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Resultados del análisis automático de IA",
                verbose_name="Análisis de IA",
            ),
        ),
        migrations.AddField(
            model_name="imagenecografia",
            name="calidad_imagen",
            field=models.CharField(
                choices=[
                    ("excelente", "Excelente"),
                    ("buena", "Buena"),
                    ("regular", "Regular"),
                    ("deficiente", "Deficiente"),
                ],
                default="buena",
                max_length=20,
                verbose_name="Calidad de Imagen",
            ),
        ),
        migrations.AddField(
            model_name="imagenecografia",
            name="es_imagen_principal",
            field=models.BooleanField(
                default=False,
                help_text="Imagen representativa de la ecografía",
                verbose_name="¿Es Imagen Principal?",
            ),
        ),
        migrations.AddField(
            model_name="imagenecografia",
            name="fecha_captura",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 11, 3, 20, 28, 40, 685623, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Fecha de Captura",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="imagenecografia",
            name="imagen",
            field=models.ImageField(
                blank=True,
                help_text="Formatos soportados: JPG, PNG, DICOM",
                null=True,
                upload_to="ecografias/%Y/%m/%d/",
                verbose_name="Imagen",
            ),
        ),
        migrations.AddField(
            model_name="imagenecografia",
            name="mediciones_incluidas",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Datos de mediciones visibles en formato JSON",
                verbose_name="Mediciones en la Imagen",
            ),
        ),
        migrations.AddField(
            model_name="imagenecografia",
            name="orden",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Orden de visualización (1, 2, 3...)",
                verbose_name="Orden",
            ),
        ),
        migrations.AddField(
            model_name="imagenecografia",
            name="titulo",
            field=models.CharField(
                blank=True,
                default="Imagen sin título",
                help_text="Ej: DBP a las 20 semanas, Cara fetal 3D",
                max_length=200,
                null=True,
                verbose_name="Título de la Imagen",
            ),
        ),
        migrations.AlterField(
            model_name="anatomiafetal",
            name="cerebelo_normal",
            field=models.BooleanField(default=True, verbose_name="Cerebelo Normal"),
        ),
        migrations.AlterField(
            model_name="anatomiafetal",
            name="cerebro_normal",
            field=models.BooleanField(default=True, verbose_name="Cerebro Normal"),
        ),
        migrations.AlterField(
            model_name="anatomiafetal",
            name="columna_normal",
            field=models.BooleanField(default=True, verbose_name="Columna Normal"),
        ),
        migrations.AlterField(
            model_name="anatomiafetal",
            name="corazon_normal",
            field=models.BooleanField(default=True, verbose_name="Corazón Normal"),
        ),
        migrations.AlterField(
            model_name="anatomiafetal",
            name="craneo_normal",
            field=models.BooleanField(default=True, verbose_name="Cráneo Normal"),
        ),
        migrations.AlterField(
            model_name="anatomiafetal",
            name="ecografia",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anatomia",
                to="ecografias.ecografia",
                verbose_name="Ecografía",
            ),
        ),
        migrations.AlterField(
            model_name="anatomiafetal",
            name="estomago_normal",
            field=models.BooleanField(default=True, verbose_name="Estómago Normal"),
        ),
        migrations.AlterField(
            model_name="anatomiafetal",
            name="extremidades_inferiores_normales",
            field=models.BooleanField(
                default=True, verbose_name="Extremidades Inferiores Normales"
            ),
        ),
        migrations.AlterField(
            model_name="anatomiafetal",
            name="extremidades_superiores_normales",
            field=models.BooleanField(
                default=True, verbose_name="Extremidades Superiores Normales"
            ),
        ),
        migrations.AlterField(
            model_name="anatomiafetal",
            name="labios_normales",
            field=models.BooleanField(default=True, verbose_name="Labios Normales"),
        ),
        migrations.AlterField(
            model_name="anatomiafetal",
            name="perfil_facial_normal",
            field=models.BooleanField(
                default=True, verbose_name="Perfil Facial Normal"
            ),
        ),
        migrations.AlterField(
            model_name="anatomiafetal",
            name="pulmones_normales",
            field=models.BooleanField(default=True, verbose_name="Pulmones Normales"),
        ),
        migrations.AlterField(
            model_name="anatomiafetal",
            name="rinones_normales",
            field=models.BooleanField(default=True, verbose_name="Riñones Normales"),
        ),
        migrations.AlterField(
            model_name="anatomiafetal",
            name="vejiga_normal",
            field=models.BooleanField(default=True, verbose_name="Vejiga Normal"),
        ),
        migrations.AlterField(
            model_name="anexosfetales",
            name="ecografia",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anexos",
                to="ecografias.ecografia",
                verbose_name="Ecografía",
            ),
        ),
        migrations.AlterField(
            model_name="anexosfetales",
            name="liquido_amniotico_normal",
            field=models.BooleanField(
                default=True, verbose_name="Líquido Amniótico Normal"
            ),
        ),
        migrations.AlterField(
            model_name="anexosfetales",
            name="numero_vasos_cordon",
            field=models.IntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
                verbose_name="Número de Vasos del Cordón",
            ),
        ),
        migrations.AlterField(
            model_name="anexosfetales",
            name="oligohidramnios",
            field=models.BooleanField(default=False, verbose_name="Oligohidramnios"),
        ),
        migrations.AlterField(
            model_name="anexosfetales",
            name="placenta_grosor",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                verbose_name="Grosor Placenta (mm)",
            ),
        ),
        migrations.AlterField(
            model_name="anexosfetales",
            name="placenta_inserccion_cordon",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Inserción del Cordón"
            ),
        ),
        migrations.AlterField(
            model_name="anexosfetales",
            name="placenta_localizacion",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Localización Placenta"
            ),
        ),
        migrations.AlterField(
            model_name="anexosfetales",
            name="polihidramnios",
            field=models.BooleanField(default=False, verbose_name="Polihidramnios"),
        ),
        migrations.AlterField(
            model_name="biometriafetal",
            name="circunferencia_abdominal",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Circunferencia Abdominal",
                max_digits=5,
                null=True,
                verbose_name="CA (mm)",
            ),
        ),
        migrations.AlterField(
            model_name="biometriafetal",
            name="circunferencia_cefalica",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Circunferencia Cefálica",
                max_digits=5,
                null=True,
                verbose_name="CC (mm)",
            ),
        ),
        migrations.AlterField(
            model_name="biometriafetal",
            name="diametro_biparietal",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Diámetro Biparietal",
                max_digits=4,
                null=True,
                verbose_name="DBP (mm)",
            ),
        ),
        migrations.AlterField(
            model_name="biometriafetal",
            name="ecografia",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="biometria",
                to="ecografias.ecografia",
                verbose_name="Ecografía",
            ),
        ),
        migrations.AlterField(
            model_name="biometriafetal",
            name="longitud_femur",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Longitud del Fémur",
                max_digits=4,
                null=True,
                verbose_name="LF (mm)",
            ),
        ),
        migrations.AlterField(
            model_name="biometriafetal",
            name="longitud_humero",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Longitud del Húmero",
                max_digits=4,
                null=True,
                verbose_name="LH (mm)",
            ),
        ),
        migrations.AlterField(
            model_name="biometriafetal",
            name="percentil_peso",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Percentil de Peso",
            ),
        ),
        migrations.AlterField(
            model_name="ecografia",
            name="edad_gestacional_dias",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(6),
                ],
                verbose_name="Días adicionales",
            ),
        ),
        migrations.AlterField(
            model_name="ecografia",
            name="edad_gestacional_semanas",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(4),
                    django.core.validators.MaxValueValidator(42),
                ],
                verbose_name="Edad Gestacional (semanas)",
            ),
        ),
        migrations.AlterField(
            model_name="ecografia",
            name="embarazo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ecografias",
                to="embarazos.embarazo",
                verbose_name="Embarazo",
            ),
        ),
        migrations.AlterField(
            model_name="ecografia",
            name="frecuencia_cardiaca_fetal",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(90),
                    django.core.validators.MaxValueValidator(180),
                ],
                verbose_name="FCF (lpm)",
            ),
        ),
        migrations.AlterField(
            model_name="ecografia",
            name="grado_madurez_placenta",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
                verbose_name="Grado de Madurez Placenta",
            ),
        ),
        migrations.AlterField(
            model_name="ecografia",
            name="indicacion",
            field=models.CharField(
                choices=[
                    ("control_rutina", "Control de Rutina"),
                    ("sospecha_malformacion", "Sospecha de Malformación"),
                    ("control_crecimiento", "Control de Crecimiento"),
                    ("evaluacion_bienestar", "Evaluación de Bienestar Fetal"),
                    ("sangrado", "Sangrado"),
                    ("screening_genetico", "Screening Genético"),
                    ("evaluacion_cervical", "Evaluación Cervical"),
                    ("doppler_materno", "Doppler Materno"),
                    ("doppler_fetal", "Doppler Fetal"),
                    ("otro", "Otro"),
                ],
                default="control_rutina",
                max_length=50,
                verbose_name="Indicación",
            ),
        ),
        migrations.AlterField(
            model_name="ecografia",
            name="medico",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"rol": "medico"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ecografias_realizadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Médico Ecografista",
            ),
        ),
        migrations.AlterField(
            model_name="ecografia",
            name="numero_fetos",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Número de Fetos",
            ),
        ),
        migrations.AlterField(
            model_name="ecografia",
            name="observaciones",
            field=models.TextField(
                blank=True, verbose_name="Observaciones y Recomendaciones"
            ),
        ),
        migrations.AlterField(
            model_name="ecografia",
            name="paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ecografias",
                to="pacientes.paciente",
                verbose_name="Paciente",
            ),
        ),
        migrations.AlterField(
            model_name="ecografia",
            name="tipo_ecografia",
            field=models.CharField(
                choices=[
                    ("primer_trimestre", "Primer Trimestre (6-14 sem)"),
                    ("segundo_trimestre", "Segundo Trimestre (14-28 sem)"),
                    ("tercer_trimestre", "Tercer Trimestre (28-42 sem)"),
                    ("doppler", "Doppler"),
                    ("4d", "Ecografía 4D"),
                    ("genetica", "Ecografía Genética"),
                    ("morfologica", "Ecografía Morfológica"),
                ],
                max_length=30,
                verbose_name="Tipo de Ecografía",
            ),
        ),
        migrations.AlterField(
            model_name="imagenecografia",
            name="descripcion",
            field=models.TextField(
                blank=True,
                help_text="Hallazgos visibles en la imagen",
                verbose_name="Descripción",
            ),
        ),
        migrations.AlterField(
            model_name="imagenecografia",
            name="ecografia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imagenes",
                to="ecografias.ecografia",
                verbose_name="Ecografía",
            ),
        ),
        migrations.AlterField(
            model_name="imagenecografia",
            name="tipo_imagen",
            field=models.CharField(
                blank=True,
                choices=[
                    ("biometria", "Biometría Fetal"),
                    ("anatomia", "Anatomía Fetal"),
                    ("doppler", "Doppler"),
                    ("3d_4d", "3D/4D"),
                    ("placenta", "Placenta"),
                    ("cordon", "Cordón Umbilical"),
                    ("liquido_amniotico", "Líquido Amniótico"),
                    ("cervix", "Cérvix"),
                    ("anexos", "Anexos"),
                    ("general", "Vista General"),
                    ("cara_fetal", "Cara Fetal"),
                    ("corazon", "Corazón Fetal"),
                    ("columna", "Columna Vertebral"),
                    ("extremidades", "Extremidades"),
                    ("genitales", "Genitales"),
                ],
                default="general",
                max_length=50,
                null=True,
                verbose_name="Tipo de Imagen",
            ),
        ),
        migrations.AddIndex(
            model_name="ecografia",
            index=models.Index(
                fields=["paciente", "-fecha_ecografia"],
                name="ecografias_pacient_bc6e87_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ecografia",
            index=models.Index(
                fields=["embarazo", "-fecha_ecografia"],
                name="ecografias_embaraz_e23274_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ecografia",
            index=models.Index(
                fields=["fecha_ecografia"], name="ecografias_fecha_e_4020fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="imagenecografia",
            index=models.Index(
                fields=["ecografia", "tipo_imagen"],
                name="imagenes_ec_ecograf_2b727b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="imagenecografia",
            index=models.Index(
                fields=["fecha_captura"], name="imagenes_ec_fecha_c_8487e2_idx"
            ),
        ),
    ]
