# Generated by Django 5.1.3 on 2025-11-24 00:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pacientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AntecedenteGinecoObstetrico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "menarquia_edad",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Edad de primera menstruación (8-25 años)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(8),
                            django.core.validators.MaxValueValidator(25),
                        ],
                    ),
                ),
                (
                    "ciclos_menstruales",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("regular", "Regular"),
                            ("irregular", "Irregular"),
                            ("amenorrea", "Amenorrea"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "duracion_ciclo_dias",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duración del ciclo en días (21-45)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(21),
                            django.core.validators.MaxValueValidator(45),
                        ],
                    ),
                ),
                (
                    "duracion_menstruacion_dias",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duración del sangrado en días (2-9)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(9),
                        ],
                    ),
                ),
                (
                    "fecha_ultima_menstruacion",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de Última Menstruación (FUM)",
                    ),
                ),
                (
                    "gestas",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Número total de embarazos (incluyendo actual)",
                    ),
                ),
                (
                    "partos",
                    models.PositiveIntegerField(
                        default=0, help_text="Número de partos (> 20 semanas)",
                    ),
                ),
                (
                    "abortos",
                    models.PositiveIntegerField(
                        default=0, help_text="Número de abortos (< 20 semanas)",
                    ),
                ),
                (
                    "cesareas",
                    models.PositiveIntegerField(
                        default=0, help_text="Número de cesáreas",
                    ),
                ),
                (
                    "hijos_vivos",
                    models.PositiveIntegerField(
                        default=0, help_text="Número de hijos vivos actualmente",
                    ),
                ),
                (
                    "metodo_anticonceptivo_actual",
                    models.CharField(
                        blank=True,
                        help_text="Método anticonceptivo en uso (si aplica)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "tiempo_uso_anticonceptivo_meses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Tiempo de uso del método en meses",
                        null=True,
                    ),
                ),
                (
                    "fecha_suspension_anticonceptivo",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de suspensión (si aplica)",
                        null=True,
                    ),
                ),
                (
                    "inicio_vida_sexual_edad",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Edad de inicio de vida sexual",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "numero_parejas_sexuales",
                    models.PositiveIntegerField(
                        blank=True, help_text="Número de parejas sexuales", null=True,
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="antecedentes_gineco_modificados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.OneToOneField(
                        db_column="paciente_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="antecedente_gineco",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Antecedente Gineco-Obstétrico",
                "verbose_name_plural": "Antecedentes Gineco-Obstétricos",
                "db_table": "antecedentes_gineco_obstetricos",
            },
        ),
        migrations.CreateModel(
            name="AntecedentePatologico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("personal", "Personal"),
                            ("heredofamiliar", "Heredofamiliar"),
                        ],
                        help_text="Personal: del paciente | Heredofamiliar: de familiares",
                        max_length=20,
                    ),
                ),
                ("tiene_alergias", models.BooleanField(default=False)),
                (
                    "alergias_medicamentos",
                    models.TextField(
                        blank=True,
                        help_text="Detallar medicamentos y reacciones",
                        null=True,
                    ),
                ),
                (
                    "alergias_alimentos",
                    models.TextField(
                        blank=True,
                        help_text="Detallar alimentos y reacciones",
                        null=True,
                    ),
                ),
                (
                    "alergias_otras",
                    models.TextField(
                        blank=True,
                        help_text="Otras alergias (látex, yodo, etc.)",
                        null=True,
                    ),
                ),
                ("diabetes", models.BooleanField(default=False)),
                (
                    "diabetes_tipo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tipo1", "Tipo 1"),
                            ("tipo2", "Tipo 2"),
                            ("gestacional", "Gestacional"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("hipertension", models.BooleanField(default=False)),
                ("cardiopatias", models.BooleanField(default=False)),
                ("cardiopatia_detalle", models.TextField(blank=True, null=True)),
                ("nefropatias", models.BooleanField(default=False)),
                ("nefropatia_detalle", models.TextField(blank=True, null=True)),
                ("trastornos_coagulacion", models.BooleanField(default=False)),
                ("anemia", models.BooleanField(default=False)),
                ("lupus", models.BooleanField(default=False)),
                ("artritis_reumatoide", models.BooleanField(default=False)),
                ("asma", models.BooleanField(default=False)),
                ("preeclampsia_previa", models.BooleanField(default=False)),
                ("eclampsia_previa", models.BooleanField(default=False)),
                ("diabetes_gestacional_previa", models.BooleanField(default=False)),
                ("hemorragia_postparto_previa", models.BooleanField(default=False)),
                (
                    "otras_enfermedades",
                    models.TextField(
                        blank=True,
                        help_text="Otras enfermedades no listadas",
                        null=True,
                    ),
                ),
                (
                    "cirugiasanteriores",
                    models.TextField(
                        blank=True, help_text="Cirugías previas y fechas", null=True,
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        db_column="paciente_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="antecedentes_patologicos",
                        to="pacientes.paciente",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="antecedentes_patologicos_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Antecedente Patológico",
                "verbose_name_plural": "Antecedentes Patológicos",
                "db_table": "antecedentes_patologicos",
                "ordering": ["-fecha_registro"],
            },
        ),
    ]
