# Generated by Django 5.1.3 on 2025-11-04 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrecimientoFetal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paciente_id", models.IntegerField(verbose_name="ID del Paciente")),
                (
                    "embarazo_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID del Embarazo"
                    ),
                ),
                (
                    "ecografia_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID de Ecografía"
                    ),
                ),
                (
                    "fecha_evaluacion",
                    models.DateTimeField(verbose_name="Fecha de Evaluación"),
                ),
                (
                    "edad_gestacional_semanas",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(16),
                            django.core.validators.MaxValueValidator(42),
                        ],
                        verbose_name="Edad Gestacional (semanas)",
                    ),
                ),
                (
                    "edad_gestacional_dias",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                        verbose_name="Días adicionales",
                    ),
                ),
                (
                    "diametro_biparietal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="DBP (mm)",
                    ),
                ),
                (
                    "circunferencia_cefalica",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="CC (mm)",
                    ),
                ),
                (
                    "circunferencia_abdominal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="CA (mm)",
                    ),
                ),
                (
                    "longitud_femur",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="LF (mm)",
                    ),
                ),
                (
                    "peso_fetal_estimado",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Peso Fetal Estimado (g)"
                    ),
                ),
                (
                    "percentil_dbp",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Percentil DBP"
                    ),
                ),
                (
                    "percentil_cc",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Percentil CC"
                    ),
                ),
                (
                    "percentil_ca",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Percentil CA"
                    ),
                ),
                (
                    "percentil_lf",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Percentil LF"
                    ),
                ),
                (
                    "percentil_peso",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Percentil Peso"
                    ),
                ),
                (
                    "clasificacion_peso",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Clasificación del Peso"
                    ),
                ),
                (
                    "restriccion_crecimiento",
                    models.BooleanField(
                        default=False, verbose_name="¿Restricción de Crecimiento?"
                    ),
                ),
                (
                    "macrosomia",
                    models.BooleanField(default=False, verbose_name="¿Macrosomía?"),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Evaluación de Crecimiento Fetal",
                "verbose_name_plural": "Evaluaciones de Crecimiento Fetal",
                "db_table": "crecimiento_fetal",
                "ordering": ["-fecha_evaluacion"],
            },
        ),
        migrations.CreateModel(
            name="RiesgoPreeclampsia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paciente_id", models.IntegerField(verbose_name="ID del Paciente")),
                (
                    "embarazo_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID del Embarazo"
                    ),
                ),
                (
                    "fecha_evaluacion",
                    models.DateTimeField(verbose_name="Fecha de Evaluación"),
                ),
                (
                    "edad_gestacional_semanas",
                    models.IntegerField(
                        help_text="Evaluación óptima: 11-14 semanas",
                        validators=[
                            django.core.validators.MinValueValidator(11),
                            django.core.validators.MaxValueValidator(14),
                        ],
                        verbose_name="Edad Gestacional (semanas)",
                    ),
                ),
                (
                    "edad_materna",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(15),
                            django.core.validators.MaxValueValidator(50),
                        ],
                        verbose_name="Edad Materna (años)",
                    ),
                ),
                (
                    "peso_materno",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(40),
                            django.core.validators.MaxValueValidator(150),
                        ],
                        verbose_name="Peso Materno (kg)",
                    ),
                ),
                (
                    "talla_materna",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(140),
                            django.core.validators.MaxValueValidator(200),
                        ],
                        verbose_name="Talla Materna (cm)",
                    ),
                ),
                (
                    "raza",
                    models.CharField(
                        choices=[
                            ("caucasica", "Caucásica"),
                            ("afroamericana", "Afroamericana"),
                            ("asiatica", "Asiática"),
                            ("hispana", "Hispana"),
                            ("otra", "Otra"),
                        ],
                        max_length=20,
                        verbose_name="Raza/Etnia",
                    ),
                ),
                (
                    "paridad",
                    models.IntegerField(
                        help_text="Número de partos previos",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Paridad",
                    ),
                ),
                (
                    "hipertension_cronica",
                    models.BooleanField(
                        default=False, verbose_name="Hipertensión Crónica"
                    ),
                ),
                (
                    "diabetes_tipo1",
                    models.BooleanField(default=False, verbose_name="Diabetes Tipo 1"),
                ),
                (
                    "diabetes_tipo2",
                    models.BooleanField(default=False, verbose_name="Diabetes Tipo 2"),
                ),
                (
                    "lupus",
                    models.BooleanField(
                        default=False, verbose_name="Lupus Eritematoso Sistémico"
                    ),
                ),
                (
                    "antecedente_preeclampsia",
                    models.BooleanField(
                        default=False, verbose_name="Antecedente de Preeclampsia"
                    ),
                ),
                (
                    "embarazo_multiple",
                    models.BooleanField(
                        default=False, verbose_name="Embarazo Múltiple"
                    ),
                ),
                (
                    "metodo_concepcion",
                    models.CharField(
                        choices=[
                            ("natural", "Natural"),
                            ("fertilizacion_in_vitro", "FIV"),
                            ("inseminacion", "Inseminación"),
                        ],
                        default="natural",
                        max_length=30,
                        verbose_name="Método de Concepción",
                    ),
                ),
                (
                    "presion_arterial_media",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Presión Arterial Media (mmHg)",
                    ),
                ),
                (
                    "riesgo_calculado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="Riesgo Calculado (1:X)",
                    ),
                ),
                (
                    "riesgo_porcentaje",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Riesgo (%)",
                    ),
                ),
                (
                    "clasificacion_riesgo",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Clasificación de Riesgo",
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Riesgo de Preeclampsia",
                "verbose_name_plural": "Riesgos de Preeclampsia",
                "db_table": "riesgo_preeclampsia",
                "ordering": ["-fecha_evaluacion"],
            },
        ),
        migrations.CreateModel(
            name="ScoreBishop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paciente_id", models.IntegerField(verbose_name="ID del Paciente")),
                (
                    "embarazo_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID del Embarazo"
                    ),
                ),
                (
                    "medico_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID del Médico"
                    ),
                ),
                (
                    "fecha_evaluacion",
                    models.DateTimeField(verbose_name="Fecha de Evaluación"),
                ),
                (
                    "edad_gestacional_semanas",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(42),
                        ],
                        verbose_name="Edad Gestacional (semanas)",
                    ),
                ),
                (
                    "dilatacion_cervical",
                    models.IntegerField(
                        help_text="0-10 cm",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Dilatación Cervical (cm)",
                    ),
                ),
                (
                    "borramiento_cervical",
                    models.IntegerField(
                        help_text="0-100%",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Borramiento Cervical (%)",
                    ),
                ),
                (
                    "consistencia_cervical",
                    models.CharField(
                        choices=[
                            ("dura", "Dura"),
                            ("media", "Media"),
                            ("blanda", "Blanda"),
                        ],
                        max_length=20,
                        verbose_name="Consistencia del Cérvix",
                    ),
                ),
                (
                    "posicion_cervical",
                    models.CharField(
                        choices=[
                            ("posterior", "Posterior"),
                            ("media", "Media"),
                            ("anterior", "Anterior"),
                        ],
                        max_length=20,
                        verbose_name="Posición del Cérvix",
                    ),
                ),
                (
                    "estacion_fetal",
                    models.CharField(
                        choices=[
                            ("-3", "-3"),
                            ("-2", "-2"),
                            ("-1", "-1"),
                            ("0", "0"),
                            ("+1", "+1"),
                            ("+2", "+2"),
                        ],
                        max_length=10,
                        verbose_name="Estación Fetal",
                    ),
                ),
                (
                    "score_total",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Score Total de Bishop"
                    ),
                ),
                (
                    "interpretacion",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Interpretación del Score",
                    ),
                ),
                (
                    "probabilidad_parto_espontaneo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Probabilidad Parto Espontáneo (%)",
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Score de Bishop",
                "verbose_name_plural": "Scores de Bishop",
                "db_table": "score_bishop",
                "ordering": ["-fecha_evaluacion"],
            },
        ),
    ]
