# Generated by Django 5.2.7 on 2025-10-27 19:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("controles", "0001_initial"),
        ("embarazos", "0001_initial"),
        ("pacientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalculoClinico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_calculo",
                    models.CharField(
                        choices=[
                            ("edad_gestacional", "Edad Gestacional y FPP"),
                            ("imc", "Índice de Masa Corporal"),
                            ("ganancia_peso", "Ganancia de Peso Gestacional"),
                            ("bishop", "Puntaje de Bishop"),
                            ("preeclampsia", "Riesgo de Preeclampsia"),
                            ("diabetes_gestacional", "Tamizaje Diabetes Gestacional"),
                            ("ila", "Índice de Líquido Amniótico"),
                            ("peso_fetal", "Estimación de Peso Fetal"),
                            ("apgar", "Puntaje Apgar"),
                            ("percentil_peso", "Percentil de Peso Fetal"),
                            ("rmi_ovario", "Riesgo de Cáncer de Ovario (RMI)"),
                            ("riesgo_endometrio", "Riesgo de Cáncer de Endometrio"),
                            ("pam", "Presión Arterial Media"),
                            ("superficie_corporal", "Superficie Corporal"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Cálculo",
                    ),
                ),
                (
                    "parametros_entrada",
                    models.JSONField(
                        help_text="Datos utilizados para el cálculo",
                        verbose_name="Parámetros de Entrada",
                    ),
                ),
                (
                    "resultados",
                    models.JSONField(
                        help_text="Resultados obtenidos",
                        verbose_name="Resultados del Cálculo",
                    ),
                ),
                (
                    "interpretacion",
                    models.TextField(
                        blank=True,
                        help_text="Interpretación clínica de los resultados",
                        verbose_name="Interpretación",
                    ),
                ),
                (
                    "fecha_calculo",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha del Cálculo",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "control_prenatal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calculos",
                        to="controles.controlprenatal",
                        verbose_name="Control Prenatal Asociado",
                    ),
                ),
                (
                    "embarazo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calculos",
                        to="embarazos.embarazo",
                        verbose_name="Embarazo Asociado",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculos_clinicos",
                        to="pacientes.paciente",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "realizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calculos_realizados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Realizado Por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cálculo Clínico",
                "verbose_name_plural": "Cálculos Clínicos",
                "db_table": "calculos_clinicos",
                "ordering": ["-fecha_calculo"],
            },
        ),
        migrations.CreateModel(
            name="DiabetesGestacional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_test",
                    models.CharField(
                        choices=[
                            ("ogtt_75g", "OGTT 75g (2 horas)"),
                            ("ogtt_100g", "OGTT 100g (3 horas)"),
                            ("glucosa_ayunas", "Glucosa en Ayunas"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Test",
                    ),
                ),
                (
                    "semanas_gestacion",
                    models.IntegerField(verbose_name="Semanas de Gestación"),
                ),
                (
                    "glucosa_ayunas",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Glucosa en Ayunas (mg/dL)",
                    ),
                ),
                (
                    "glucosa_1h",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Glucosa 1 hora (mg/dL)",
                    ),
                ),
                (
                    "glucosa_2h",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Glucosa 2 horas (mg/dL)",
                    ),
                ),
                (
                    "glucosa_3h",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Glucosa 3 horas (mg/dL)",
                    ),
                ),
                (
                    "diagnostico",
                    models.CharField(max_length=100, verbose_name="Diagnóstico"),
                ),
                (
                    "valores_alterados",
                    models.IntegerField(default=0, verbose_name="Valores Alterados"),
                ),
                (
                    "requiere_seguimiento",
                    models.BooleanField(
                        default=False, verbose_name="Requiere Seguimiento",
                    ),
                ),
                (
                    "calculo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diabetes_gestacional",
                        to="calculadoras.calculoclinico",
                        verbose_name="Cálculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diabetes Gestacional",
                "verbose_name_plural": "Diabetes Gestacionales",
                "db_table": "calculos_diabetes_gestacional",
            },
        ),
        migrations.CreateModel(
            name="EdadGestacional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fum", models.DateField(verbose_name="Fecha de Última Menstruación")),
                ("fecha_calculo", models.DateField(verbose_name="Fecha del Cálculo")),
                ("semanas", models.IntegerField(verbose_name="Semanas de Gestación")),
                ("dias", models.IntegerField(verbose_name="Días Adicionales")),
                ("fpp", models.DateField(verbose_name="Fecha Probable de Parto")),
                (
                    "trimestre",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                        verbose_name="Trimestre",
                    ),
                ),
                (
                    "calculo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edad_gestacional",
                        to="calculadoras.calculoclinico",
                        verbose_name="Cálculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Edad Gestacional",
                "verbose_name_plural": "Edades Gestacionales",
                "db_table": "calculos_edad_gestacional",
            },
        ),
        migrations.CreateModel(
            name="GananciaPeso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "peso_pregestacional",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Peso Pregestacional (kg)",
                    ),
                ),
                (
                    "peso_actual",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Peso Actual (kg)",
                    ),
                ),
                (
                    "semanas_gestacion",
                    models.IntegerField(verbose_name="Semanas de Gestación"),
                ),
                (
                    "imc_pregestacional",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="IMC Pregestacional",
                    ),
                ),
                (
                    "ganancia_peso_actual",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Ganancia de Peso Actual (kg)",
                    ),
                ),
                (
                    "ganancia_peso_esperada_min",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Ganancia Esperada Mínima (kg)",
                    ),
                ),
                (
                    "ganancia_peso_esperada_max",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Ganancia Esperada Máxima (kg)",
                    ),
                ),
                ("adecuada", models.BooleanField(verbose_name="Ganancia Adecuada")),
                (
                    "interpretacion",
                    models.CharField(max_length=200, verbose_name="Interpretación"),
                ),
                (
                    "calculo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ganancia_peso",
                        to="calculadoras.calculoclinico",
                        verbose_name="Cálculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ganancia de Peso",
                "verbose_name_plural": "Ganancias de Peso",
                "db_table": "calculos_ganancia_peso",
            },
        ),
        migrations.CreateModel(
            name="IndiceLiquidoAmniotico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semanas_gestacion",
                    models.IntegerField(verbose_name="Semanas de Gestación"),
                ),
                (
                    "cuadrante_1",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Cuadrante Superior Derecho (mm)",
                    ),
                ),
                (
                    "cuadrante_2",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Cuadrante Superior Izquierdo (mm)",
                    ),
                ),
                (
                    "cuadrante_3",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Cuadrante Inferior Derecho (mm)",
                    ),
                ),
                (
                    "cuadrante_4",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Cuadrante Inferior Izquierdo (mm)",
                    ),
                ),
                (
                    "ila",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Índice de Líquido Amniótico (mm)",
                    ),
                ),
                (
                    "interpretacion",
                    models.CharField(
                        choices=[
                            ("oligohidramnios", "Oligohidramnios"),
                            ("normal", "Normal"),
                            ("polihidramnios", "Polihidramnios"),
                        ],
                        max_length=20,
                        verbose_name="Interpretación",
                    ),
                ),
                (
                    "calculo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ila",
                        to="calculadoras.calculoclinico",
                        verbose_name="Cálculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Índice de Líquido Amniótico",
                "verbose_name_plural": "Índices de Líquido Amniótico",
                "db_table": "calculos_ila",
            },
        ),
        migrations.CreateModel(
            name="IndiceMasaCorporal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "peso",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Peso (kg)",
                    ),
                ),
                (
                    "altura",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Altura (cm)",
                    ),
                ),
                (
                    "imc",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="IMC",
                    ),
                ),
                (
                    "clasificacion",
                    models.CharField(
                        choices=[
                            ("bajo_peso", "Bajo Peso"),
                            ("normal", "Normal"),
                            ("sobrepeso", "Sobrepeso"),
                            ("obesidad_i", "Obesidad Grado I"),
                            ("obesidad_ii", "Obesidad Grado II"),
                            ("obesidad_iii", "Obesidad Grado III"),
                        ],
                        default="aeg",
                        max_length=20,
                        verbose_name="Clasificacion",
                    ),
                ),
                (
                    "ganancia_peso_recomendada_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Ganancia de Peso Mínima Recomendada (kg)",
                    ),
                ),
                (
                    "ganancia_peso_recomendada_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Ganancia de Peso Máxima Recomendada (kg)",
                    ),
                ),
                (
                    "calculo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imc",
                        to="calculadoras.calculoclinico",
                        verbose_name="Cálculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Índice de Masa Corporal",
                "verbose_name_plural": "Índices de Masa Corporal",
                "db_table": "calculos_imc",
            },
        ),
        migrations.CreateModel(
            name="PesoFetal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semanas_gestacion",
                    models.IntegerField(verbose_name="Semanas de Gestación"),
                ),
                (
                    "dbp",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Diámetro Biparietal (mm)",
                    ),
                ),
                (
                    "cc",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Circunferencia Cefálica (mm)",
                    ),
                ),
                (
                    "ca",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Circunferencia Abdominal (mm)",
                    ),
                ),
                (
                    "lf",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Longitud del Fémur (mm)",
                    ),
                ),
                (
                    "peso_estimado",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Peso Fetal Estimado (gramos)",
                    ),
                ),
                (
                    "percentil",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Percentil de Peso",
                    ),
                ),
                (
                    "clasificacion",
                    models.CharField(
                        choices=[
                            ("rciu", "Restricción de Crecimiento Intrauterino"),
                            ("peg", "Pequeño para Edad Gestacional"),
                            ("aeg", "Adecuado para Edad Gestacional"),
                            ("geg", "Grande para Edad Gestacional"),
                            ("macrosomia", "Macrosomía"),
                        ],
                        max_length=20,
                        verbose_name="Clasificación",
                    ),
                ),
                (
                    "calculo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peso_fetal",
                        to="calculadoras.calculoclinico",
                        verbose_name="Cálculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Peso Fetal",
                "verbose_name_plural": "Pesos Fetales",
                "db_table": "calculos_peso_fetal",
            },
        ),
        migrations.CreateModel(
            name="PresionArterialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "presion_sistolica",
                    models.IntegerField(verbose_name="Presión Sistólica (mmHg)"),
                ),
                (
                    "presion_diastolica",
                    models.IntegerField(verbose_name="Presión Diastólica (mmHg)"),
                ),
                (
                    "pam",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Presión Arterial Media (mmHg)",
                    ),
                ),
                (
                    "interpretacion",
                    models.CharField(
                        choices=[
                            ("hipotension", "Hipotensión (<70 mmHg)"),
                            ("normal", "Normal (70-100 mmHg)"),
                            ("elevada", "Elevada (100-110 mmHg)"),
                            ("hipertension", "Hipertensión (>110 mmHg)"),
                        ],
                        max_length=20,
                        verbose_name="Interpretación",
                    ),
                ),
                (
                    "calculo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pam",
                        to="calculadoras.calculoclinico",
                        verbose_name="Cálculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presión Arterial Media",
                "verbose_name_plural": "Presiones Arteriales Medias",
                "db_table": "calculos_pam",
            },
        ),
        migrations.CreateModel(
            name="PuntajeApgar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "minuto",
                    models.IntegerField(
                        choices=[(1, "1 minuto"), (5, "5 minutos"), (10, "10 minutos")],
                        verbose_name="Momento de Evaluación",
                    ),
                ),
                (
                    "frecuencia_cardiaca",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2),
                        ],
                        verbose_name="Frecuencia Cardíaca",
                    ),
                ),
                (
                    "esfuerzo_respiratorio",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2),
                        ],
                        verbose_name="Esfuerzo Respiratorio",
                    ),
                ),
                (
                    "tono_muscular",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2),
                        ],
                        verbose_name="Tono Muscular",
                    ),
                ),
                (
                    "irritabilidad_refleja",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2),
                        ],
                        verbose_name="Irritabilidad Refleja",
                    ),
                ),
                (
                    "coloracion",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2),
                        ],
                        verbose_name="Coloración",
                    ),
                ),
                ("puntaje_total", models.IntegerField(verbose_name="Puntaje Total")),
                (
                    "interpretacion",
                    models.CharField(
                        choices=[
                            ("critico", "Crítico (0-3)"),
                            ("depresion_moderada", "Depresión Moderada (4-6)"),
                            ("normal", "Normal (7-10)"),
                        ],
                        max_length=30,
                        verbose_name="Interpretación",
                    ),
                ),
                (
                    "calculo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apgar",
                        to="calculadoras.calculoclinico",
                        verbose_name="Cálculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Puntaje Apgar",
                "verbose_name_plural": "Puntajes Apgar",
                "db_table": "calculos_apgar",
            },
        ),
        migrations.CreateModel(
            name="PuntajeBishop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dilatacion",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Dilatación Cervical (cm)",
                    ),
                ),
                (
                    "borramiento",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Borramiento (%)",
                    ),
                ),
                (
                    "estacion",
                    models.IntegerField(
                        choices=[
                            (-3, "-3"),
                            (-2, "-2"),
                            (-1, "-1"),
                            (0, "0"),
                            (1, "+1"),
                            (2, "+2"),
                        ],
                        verbose_name="Estación de la Presentación",
                    ),
                ),
                (
                    "consistencia",
                    models.IntegerField(
                        choices=[(0, "Firme"), (1, "Media"), (2, "Blanda")],
                        verbose_name="Consistencia Cervical",
                    ),
                ),
                (
                    "posicion",
                    models.IntegerField(
                        choices=[(0, "Posterior"), (1, "Media"), (2, "Anterior")],
                        verbose_name="Posición Cervical",
                    ),
                ),
                (
                    "puntaje_total",
                    models.IntegerField(verbose_name="Puntaje Total de Bishop"),
                ),
                (
                    "interpretacion",
                    models.CharField(max_length=100, verbose_name="Interpretación"),
                ),
                (
                    "calculo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bishop",
                        to="calculadoras.calculoclinico",
                        verbose_name="Cálculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Puntaje de Bishop",
                "verbose_name_plural": "Puntajes de Bishop",
                "db_table": "calculos_bishop",
            },
        ),
        migrations.CreateModel(
            name="RiesgoEndometrio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edad", models.IntegerField(verbose_name="Edad (años)")),
                (
                    "obesidad",
                    models.BooleanField(
                        default=False, verbose_name="Obesidad (IMC ≥30)",
                    ),
                ),
                (
                    "diabetes",
                    models.BooleanField(
                        default=False, verbose_name="Diabetes Mellitus",
                    ),
                ),
                (
                    "hipertension",
                    models.BooleanField(default=False, verbose_name="Hipertensión"),
                ),
                (
                    "nuliparidad",
                    models.BooleanField(default=False, verbose_name="Nuliparidad"),
                ),
                (
                    "menarquia_temprana",
                    models.BooleanField(
                        default=False, verbose_name="Menarquia Temprana (<12 años)",
                    ),
                ),
                (
                    "menopausia_tardia",
                    models.BooleanField(
                        default=False, verbose_name="Menopausia Tardía (>55 años)",
                    ),
                ),
                (
                    "terapia_hormonal",
                    models.BooleanField(
                        default=False,
                        verbose_name="Terapia con Estrógenos sin Oposición",
                    ),
                ),
                (
                    "tamoxifeno",
                    models.BooleanField(
                        default=False, verbose_name="Uso de Tamoxifeno",
                    ),
                ),
                (
                    "sindrome_ovario_poliquistico",
                    models.BooleanField(
                        default=False, verbose_name="Síndrome de Ovario Poliquístico",
                    ),
                ),
                (
                    "antecedente_familiar",
                    models.BooleanField(
                        default=False,
                        verbose_name="Antecedente Familiar de Cáncer Endometrial",
                    ),
                ),
                (
                    "grosor_endometrial",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Grosor Endometrial (mm)",
                    ),
                ),
                (
                    "factores_riesgo_count",
                    models.IntegerField(
                        default=0, verbose_name="Cantidad de Factores de Riesgo",
                    ),
                ),
                (
                    "nivel_riesgo",
                    models.CharField(
                        choices=[
                            ("bajo", "Bajo Riesgo"),
                            ("moderado", "Riesgo Moderado"),
                            ("alto", "Alto Riesgo"),
                        ],
                        max_length=20,
                        verbose_name="Nivel de Riesgo",
                    ),
                ),
                (
                    "requiere_biopsia",
                    models.BooleanField(
                        default=False, verbose_name="Requiere Biopsia Endometrial",
                    ),
                ),
                (
                    "calculo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="riesgo_endometrio",
                        to="calculadoras.calculoclinico",
                        verbose_name="Cálculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Riesgo de Cáncer de Endometrio",
                "verbose_name_plural": "Riesgos de Cáncer de Endometrio",
                "db_table": "calculos_riesgo_endometrio",
            },
        ),
        migrations.CreateModel(
            name="RiesgoPreeclampsia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edad", models.IntegerField(verbose_name="Edad (años)")),
                (
                    "primiparidad",
                    models.BooleanField(default=False, verbose_name="Primiparidad"),
                ),
                (
                    "antecedente_preeclampsia",
                    models.BooleanField(
                        default=False, verbose_name="Antecedente de Preeclampsia",
                    ),
                ),
                (
                    "diabetes",
                    models.BooleanField(default=False, verbose_name="Diabetes"),
                ),
                (
                    "hipertension_cronica",
                    models.BooleanField(
                        default=False, verbose_name="Hipertensión Crónica",
                    ),
                ),
                (
                    "obesidad",
                    models.BooleanField(
                        default=False, verbose_name="Obesidad (IMC ≥30)",
                    ),
                ),
                (
                    "embarazo_multiple",
                    models.BooleanField(
                        default=False, verbose_name="Embarazo Múltiple",
                    ),
                ),
                (
                    "enfermedad_renal",
                    models.BooleanField(
                        default=False, verbose_name="Enfermedad Renal Crónica",
                    ),
                ),
                (
                    "enfermedad_autoinmune",
                    models.BooleanField(
                        default=False, verbose_name="Enfermedad Autoinmune",
                    ),
                ),
                (
                    "nivel_riesgo",
                    models.CharField(
                        choices=[
                            ("bajo", "Bajo Riesgo"),
                            ("moderado", "Riesgo Moderado"),
                            ("alto", "Alto Riesgo"),
                        ],
                        max_length=20,
                        verbose_name="Nivel de Riesgo",
                    ),
                ),
                (
                    "recomienda_aspirina",
                    models.BooleanField(
                        default=False, verbose_name="Recomienda Aspirina Profiláctica",
                    ),
                ),
                (
                    "factores_riesgo_count",
                    models.IntegerField(
                        default=0, verbose_name="Cantidad de Factores de Riesgo",
                    ),
                ),
                (
                    "calculo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="riesgo_preeclampsia",
                        to="calculadoras.calculoclinico",
                        verbose_name="Cálculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Riesgo de Preeclampsia",
                "verbose_name_plural": "Riesgos de Preeclampsia",
                "db_table": "calculos_riesgo_preeclampsia",
            },
        ),
        migrations.CreateModel(
            name="RMIOvario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado_menopausia",
                    models.CharField(
                        choices=[
                            ("premenopausia", "Premenopausia"),
                            ("postmenopausia", "Postmenopausia"),
                        ],
                        max_length=20,
                        verbose_name="Estado Menopáusico",
                    ),
                ),
                (
                    "masa_multilocular",
                    models.BooleanField(
                        default=False, verbose_name="Masa Multilocular",
                    ),
                ),
                (
                    "masa_solida",
                    models.BooleanField(default=False, verbose_name="Áreas Sólidas"),
                ),
                (
                    "masa_bilateral",
                    models.BooleanField(
                        default=False, verbose_name="Lesiones Bilaterales",
                    ),
                ),
                ("ascitis", models.BooleanField(default=False, verbose_name="Ascitis")),
                (
                    "metastasis",
                    models.BooleanField(
                        default=False, verbose_name="Evidencia de Metástasis",
                    ),
                ),
                (
                    "ca125",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="CA-125 (U/ml)",
                    ),
                ),
                (
                    "puntuacion_u",
                    models.IntegerField(verbose_name="Puntuación Ecográfica (U)"),
                ),
                (
                    "factor_m",
                    models.IntegerField(verbose_name="Factor Menopáusico (M)"),
                ),
                (
                    "rmi",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="RMI (U x M x CA-125)",
                    ),
                ),
                (
                    "nivel_riesgo",
                    models.CharField(
                        choices=[
                            ("bajo", "Bajo Riesgo (<25)"),
                            ("intermedio", "Riesgo Intermedio (25-250)"),
                            ("alto", "Alto Riesgo (>250)"),
                        ],
                        max_length=20,
                        verbose_name="Nivel de Riesgo",
                    ),
                ),
                (
                    "calculo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rmi_ovario",
                        to="calculadoras.calculoclinico",
                        verbose_name="Cálculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "RMI de Ovario",
                "verbose_name_plural": "RMI de Ovarios",
                "db_table": "calculos_rmi_ovario",
            },
        ),
        migrations.CreateModel(
            name="SuperficieCorporal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "peso",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Peso (kg)",
                    ),
                ),
                (
                    "altura",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Altura (cm)",
                    ),
                ),
                (
                    "superficie_corporal",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Superficie Corporal (m²)",
                    ),
                ),
                (
                    "calculo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="superficie_corporal",
                        to="calculadoras.calculoclinico",
                        verbose_name="Cálculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Superficie Corporal",
                "verbose_name_plural": "Superficies Corporales",
                "db_table": "calculos_superficie_corporal",
            },
        ),
        migrations.AddIndex(
            model_name="calculoclinico",
            index=models.Index(
                fields=["paciente", "-fecha_calculo"],
                name="calculos_cl_pacient_64eda3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="calculoclinico",
            index=models.Index(
                fields=["tipo_calculo"], name="calculos_cl_tipo_ca_8f3fc8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="calculoclinico",
            index=models.Index(
                fields=["embarazo"], name="calculos_cl_embaraz_ae0f2c_idx",
            ),
        ),
    ]
