# Generated by Django 5.1.3 on 2025-11-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calculadoras", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculoclinico",
            name="tipo_calculo",
            field=models.CharField(
                choices=[
                    ("edad_gestacional", "Edad Gestacional y FPP"),
                    ("imc", "Índice de Masa Corporporal"),
                    ("ganancia_peso", "Ganancia de Peso Gestacional"),
                    ("bishop", "Puntaje de Bishop"),
                    ("preeclampsia", "Riesgo de Preeclampsia"),
                    ("diabetes_gestacional", "Tamizaje Diabetes Gestacional"),
                    ("ila", "Índice de Líquido Amniótico"),
                    ("peso_fetal", "Estimación de Peso Fetal"),
                    ("apgar", "Puntaje Apgar"),
                    ("percentil_peso", "Percentil de Peso Fetal"),
                    ("rmi_ovario", "Riesgo de Cáncer de Ovario (RMI)"),
                    ("riesgo_endometrio", "Riesgo de Cáncer de Endometrio"),
                    ("pam", "Presión Arterial Media"),
                    ("superficie_corporal", "Superficie Corporal"),
                ],
                max_length=50,
                verbose_name="Tipo de Cálculo",
            ),
        ),
        migrations.AlterField(
            model_name="indicemasacorporal",
            name="clasificacion",
            field=models.CharField(
                choices=[
                    ("bajo_peso", "Bajo Peso"),
                    ("normal", "Normal"),
                    ("sobrepeso", "Sobrepeso"),
                    ("obesidad_i", "Obesidad Grado I"),
                    ("obesidad_ii", "Obesidad Grado II"),
                    ("obesidad_iii", "Obesidad Grado III"),
                ],
                default="normal",
                max_length=20,
                verbose_name="Clasificación",
            ),
        ),
    ]
