# Generated by Django 5.1.3 on 2025-12-17 22:27

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calculadoras", "0002_alter_calculoclinico_tipo_calculo_and_more"),
        ("embarazos", "0004_embarazo_peso_pregestacional_embarazo_talla_materna"),
        ("pacientes", "0005_paciente_estado_civil_paciente_ocupacion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Eliminar índices ANTES de eliminar los campos que referencian
        # (requerido por SQLite que recrea la tabla al eliminar columnas)
        migrations.RemoveIndex(
            model_name="calculoclinico",
            name="calculos_cl_embaraz_ae0f2c_idx",
        ),
        migrations.RemoveIndex(
            model_name="calculoclinico",
            name="calculos_cl_pacient_64eda3_idx",
        ),
        migrations.RemoveIndex(
            model_name="calculoclinico",
            name="calculos_cl_tipo_ca_8f3fc8_idx",
        ),
        migrations.RemoveField(
            model_name="calculoclinico",
            name="control_prenatal",
        ),
        migrations.RemoveField(
            model_name="calculoclinico",
            name="embarazo",
        ),
        migrations.RemoveField(
            model_name="calculoclinico",
            name="paciente",
        ),
        migrations.RemoveField(
            model_name="calculoclinico",
            name="realizado_por",
        ),
        migrations.RemoveField(
            model_name="pesofetal",
            name="calculo",
        ),
        migrations.RemoveField(
            model_name="riesgopreeclampsia",
            name="calculo",
        ),
        migrations.RemoveField(
            model_name="indiceliquidoamniotico",
            name="calculo",
        ),
        migrations.RemoveField(
            model_name="rmiovario",
            name="calculo",
        ),
        migrations.RemoveField(
            model_name="diabetesgestacional",
            name="calculo",
        ),
        migrations.RemoveField(
            model_name="superficiecorporal",
            name="calculo",
        ),
        migrations.RemoveField(
            model_name="presionarterialmedia",
            name="calculo",
        ),
        migrations.RemoveField(
            model_name="indicemasacorporal",
            name="calculo",
        ),
        migrations.RemoveField(
            model_name="riesgoendometrio",
            name="calculo",
        ),
        migrations.RemoveField(
            model_name="puntajebishop",
            name="calculo",
        ),
        migrations.RemoveField(
            model_name="edadgestacional",
            name="calculo",
        ),
        migrations.RemoveField(
            model_name="gananciapeso",
            name="calculo",
        ),
        migrations.CreateModel(
            name="Bioquimica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_toma", models.DateTimeField()),
                ("fecha_resultado", models.DateTimeField(auto_now_add=True)),
                ("semanas_gestacion", models.IntegerField(blank=True, null=True)),
                (
                    "glucosa_ayunas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="mg/dL",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "glucosa_postprandial",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="mg/dL",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "hba1c",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="%",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "creatinina",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="mg/dL",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "urea",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="mg/dL",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "acido_urico",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="mg/dL",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "got_ast",
                    models.IntegerField(blank=True, help_text="U/L", null=True),
                ),
                (
                    "gpt_alt",
                    models.IntegerField(blank=True, help_text="U/L", null=True),
                ),
                (
                    "bilirrubina_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="mg/dL",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "bilirrubina_directa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="mg/dL",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "fosfatasa_alcalina",
                    models.IntegerField(blank=True, help_text="U/L", null=True),
                ),
                (
                    "albumina",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="g/dL",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "sodio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="mEq/L",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "potasio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="mEq/L",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "cloro",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="mEq/L",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "calcio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="mg/dL",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "magnesio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="mg/dL",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "colesterol_total",
                    models.IntegerField(blank=True, help_text="mg/dL", null=True),
                ),
                ("ldl", models.IntegerField(blank=True, help_text="mg/dL", null=True)),
                ("hdl", models.IntegerField(blank=True, help_text="mg/dL", null=True)),
                (
                    "trigliceridos",
                    models.IntegerField(blank=True, help_text="mg/dL", null=True),
                ),
                (
                    "proteinas_totales",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="g/dL",
                        max_digits=3,
                        null=True,
                    ),
                ),
                ("ldh", models.IntegerField(blank=True, help_text="U/L", null=True)),
                ("clasificacion", models.CharField(blank=True, max_length=50)),
                ("alertas", models.JSONField(blank=True, default=list)),
                ("es_critico", models.BooleanField(default=False)),
                ("interpretacion_automatica", models.TextField(blank=True)),
                ("observaciones_medicas", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "embarazo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="embarazos.embarazo",
                    ),
                ),
                (
                    "medico_solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bioquimicas",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "db_table": "laboratorio_bioquimica",
                "ordering": ["-fecha_toma"],
            },
        ),
        migrations.CreateModel(
            name="CalculadoraRiesgo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("preeclampsia", "Preeclampsia"),
                            ("trisomias", "Trisomías (21, 18, 13)"),
                            ("diabetes_gestacional", "Diabetes Gestacional"),
                            ("sga_rciu", "Restricción Crecimiento (SGA/RCIU)"),
                            ("parto_pretermino", "Parto Pretérmino"),
                            ("macrosomia", "Macrosomía Fetal"),
                            ("aborto", "Aborto Espontáneo"),
                            ("obito", "Óbito Fetal"),
                            ("anemia_fetal", "Anemia Fetal"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Calculadora",
                    ),
                ),
                (
                    "edad_gestacional_semanas",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(42),
                        ],
                        verbose_name="Edad Gestacional (semanas)",
                    ),
                ),
                (
                    "edad_gestacional_dias",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                        verbose_name="Días adicionales",
                    ),
                ),
                (
                    "edad_materna",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(60),
                        ],
                        verbose_name="Edad Materna (años)",
                    ),
                ),
                (
                    "peso_kg",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("30.00")),
                            django.core.validators.MaxValueValidator(Decimal("200.00")),
                        ],
                        verbose_name="Peso (kg)",
                    ),
                ),
                (
                    "talla_cm",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("120.00")),
                            django.core.validators.MaxValueValidator(Decimal("220.00")),
                        ],
                        verbose_name="Talla (cm)",
                    ),
                ),
                (
                    "imc",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Calculado automáticamente",
                        max_digits=5,
                        verbose_name="IMC",
                    ),
                ),
                (
                    "etnia",
                    models.CharField(
                        choices=[
                            ("caucasica", "Caucásica"),
                            ("afrocaribeña", "Afrocaribeña"),
                            ("sudasiatica", "Sudasiática"),
                            ("indigena", "Indígena"),
                            ("mestiza", "Mestiza"),
                            ("otra", "Otra"),
                        ],
                        default="mestiza",
                        max_length=20,
                        verbose_name="Etnia",
                    ),
                ),
                (
                    "tabaquismo",
                    models.BooleanField(default=False, verbose_name="Fumadora Activa"),
                ),
                (
                    "hta_cronica",
                    models.BooleanField(
                        default=False, verbose_name="Hipertensión Crónica",
                    ),
                ),
                (
                    "diabetes_previa",
                    models.BooleanField(
                        default=False, verbose_name="Diabetes Pregestacional",
                    ),
                ),
                (
                    "diabetes_tipo",
                    models.CharField(
                        choices=[
                            ("tipo1", "Tipo 1"),
                            ("tipo2", "Tipo 2"),
                            ("ninguna", "Ninguna"),
                        ],
                        default="ninguna",
                        max_length=10,
                        verbose_name="Tipo de Diabetes",
                    ),
                ),
                (
                    "lupus",
                    models.BooleanField(
                        default=False, verbose_name="Lupus Eritematoso Sistémico",
                    ),
                ),
                (
                    "sindrome_antifosfolipido",
                    models.BooleanField(
                        default=False, verbose_name="Síndrome Antifosfolípido",
                    ),
                ),
                (
                    "preeclampsia_previa",
                    models.BooleanField(
                        default=False, verbose_name="Preeclampsia Previa",
                    ),
                ),
                (
                    "diabetes_gestacional_previa",
                    models.BooleanField(
                        default=False, verbose_name="Diabetes Gestacional Previa",
                    ),
                ),
                (
                    "parto_pretermino_previo",
                    models.BooleanField(
                        default=False, verbose_name="Parto Pretérmino Previo",
                    ),
                ),
                (
                    "macrosomia_previa",
                    models.BooleanField(
                        default=False, verbose_name="Macrosomía Previa (>4000g)",
                    ),
                ),
                (
                    "historia_familiar_diabetes",
                    models.BooleanField(
                        default=False, verbose_name="Historia Familiar de Diabetes",
                    ),
                ),
                (
                    "madre_con_preeclampsia",
                    models.BooleanField(
                        default=False, verbose_name="Madre con Preeclampsia",
                    ),
                ),
                (
                    "paridad",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Paridad (gestas previas)",
                    ),
                ),
                (
                    "intervalo_interembarazo_meses",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Intervalo Interembarazo (meses)",
                    ),
                ),
                (
                    "metodo_concepcion",
                    models.CharField(
                        choices=[
                            ("espontaneo", "Espontáneo"),
                            ("ivf", "FIV"),
                            ("otro", "Otro"),
                        ],
                        default="espontaneo",
                        max_length=20,
                        verbose_name="Método de Concepción",
                    ),
                ),
                (
                    "riesgo_porcentaje",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="Riesgo (%)",
                    ),
                ),
                (
                    "riesgo_ratio",
                    models.CharField(
                        blank=True,
                        help_text="Ejemplo: 1:85",
                        max_length=20,
                        null=True,
                        verbose_name="Riesgo (ratio)",
                    ),
                ),
                (
                    "categoria_riesgo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bajo", "Bajo Riesgo"),
                            ("intermedio", "Riesgo Intermedio"),
                            ("alto", "Alto Riesgo"),
                            ("critico", "Riesgo Crítico"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Categoría de Riesgo",
                    ),
                ),
                (
                    "interpretacion_clinica",
                    models.TextField(
                        blank=True, null=True, verbose_name="Interpretación Clínica",
                    ),
                ),
                (
                    "recomendaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Recomendaciones",
                    ),
                ),
                (
                    "conducta_sugerida",
                    models.TextField(
                        blank=True, null=True, verbose_name="Conducta Sugerida",
                    ),
                ),
                (
                    "fecha_calculo",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Cálculo",
                    ),
                ),
                (
                    "notas_adicionales",
                    models.TextField(
                        blank=True, verbose_name="Notas Adicionales del Profesional",
                    ),
                ),
                (
                    "calculado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calculadoras_realizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Calculado Por",
                    ),
                ),
                (
                    "embarazo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculadoras_riesgo",
                        to="embarazos.embarazo",
                        verbose_name="Embarazo Asociado",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculadoras_riesgo",
                        to="pacientes.paciente",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calculadora de Riesgo",
                "verbose_name_plural": "Calculadoras de Riesgo",
                "db_table": "calculadoras_riesgo",
                "ordering": ["-fecha_calculo"],
            },
        ),
        migrations.CreateModel(
            name="BiomarcadorMOM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marcador",
                    models.CharField(
                        choices=[
                            ("pappa", "PAPP-A"),
                            ("bhcg", "β-hCG libre"),
                            ("plgf", "PLGF (Factor Crecimiento Placentario)"),
                            ("sflt1", "sFlt-1 (Factor Antiangiogénico)"),
                            ("pam", "PAM (Presión Arterial Media)"),
                            ("utpi", "UtA-PI (Índice Pulsatilidad Arteria Uterina)"),
                            ("afp", "AFP (Alfafetoproteína)"),
                            ("bhcg_total", "β-hCG Total"),
                            ("estriol", "Estriol Libre"),
                            ("inhibina_a", "Inhibina A"),
                        ],
                        max_length=20,
                        verbose_name="Marcador",
                    ),
                ),
                (
                    "valor_crudo",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="Valor Crudo",
                    ),
                ),
                (
                    "unidad",
                    models.CharField(
                        help_text="Ej: mIU/mL, ng/mL, mmHg",
                        max_length=50,
                        verbose_name="Unidad",
                    ),
                ),
                (
                    "mediana_esperada",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        verbose_name="Mediana Esperada (ajustada)",
                    ),
                ),
                (
                    "mediana_base",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Mediana Base (sin ajustes)",
                    ),
                ),
                (
                    "mom_calculado",
                    models.DecimalField(
                        decimal_places=3, max_digits=6, verbose_name="MoM Calculado",
                    ),
                ),
                (
                    "correccion_peso",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("1.000"),
                        max_digits=5,
                        verbose_name="Factor Corrección Peso",
                    ),
                ),
                (
                    "correccion_etnia",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("1.000"),
                        max_digits=5,
                        verbose_name="Factor Corrección Etnia",
                    ),
                ),
                (
                    "correccion_tabaco",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("1.000"),
                        max_digits=5,
                        verbose_name="Factor Corrección Tabaco",
                    ),
                ),
                (
                    "correccion_diabetes",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("1.000"),
                        max_digits=5,
                        verbose_name="Factor Corrección Diabetes",
                    ),
                ),
                (
                    "dentro_rango",
                    models.BooleanField(
                        default=True, verbose_name="Dentro del Rango Normal (0.8-1.2)",
                    ),
                ),
                (
                    "interpretacion",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Interpretación",
                    ),
                ),
                (
                    "fecha_medicion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Medición",
                    ),
                ),
                (
                    "calculadora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biomarcadores",
                        to="calculadoras.calculadorariesgo",
                        verbose_name="Calculadora",
                    ),
                ),
            ],
            options={
                "verbose_name": "Biomarcador MoM",
                "verbose_name_plural": "Biomarcadores MoM",
                "db_table": "biomarcadores_mom",
                "ordering": ["calculadora", "marcador"],
            },
        ),
        migrations.CreateModel(
            name="Hemograma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_toma", models.DateTimeField()),
                ("fecha_resultado", models.DateTimeField(auto_now_add=True)),
                (
                    "semanas_gestacion",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(42),
                        ],
                    ),
                ),
                (
                    "hemoglobina",
                    models.DecimalField(
                        decimal_places=1, help_text="g/dL", max_digits=4,
                    ),
                ),
                (
                    "hematocrito",
                    models.DecimalField(decimal_places=1, help_text="%", max_digits=4),
                ),
                (
                    "eritrocitos",
                    models.DecimalField(
                        decimal_places=2, help_text="mill/µL", max_digits=4,
                    ),
                ),
                (
                    "vcm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="fL",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "hcm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="pg",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "chcm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="g/dL",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "rdw",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="%",
                        max_digits=4,
                        null=True,
                    ),
                ),
                ("leucocitos", models.IntegerField(help_text="/µL")),
                (
                    "neutrofilos",
                    models.IntegerField(blank=True, help_text="/µL", null=True),
                ),
                (
                    "linfocitos",
                    models.IntegerField(blank=True, help_text="/µL", null=True),
                ),
                (
                    "monocitos",
                    models.IntegerField(blank=True, help_text="/µL", null=True),
                ),
                (
                    "eosinofilos",
                    models.IntegerField(blank=True, help_text="/µL", null=True),
                ),
                (
                    "basofilos",
                    models.IntegerField(blank=True, help_text="/µL", null=True),
                ),
                ("plaquetas", models.IntegerField(help_text="/µL")),
                (
                    "vpm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="fL",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "clasificacion",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("ANEMIA_LEVE", "Anemia Leve"),
                            ("ANEMIA_MODERADA", "Anemia Moderada"),
                            ("ANEMIA_SEVERA", "Anemia Severa"),
                            ("LEUCOCITOSIS", "Leucocitosis"),
                            ("LEUCOPENIA", "Leucopenia"),
                            ("TROMBOCITOPENIA", "Trombocitopenia"),
                            ("TROMBOCITOSIS", "Trombocitosis"),
                        ],
                        max_length=30,
                    ),
                ),
                ("es_critico", models.BooleanField(default=False)),
                ("alertas", models.JSONField(blank=True, default=list)),
                ("interpretacion_automatica", models.TextField(blank=True)),
                ("observaciones_medicas", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "embarazo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hemogramas",
                        to="embarazos.embarazo",
                    ),
                ),
                (
                    "medico_solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hemogramas_solicitados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hemogramas",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "db_table": "laboratorio_hemograma",
                "ordering": ["-fecha_toma"],
            },
        ),
        migrations.CreateModel(
            name="MarcadorEmbarazo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_toma", models.DateTimeField()),
                ("semanas_gestacion", models.IntegerField()),
                (
                    "dias_adicionales",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "beta_hcg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="mIU/mL",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "papp_a",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="mIU/mL",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "free_bhcg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="ng/mL",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "plgf",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="pg/mL",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "sflt1",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="pg/mL",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "beta_hcg_mom",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True,
                    ),
                ),
                (
                    "papp_a_mom",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True,
                    ),
                ),
                (
                    "free_bhcg_mom",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True,
                    ),
                ),
                (
                    "plgf_mom",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True,
                    ),
                ),
                (
                    "sflt1_mom",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True,
                    ),
                ),
                (
                    "ratio_sflt_plgf",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True,
                    ),
                ),
                ("clasificacion", models.CharField(blank=True, max_length=50)),
                ("alertas", models.JSONField(blank=True, default=list)),
                ("interpretacion_automatica", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "embarazo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="embarazos.embarazo",
                    ),
                ),
                (
                    "medico_solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "db_table": "laboratorio_marcador_embarazo",
                "ordering": ["-fecha_toma"],
            },
        ),
        migrations.CreateModel(
            name="MedicionEcografica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crl_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Longitud céfalo-nalgas (9-14 semanas)",
                        max_digits=6,
                        null=True,
                        verbose_name="CRL - Crown-Rump Length (mm)",
                    ),
                ),
                (
                    "nt_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Importante para trisomías (11-13+6 semanas)",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("10.00")),
                        ],
                        verbose_name="NT - Translucencia Nucal (mm)",
                    ),
                ),
                (
                    "fcf_lpm",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(220),
                        ],
                        verbose_name="FCF - Frecuencia Cardíaca Fetal (lpm)",
                    ),
                ),
                (
                    "bpd_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="BPD - Diámetro Biparietal (mm)",
                    ),
                ),
                (
                    "hc_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="HC - Circunferencia Cefálica (mm)",
                    ),
                ),
                (
                    "ac_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="AC - Circunferencia Abdominal (mm)",
                    ),
                ),
                (
                    "fl_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="FL - Longitud Fémur (mm)",
                    ),
                ),
                (
                    "efw_gramos",
                    models.IntegerField(
                        blank=True,
                        help_text="Calculado por fórmula de Hadlock",
                        null=True,
                        verbose_name="EFW - Peso Fetal Estimado (gramos)",
                    ),
                ),
                (
                    "nt_percentil",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(99),
                        ],
                        verbose_name="NT Percentil",
                    ),
                ),
                (
                    "efw_percentil",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(99),
                        ],
                        verbose_name="EFW Percentil",
                    ),
                ),
                (
                    "crl_percentil",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(99),
                        ],
                        verbose_name="CRL Percentil",
                    ),
                ),
                (
                    "longitud_cervical_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Medición transvaginal (20-26 semanas)",
                        max_digits=4,
                        null=True,
                        verbose_name="Longitud Cervical (mm)",
                    ),
                ),
                (
                    "fecha_medicion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Medición",
                    ),
                ),
                (
                    "calculadora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mediciones_eco",
                        to="calculadoras.calculadorariesgo",
                        verbose_name="Calculadora",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medición Ecográfica",
                "verbose_name_plural": "Mediciones Ecográficas",
                "db_table": "mediciones_ecograficas",
                "ordering": ["-fecha_medicion"],
            },
        ),
        migrations.DeleteModel(
            name="PuntajeApgar",
        ),
        migrations.DeleteModel(
            name="PesoFetal",
        ),
        migrations.DeleteModel(
            name="RiesgoPreeclampsia",
        ),
        migrations.DeleteModel(
            name="IndiceLiquidoAmniotico",
        ),
        migrations.DeleteModel(
            name="RMIOvario",
        ),
        migrations.DeleteModel(
            name="DiabetesGestacional",
        ),
        migrations.DeleteModel(
            name="SuperficieCorporal",
        ),
        migrations.DeleteModel(
            name="PresionArterialMedia",
        ),
        migrations.DeleteModel(
            name="IndiceMasaCorporal",
        ),
        migrations.DeleteModel(
            name="RiesgoEndometrio",
        ),
        migrations.DeleteModel(
            name="PuntajeBishop",
        ),
        migrations.DeleteModel(
            name="EdadGestacional",
        ),
        migrations.DeleteModel(
            name="CalculoClinico",
        ),
        migrations.DeleteModel(
            name="GananciaPeso",
        ),
        migrations.AddIndex(
            model_name="calculadorariesgo",
            index=models.Index(
                fields=["paciente", "-fecha_calculo"],
                name="calculadora_pacient_0f0a03_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="calculadorariesgo",
            index=models.Index(
                fields=["tipo", "-fecha_calculo"], name="calculadora_tipo_a256d5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="calculadorariesgo",
            index=models.Index(
                fields=["categoria_riesgo"], name="calculadora_categor_0935e1_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="biomarcadormom",
            unique_together={("calculadora", "marcador")},
        ),
        migrations.AddIndex(
            model_name="hemograma",
            index=models.Index(
                fields=["paciente", "-fecha_toma"],
                name="laboratorio_pacient_578ff6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hemograma",
            index=models.Index(
                fields=["embarazo", "-fecha_toma"],
                name="laboratorio_embaraz_d6ff56_idx",
            ),
        ),
    ]
