# Generated by Django 5.1.3 on 2025-12-27 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calculadoras", "0003_remove_calculoclinico_control_prenatal_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="biomarcadormom",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="biomarcadores_mom_creados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="biomarcadormom",
            name="fecha_modificacion",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de Modificación",
            ),
        ),
        migrations.AddField(
            model_name="biomarcadormom",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="biomarcadores_mom_modificados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modificado por",
            ),
        ),
        migrations.AddField(
            model_name="calculadorariesgo",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="calculadoras_riesgo_creadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="calculadorariesgo",
            name="fecha_modificacion",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de Modificación",
            ),
        ),
        migrations.AddField(
            model_name="calculadorariesgo",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="calculadoras_riesgo_modificadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modificado por",
            ),
        ),
        migrations.AddField(
            model_name="medicionecografica",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mediciones_ecograficas_creadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="medicionecografica",
            name="fecha_modificacion",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de Modificación",
            ),
        ),
        migrations.AddField(
            model_name="medicionecografica",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mediciones_ecograficas_modificadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modificado por",
            ),
        ),
    ]
