# Generated by Django 6.0.4 on 2026-04-09 23:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calculadoras", "0004_biomarcadormom_created_by_and_more"),
        ("embarazos", "0005_embarazo_created_by_embarazo_fecha_modificacion_and_more"),
        ("pacientes", "0006_paciente_created_by_paciente_updated_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DopplerMaterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_examen", models.DateField(default=django.utils.timezone.now)),
                (
                    "edad_gestacional_semanas",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(7),
                            django.core.validators.MaxValueValidator(42),
                        ],
                    ),
                ),
                (
                    "edad_gestacional_dias",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "lado",
                    models.CharField(
                        choices=[
                            ("izquierda", "Arteria Uterina Izquierda"),
                            ("derecha", "Arteria Uterina Derecha"),
                            ("promedio", "Promedio Bilateral"),
                        ],
                        default="promedio",
                        max_length=20,
                    ),
                ),
                (
                    "ps_cm_s",
                    models.FloatField(
                        blank=True,
                        help_text="Velocidad sistólica pico (cm/s)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "ed_cm_s",
                    models.FloatField(
                        blank=True,
                        help_text="Velocidad diastólica final (cm/s)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "ri",
                    models.FloatField(
                        blank=True,
                        help_text="Índice de resistencia",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "ip",
                    models.FloatField(
                        blank=True,
                        help_text="Índice de pulsatilidad",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "s_d_ratio",
                    models.FloatField(
                        blank=True,
                        help_text="Relación S/D",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "escotadura_diastolica",
                    models.BooleanField(
                        default=False, help_text="Presencia de escotadura diastólica",
                    ),
                ),
                (
                    "clasificacion",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("resistencia_aumentada", "Resistencia Aumentada"),
                            ("escotadura_bilateral", "Escotadura Bilateral"),
                            ("alto_riesgo", "Alto Riesgo"),
                        ],
                        default="normal",
                        max_length=30,
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("notas", models.TextField(blank=True)),
                (
                    "embarazo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dopplers_maternos",
                        to="embarazos.embarazo",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dopplers_maternos",
                        to="pacientes.paciente",
                    ),
                ),
                (
                    "realizado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Doppler Materno",
                "verbose_name_plural": "Dopplers Maternos",
                "db_table": "doppler_materno",
                "ordering": ["-fecha_examen"],
            },
        ),
    ]
