# Generated by Django 6.0.5 on 2026-05-23 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculadoras", "0006_5nf_alerta_laboratorio"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="alertalaboratorio",
            name="alerta_lab_ct_obj_fecha_idx",
        ),
        migrations.RemoveIndex(
            model_name="alertalaboratorio",
            name="alerta_lab_sev_proc_idx",
        ),
        migrations.AlterField(
            model_name="alertalaboratorio",
            name="codigo",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=50,
                verbose_name="Código de alerta",
            ),
        ),
        migrations.AlterField(
            model_name="alertalaboratorio",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Tipo de modelo",
            ),
        ),
        migrations.AlterField(
            model_name="alertalaboratorio",
            name="fecha",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Fecha de generación"
            ),
        ),
        migrations.AlterField(
            model_name="alertalaboratorio",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="alertalaboratorio",
            name="mensaje",
            field=models.TextField(verbose_name="Mensaje de alerta"),
        ),
        migrations.AlterField(
            model_name="alertalaboratorio",
            name="procesada",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Procesada"
            ),
        ),
        migrations.AlterField(
            model_name="biomarcadormom",
            name="marcador",
            field=models.CharField(
                choices=[
                    ("pappa", "PAPP-A"),
                    ("bhcg", "β-hCG libre"),
                    ("plg", "PLGF (Factor Crecimiento Placentario)"),
                    ("sflt1", "sFlt-1 (Factor Antiangiogénico)"),
                    ("pam", "PAM (Presión Arterial Media)"),
                    ("utpi", "UtA-PI (Índice Pulsatilidad Arteria Uterina)"),
                    ("afp", "AFP (Alfafetoproteína)"),
                    ("bhcg_total", "β-hCG Total"),
                    ("estriol", "Estriol Libre"),
                    ("inhibina_a", "Inhibina A"),
                ],
                max_length=20,
                verbose_name="Marcador",
            ),
        ),
        migrations.AlterField(
            model_name="calculadorariesgo",
            name="metodo_concepcion",
            field=models.CharField(
                choices=[("espontaneo", "Espontáneo"), ("iv", "FIV"), ("otro", "Otro")],
                default="espontaneo",
                max_length=20,
                verbose_name="Método de Concepción",
            ),
        ),
    ]
