# Generated by Django 6.0.5 on 2026-06-20 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculadoras",
            "0007_remove_alertalaboratorio_alerta_lab_ct_obj_fecha_idx_and_more",
        ),
        ("embarazos", "0005_embarazo_created_by_embarazo_fecha_modificacion_and_more"),
        ("pacientes", "0009_alter_paciente_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalculoHistorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_calculadora",
                    models.CharField(
                        choices=[
                            ("edad_gestacional", "Edad Gestacional"),
                            ("bishop", "Score de Bishop"),
                            ("imc", "IMC"),
                            ("riesgo_preeclampsia", "Riesgo de Preeclampsia"),
                            ("diabetes_gestacional", "Diabetes Gestacional"),
                            ("ila", "Indice de Liquido Amniotico"),
                            ("peso_fetal", "Peso Fetal"),
                            ("apgar", "Score de Apgar"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Tipo de Calculadora",
                    ),
                ),
                (
                    "inputs_json",
                    models.JSONField(
                        default=dict,
                        help_text="Valores ingresados en el formulario de la calculadora",
                        verbose_name="Datos de entrada",
                    ),
                ),
                (
                    "resultado_json",
                    models.JSONField(default=dict, verbose_name="Resultado calculado"),
                ),
                (
                    "resultado_resumen",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Texto corto para mostrar en listados sin abrir el detalle",
                        max_length=255,
                        verbose_name="Resumen del resultado",
                    ),
                ),
                (
                    "fecha_calculo",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de cálculo",
                    ),
                ),
                (
                    "calculado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calculos_historial_realizados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Calculado por",
                    ),
                ),
                (
                    "embarazo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calculos_historial",
                        to="embarazos.embarazo",
                        verbose_name="Embarazo",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calculos_historial",
                        to="pacientes.paciente",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Cálculo",
                "verbose_name_plural": "Historial de Cálculos",
                "db_table": "calculadoras_historial",
                "ordering": ["-fecha_calculo"],
                "indexes": [
                    models.Index(
                        fields=["tipo_calculadora", "-fecha_calculo"],
                        name="calculadora_tipo_ca_6c1bac_idx",
                    ),
                    models.Index(
                        fields=["paciente", "-fecha_calculo"],
                        name="calculadora_pacient_f941cf_idx",
                    ),
                ],
            },
        ),
    ]
