# Generated by Django 6.0.5 on 2026-06-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculadoras", "0008_calculohistorial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculohistorial",
            name="tipo_calculadora",
            field=models.CharField(
                choices=[
                    ("edad_gestacional", "Edad Gestacional"),
                    ("bishop", "Score de Bishop"),
                    ("imc", "IMC"),
                    ("riesgo_preeclampsia", "Riesgo de Preeclampsia"),
                    ("diabetes_gestacional", "Diabetes Gestacional"),
                    ("ila", "Indice de Liquido Amniotico"),
                    ("peso_fetal", "Peso Fetal"),
                    ("apgar", "Score de Apgar"),
                    ("capurro", "Método de Capurro"),
                    ("silverman", "Test de Silverman-Andersen"),
                    ("ballard", "Ballard Score"),
                    ("icc", "Indice Cardio-Cerebral"),
                    ("pa_media", "Presión Arterial Media"),
                    ("fc_maxima", "Frecuencia Cardíaca Máxima"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="Tipo de Calculadora",
            ),
        ),
    ]
