# Generated by Django 5.1.3 on 2025-11-04 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calculadoras_avanzadas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DosisMedicamentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paciente_id", models.IntegerField(verbose_name="ID del Paciente")),
                (
                    "embarazo_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID del Embarazo",
                    ),
                ),
                (
                    "parto_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID del Parto",
                    ),
                ),
                (
                    "fecha_calculo",
                    models.DateTimeField(verbose_name="Fecha del Cálculo"),
                ),
                (
                    "medicamento",
                    models.CharField(
                        choices=[
                            ("oxitocina", "Oxitocina"),
                            ("sulfato_magnesio", "Sulfato de Magnesio"),
                            ("betametasona", "Betametasona"),
                            ("dexametasona", "Dexametasona"),
                            ("nifedipino", "Nifedipino"),
                            ("indometacina", "Indometacina"),
                            ("metildopa", "Metildopa"),
                            ("labetalol", "Labetalol"),
                        ],
                        max_length=30,
                        verbose_name="Medicamento",
                    ),
                ),
                (
                    "indicacion",
                    models.CharField(
                        choices=[
                            ("induccion_parto", "Inducción del Parto"),
                            ("conduccion_parto", "Conducción del Parto"),
                            ("hemorragia_postparto", "Hemorragia Postparto"),
                            ("preeclampsia_severa", "Preeclampsia Severa"),
                            ("eclampsia", "Eclampsia"),
                            ("maduracin_pulmonar", "Maduración Pulmonar"),
                            ("tocolis_aguda", "Tocolisis Aguda"),
                            ("hipertension_gestacional", "Hipertensión Gestacional"),
                        ],
                        max_length=30,
                        verbose_name="Indicación",
                    ),
                ),
                (
                    "peso_materno",
                    models.DecimalField(
                        decimal_places=1, max_digits=5, verbose_name="Peso Materno (kg)",
                    ),
                ),
                (
                    "edad_gestacional_semanas",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(42),
                        ],
                        verbose_name="Edad Gestacional (semanas)",
                    ),
                ),
                (
                    "presion_arterial_sistolica",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="PAS (mmHg)",
                    ),
                ),
                (
                    "presion_arterial_diastolica",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="PAD (mmHg)",
                    ),
                ),
                (
                    "creatinina_serica",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="Creatinina (mg/dL)",
                    ),
                ),
                (
                    "dosis_inicial",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Dosis Inicial",
                    ),
                ),
                (
                    "dosis_mantenimiento",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Dosis de Mantenimiento",
                    ),
                ),
                (
                    "dosis_maxima",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Dosis Máxima",
                    ),
                ),
                (
                    "via_administracion",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Vía de Administración",
                    ),
                ),
                (
                    "intervalo_dosis",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Intervalo entre Dosis",
                    ),
                ),
                (
                    "duracion_tratamiento",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Duración del Tratamiento",
                    ),
                ),
                (
                    "precauciones",
                    models.TextField(
                        blank=True, verbose_name="Precauciones Especiales",
                    ),
                ),
                (
                    "contraindicaciones",
                    models.TextField(blank=True, verbose_name="Contraindicaciones"),
                ),
                (
                    "monitoreo_requerido",
                    models.TextField(blank=True, verbose_name="Monitoreo Requerido"),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dosis de Medicamento",
                "verbose_name_plural": "Dosis de Medicamentos",
                "db_table": "dosis_medicamentos",
                "ordering": ["-fecha_calculo"],
            },
        ),
        migrations.CreateModel(
            name="HemorragiaObstetrica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paciente_id", models.IntegerField(verbose_name="ID del Paciente")),
                (
                    "embarazo_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID del Embarazo",
                    ),
                ),
                (
                    "parto_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID del Parto",
                    ),
                ),
                (
                    "fecha_evento",
                    models.DateTimeField(verbose_name="Fecha y Hora del Evento"),
                ),
                (
                    "tipo_hemorragia",
                    models.CharField(
                        choices=[
                            ("anteparto", "Hemorragia Anteparto"),
                            ("intraparto", "Hemorragia Intraparto"),
                            ("postparto_inmediato", "Hemorragia Postparto Inmediato"),
                            ("postparto_tardio", "Hemorragia Postparto Tardío"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Hemorragia",
                    ),
                ),
                (
                    "causa_principal",
                    models.CharField(
                        choices=[
                            ("atonia_uterina", "Atonía Uterina"),
                            ("retencion_placentaria", "Retención Placentaria"),
                            ("desgarros_tractus", "Desgarros del Tractus Genital"),
                            ("rotura_uterina", "Rotura Uterina"),
                            ("placenta_previa", "Placenta Previa"),
                            ("desprendimiento_placenta", "Desprendimiento de Placenta"),
                            ("coagulopatia", "Coagulopatía"),
                            ("inversion_uterina", "Inversión Uterina"),
                        ],
                        max_length=30,
                        verbose_name="Causa Principal",
                    ),
                ),
                (
                    "perdida_sanguinea_estimada",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5000),
                        ],
                        verbose_name="Pérdida Sanguínea Estimada (mL)",
                    ),
                ),
                (
                    "presion_arterial_sistolica",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(200),
                        ],
                        verbose_name="PAS (mmHg)",
                    ),
                ),
                (
                    "presion_arterial_diastolica",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(120),
                        ],
                        verbose_name="PAD (mmHg)",
                    ),
                ),
                (
                    "frecuencia_cardiaca",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(40),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="FC (lpm)",
                    ),
                ),
                (
                    "hemoglobina_inicial",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Hemoglobina Inicial (g/dL)",
                    ),
                ),
                (
                    "hematocrito_inicial",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Hematocrito Inicial (%)",
                    ),
                ),
                (
                    "plaquetas",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Plaquetas (/mm³)",
                    ),
                ),
                (
                    "severidad_hemorragia",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Severidad de la Hemorragia",
                    ),
                ),
                (
                    "indice_shock",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="Índice de Shock",
                    ),
                ),
                (
                    "deficit_volumen_estimado",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Déficit de Volumen Estimado (mL)",
                    ),
                ),
                (
                    "paso_protocolo_actual",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Paso Actual del Protocolo",
                    ),
                ),
                (
                    "medidas_implementadas",
                    models.TextField(blank=True, verbose_name="Medidas Implementadas"),
                ),
                (
                    "requiere_transfusion",
                    models.BooleanField(
                        default=False, verbose_name="¿Requiere Transfusión?",
                    ),
                ),
                (
                    "unidades_globulos_rojos",
                    models.IntegerField(
                        default=0, verbose_name="Unidades de Glóbulos Rojos",
                    ),
                ),
                (
                    "unidades_plasma_fresco",
                    models.IntegerField(
                        default=0, verbose_name="Unidades de Plasma Fresco",
                    ),
                ),
                (
                    "unidades_plaquetas",
                    models.IntegerField(
                        default=0, verbose_name="Unidades de Plaquetas",
                    ),
                ),
                (
                    "hemorragia_controlada",
                    models.BooleanField(
                        default=False, verbose_name="¿Hemorragia Controlada?",
                    ),
                ),
                (
                    "requirio_cirugia",
                    models.BooleanField(
                        default=False, verbose_name="¿Requirió Cirugía?",
                    ),
                ),
                (
                    "tipo_cirugia",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tipo de Cirugía",
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hemorragia Obstétrica",
                "verbose_name_plural": "Hemorragias Obstétricas",
                "db_table": "hemorragia_obstetrica",
                "ordering": ["-fecha_evento"],
            },
        ),
        migrations.CreateModel(
            name="RiesgoCromosomico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paciente_id", models.IntegerField(verbose_name="ID del Paciente")),
                (
                    "embarazo_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID del Embarazo",
                    ),
                ),
                (
                    "ecografia_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID de Ecografía",
                    ),
                ),
                (
                    "fecha_evaluacion",
                    models.DateTimeField(verbose_name="Fecha de Evaluación"),
                ),
                (
                    "edad_gestacional_semanas",
                    models.IntegerField(
                        help_text="Screening del primer trimestre: 11-14 semanas",
                        validators=[
                            django.core.validators.MinValueValidator(11),
                            django.core.validators.MaxValueValidator(14),
                        ],
                        verbose_name="Edad Gestacional (semanas)",
                    ),
                ),
                (
                    "edad_gestacional_dias",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                        verbose_name="Días adicionales",
                    ),
                ),
                (
                    "edad_materna",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(15),
                            django.core.validators.MaxValueValidator(50),
                        ],
                        verbose_name="Edad Materna (años)",
                    ),
                ),
                (
                    "peso_materno",
                    models.DecimalField(
                        decimal_places=1, max_digits=5, verbose_name="Peso Materno (kg)",
                    ),
                ),
                (
                    "translucencia_nucal",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Medida en mm",
                        max_digits=4,
                        verbose_name="Translucencia Nucal (mm)",
                    ),
                ),
                (
                    "hueso_nasal_presente",
                    models.BooleanField(
                        default=True, verbose_name="¿Hueso nasal presente?",
                    ),
                ),
                (
                    "crl_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Longitud cráneo-rabadilla",
                        max_digits=4,
                        null=True,
                        verbose_name="CRL (mm)",
                    ),
                ),
                (
                    "papp_a",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Proteína plasmática A asociada al embarazo",
                        max_digits=6,
                        null=True,
                        verbose_name="PAPP-A (mUI/L)",
                    ),
                ),
                (
                    "beta_hcg_libre",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fracción libre de gonadotropina coriónica",
                        max_digits=6,
                        null=True,
                        verbose_name="β-HCG libre (ng/mL)",
                    ),
                ),
                (
                    "papp_a_mom",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="PAPP-A MoM",
                    ),
                ),
                (
                    "beta_hcg_mom",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="β-HCG MoM",
                    ),
                ),
                (
                    "tn_mom",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="TN MoM",
                    ),
                ),
                (
                    "riesgo_down_basal",
                    models.CharField(
                        blank=True,
                        help_text="1:X",
                        max_length=20,
                        verbose_name="Riesgo Basal Down",
                    ),
                ),
                (
                    "riesgo_down_ajustado",
                    models.CharField(
                        blank=True,
                        help_text="1:X",
                        max_length=20,
                        verbose_name="Riesgo Ajustado Down",
                    ),
                ),
                (
                    "riesgo_edwards",
                    models.CharField(
                        blank=True,
                        help_text="1:X",
                        max_length=20,
                        verbose_name="Riesgo Edwards (T18)",
                    ),
                ),
                (
                    "riesgo_patau",
                    models.CharField(
                        blank=True,
                        help_text="1:X",
                        max_length=20,
                        verbose_name="Riesgo Patau (T13)",
                    ),
                ),
                (
                    "clasificacion_down",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bajo", "Bajo Riesgo"),
                            ("intermedio", "Riesgo Intermedio"),
                            ("alto", "Alto Riesgo"),
                        ],
                        max_length=20,
                        verbose_name="Clasificación Down",
                    ),
                ),
                (
                    "recomendacion",
                    models.TextField(blank=True, verbose_name="Recomendación Clínica"),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Riesgo Cromosómico",
                "verbose_name_plural": "Riesgos Cromosómicos",
                "db_table": "riesgo_cromosomico",
                "ordering": ["-fecha_evaluacion"],
            },
        ),
        migrations.CreateModel(
            name="SufrimientoFetal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paciente_id", models.IntegerField(verbose_name="ID del Paciente")),
                (
                    "embarazo_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID del Embarazo",
                    ),
                ),
                (
                    "parto_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID del Parto",
                    ),
                ),
                (
                    "fecha_evaluacion",
                    models.DateTimeField(verbose_name="Fecha y Hora de Evaluación"),
                ),
                (
                    "edad_gestacional_semanas",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(42),
                        ],
                        verbose_name="Edad Gestacional (semanas)",
                    ),
                ),
                (
                    "tipo_evaluacion",
                    models.CharField(
                        choices=[
                            ("anteparto", "Evaluación Anteparto"),
                            ("intraparto", "Evaluación Intraparto"),
                            ("postparto", "Evaluación Postparto"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Evaluación",
                    ),
                ),
                (
                    "tipo_monitoreo",
                    models.CharField(
                        choices=[
                            ("ctg_externo", "CTG Externo"),
                            ("ctg_interno", "CTG Interno"),
                            ("perfil_biofsico", "Perfil Biofísico"),
                            ("doppler_fetal", "Doppler Fetal"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Monitoreo",
                    ),
                ),
                (
                    "fcf_basal",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(80),
                            django.core.validators.MaxValueValidator(200),
                        ],
                        verbose_name="FCF Basal (lpm)",
                    ),
                ),
                (
                    "variabilidad_fcf",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ausente", "Ausente (< 5 lpm)"),
                            ("minima", "Mínima (5-10 lpm)"),
                            ("moderada", "Moderada (11-25 lpm)"),
                            ("marcada", "Marcada (> 25 lpm)"),
                        ],
                        max_length=20,
                        verbose_name="Variabilidad FCF",
                    ),
                ),
                (
                    "aceleraciones_presentes",
                    models.BooleanField(
                        default=True, verbose_name="¿Aceleraciones presentes?",
                    ),
                ),
                (
                    "desaceleraciones_tardias",
                    models.BooleanField(
                        default=False, verbose_name="Desaceleraciones Tardías",
                    ),
                ),
                (
                    "desaceleraciones_variables",
                    models.BooleanField(
                        default=False, verbose_name="Desaceleraciones Variables",
                    ),
                ),
                (
                    "desaceleraciones_prolongadas",
                    models.BooleanField(
                        default=False, verbose_name="Desaceleraciones Prolongadas",
                    ),
                ),
                (
                    "movimientos_fetales",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("presentes", "Presentes"),
                            ("disminuidos", "Disminuidos"),
                            ("ausentes", "Ausentes"),
                        ],
                        max_length=20,
                        verbose_name="Movimientos Fetales",
                    ),
                ),
                (
                    "tono_fetal",
                    models.CharField(
                        blank=True,
                        choices=[("normal", "Normal"), ("disminuido", "Disminuido")],
                        max_length=20,
                        verbose_name="Tono Fetal",
                    ),
                ),
                (
                    "liquido_amniotico",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("normal", "Normal"),
                            ("oligohidramnios", "Oligohidramnios"),
                            ("polihidramnios", "Polihidramnios"),
                        ],
                        max_length=20,
                        verbose_name="Líquido Amniótico",
                    ),
                ),
                (
                    "indice_pulsatilidad_umbilical",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="IP Arteria Umbilical",
                    ),
                ),
                (
                    "indice_pulsatilidad_cerebral",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="IP Arteria Cerebral Media",
                    ),
                ),
                (
                    "score_fisher",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Score de Fisher",
                    ),
                ),
                (
                    "perfil_biofsico_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Score Perfil Biofísico",
                    ),
                ),
                (
                    "clasificacion_ctg",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("categoria_1", "Categoría I (Normal)"),
                            ("categoria_2", "Categoría II (Indeterminado)"),
                            ("categoria_3", "Categoría III (Anormal)"),
                        ],
                        max_length=20,
                        verbose_name="Clasificación CTG",
                    ),
                ),
                (
                    "riesgo_sufrimiento_fetal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bajo", "Bajo Riesgo"),
                            ("intermedio", "Riesgo Intermedio"),
                            ("alto", "Alto Riesgo"),
                        ],
                        max_length=20,
                        verbose_name="Riesgo de Sufrimiento Fetal",
                    ),
                ),
                (
                    "conducta_recomendada",
                    models.TextField(blank=True, verbose_name="Conducta Recomendada"),
                ),
                (
                    "requiere_intervencion_inmediata",
                    models.BooleanField(
                        default=False, verbose_name="¿Requiere Intervención Inmediata?",
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Evaluación de Sufrimiento Fetal",
                "verbose_name_plural": "Evaluaciones de Sufrimiento Fetal",
                "db_table": "sufrimiento_fetal",
                "ordering": ["-fecha_evaluacion"],
            },
        ),
    ]
