# Generated by Django 6.0.5 on 2026-05-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculadoras_avanzadas",
            "0003_remove_crecimientofetal_ecografia_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="crecimientofetal",
            name="macrosomia",
            field=models.BooleanField(default=False, verbose_name="¿Macrosomía"),
        ),
        migrations.AlterField(
            model_name="crecimientofetal",
            name="restriccion_crecimiento",
            field=models.BooleanField(
                default=False, verbose_name="¿Restricción de Crecimiento"
            ),
        ),
        migrations.AlterField(
            model_name="hemorragiaobstetrica",
            name="hemorragia_controlada",
            field=models.BooleanField(
                default=False, verbose_name="¿Hemorragia Controlada"
            ),
        ),
        migrations.AlterField(
            model_name="hemorragiaobstetrica",
            name="requiere_transfusion",
            field=models.BooleanField(
                default=False, verbose_name="¿Requiere Transfusión"
            ),
        ),
        migrations.AlterField(
            model_name="hemorragiaobstetrica",
            name="requirio_cirugia",
            field=models.BooleanField(default=False, verbose_name="¿Requirió Cirugía"),
        ),
        migrations.AlterField(
            model_name="riesgocromosomico",
            name="hueso_nasal_presente",
            field=models.BooleanField(
                default=True, verbose_name="¿Hueso nasal presente"
            ),
        ),
        migrations.AlterField(
            model_name="sufrimientofetal",
            name="aceleraciones_presentes",
            field=models.BooleanField(
                default=True, verbose_name="¿Aceleraciones presentes"
            ),
        ),
        migrations.AlterField(
            model_name="sufrimientofetal",
            name="requiere_intervencion_inmediata",
            field=models.BooleanField(
                default=False, verbose_name="¿Requiere Intervención Inmediata"
            ),
        ),
    ]
