# Generated by Django 6.0.5 on 2026-06-21 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketSoporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asunto", models.CharField(max_length=200, verbose_name="Asunto")),
                (
                    "modulo",
                    models.CharField(
                        choices=[
                            ("login", "Acceso / Login"),
                            ("pacientes", "Pacientes"),
                            ("controles", "Controles Prenatales"),
                            ("reportes", "Reportes"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Módulo afectado",
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja (Consulta)"),
                            ("media", "Media (Funcionalidad parcial)"),
                            ("alta", "Alta (Sistema detenido)"),
                        ],
                        default="media",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción detallada")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierto", "Abierto"),
                            ("en_proceso", "En Proceso"),
                            ("resuelto", "Resuelto"),
                            ("cerrado", "Cerrado"),
                        ],
                        default="abierto",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "respuesta_admin",
                    models.TextField(
                        blank=True, verbose_name="Respuesta del equipo de TI"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_resolucion", models.DateTimeField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets_soporte",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario solicitante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket de Soporte",
                "verbose_name_plural": "Tickets de Soporte",
                "db_table": "tickets_soporte",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
