# Generated by Django 5.1.3 on 2025-11-24 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("embarazos", "0002_alter_embarazo_medico_responsable"),
        ("pacientes", "0002_paciente_estado_paciente_paciente_fecha_baja_and_more"),
        ("reportes", "0002_alter_dashboardkpi_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Eliminar índices que referencian campos a ser eliminados (requerido por SQLite)
        migrations.RemoveIndex(
            model_name="alertamedica",
            name="alertas_med_pacient_4c08eb_idx",
        ),
        migrations.RemoveIndex(
            model_name="alertamedica",
            name="alertas_med_estado_7131b1_idx",
        ),
        migrations.RemoveIndex(
            model_name="alertamedica",
            name="alertas_med_fecha_c_1da145_idx",
        ),
        migrations.RemoveField(
            model_name="alertamedica",
            name="embarazo_id",
        ),
        migrations.RemoveField(
            model_name="alertamedica",
            name="medico_responsable_id",
        ),
        migrations.RemoveField(
            model_name="alertamedica",
            name="paciente_id",
        ),
        migrations.RemoveField(
            model_name="alertamedica",
            name="usuario_resolucion_id",
        ),
        migrations.RemoveField(
            model_name="alertamedica",
            name="usuario_revision_id",
        ),
        migrations.RemoveField(
            model_name="auditoriareporte",
            name="usuario_id",
        ),
        migrations.AddField(
            model_name="alertamedica",
            name="embarazo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="embarazos.embarazo",
                verbose_name="🤰 Embarazo",
            ),
        ),
        migrations.AddField(
            model_name="alertamedica",
            name="medico_responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alertas_responsable",
                to=settings.AUTH_USER_MODEL,
                verbose_name="👨\u200d⚕️ Médico Responsable",
            ),
        ),
        migrations.AddField(
            model_name="alertamedica",
            name="paciente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pacientes.paciente",
                verbose_name="👤 Paciente",
            ),
        ),
        migrations.AddField(
            model_name="alertamedica",
            name="usuario_resolucion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alertas_resueltas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="👤 Usuario que resolvió",
            ),
        ),
        migrations.AddField(
            model_name="alertamedica",
            name="usuario_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alertas_revisadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="👤 Usuario que revisó",
            ),
        ),
        migrations.AddField(
            model_name="auditoriareporte",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="👤 Usuario",
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="filtro_medico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reportes_filtrados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="👨\u200d⚕️ Médico específico",
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="filtro_paciente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pacientes.paciente",
                verbose_name="👤 Paciente específico",
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="usuario_solicitante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reportes_solicitados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="👤 Usuario que solicitó el reporte",
            ),
        ),
    ]
