# Generated by Django 5.1.3 on 2025-12-04 05:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reportes", "0003_remove_alertamedica_embarazo_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HorarioAtencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia",
                    models.CharField(
                        choices=[
                            ("lunes", "Lunes"),
                            ("martes", "Martes"),
                            ("miercoles", "Miércoles"),
                            ("jueves", "Jueves"),
                            ("viernes", "Viernes"),
                            ("sabado", "Sábado"),
                            ("domingo", "Domingo"),
                        ],
                        max_length=10,
                        unique=True,
                        verbose_name="Día de la Semana",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Si está desactivado, no se podrán agendar citas en este día",
                        verbose_name="Día Activo",
                    ),
                ),
                (
                    "hora_inicio",
                    models.TimeField(
                        help_text="Formato 24 horas (ej: 08:00)",
                        verbose_name="Hora de Inicio",
                    ),
                ),
                (
                    "hora_fin",
                    models.TimeField(
                        help_text="Formato 24 horas (ej: 18:00)",
                        verbose_name="Hora de Cierre",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Horario de Atención",
                "verbose_name_plural": "Horarios de Atención",
                "db_table": "horarios_atencion",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SistemaConfiguracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_clinica",
                    models.CharField(
                        default="Centro Médico",
                        max_length=200,
                        verbose_name="Nombre de la Clínica/Consultorio",
                    ),
                ),
                (
                    "direccion",
                    models.TextField(blank=True, verbose_name="Dirección Física"),
                ),
                (
                    "telefono_contacto",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Teléfono Principal",
                    ),
                ),
                (
                    "email_contacto",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email de Contacto",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo que aparecerá en reportes y documentos oficiales",
                        null=True,
                        upload_to="logos/",
                        verbose_name="Logo Institucional",
                    ),
                ),
                (
                    "modo_mantenimiento",
                    models.BooleanField(
                        default=False,
                        help_text="Solo administradores podrán acceder al sistema",
                        verbose_name="Modo Mantenimiento",
                    ),
                ),
                (
                    "permitir_registro_publico",
                    models.BooleanField(
                        default=False, verbose_name="Permitir Registro Público",
                    ),
                ),
                (
                    "dias_retencion_logs",
                    models.IntegerField(
                        default=90,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(730),
                        ],
                        verbose_name="Días de Retención de Logs",
                    ),
                ),
                (
                    "smtp_host",
                    models.CharField(
                        default="smtp.gmail.com",
                        max_length=100,
                        verbose_name="Servidor SMTP",
                    ),
                ),
                (
                    "smtp_port",
                    models.IntegerField(default=587, verbose_name="Puerto SMTP"),
                ),
                (
                    "smtp_user",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Usuario SMTP",
                    ),
                ),
                (
                    "smtp_password",
                    models.CharField(
                        blank=True,
                        help_text="Se almacena encriptada",
                        max_length=200,
                        verbose_name="Contraseña SMTP",
                    ),
                ),
                (
                    "smtp_secure",
                    models.BooleanField(default=True, verbose_name="Usar TLS/SSL"),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Última Actualización Por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración del Sistema",
                "verbose_name_plural": "Configuración del Sistema",
                "db_table": "sistema_configuracion",
            },
        ),
    ]
