# Generated by Django 6.0.4 on 2026-05-03 03:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("embarazos", "0005_embarazo_created_by_embarazo_fecha_modificacion_and_more"),
        (
            "pacientes",
            "0008_remove_paciente_unique_paciente_ci_paciente_ci_hash_and_more",
        ),
        ("reportes", "0005_alertamedica_created_by_alertamedica_updated_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="alertamedica",
            index=models.Index(
                fields=["estado", "prioridad"], name="alertas_med_estado_7131b1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertamedica",
            index=models.Index(
                fields=["paciente_id", "estado"], name="alertas_med_pacient_4c08eb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertamedica",
            index=models.Index(
                fields=["fecha_creacion"], name="alertas_med_fecha_c_1da145_idx",
            ),
        ),
    ]
