# Generated by Django 6.0.5 on 2026-05-23 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("embarazos", "0005_embarazo_created_by_embarazo_fecha_modificacion_and_more"),
        (
            "pacientes",
            "0008_remove_paciente_unique_paciente_ci_paciente_ci_hash_and_more",
        ),
        ("reportes", "0006_alertamedica_alertas_med_estado_7131b1_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportegenerado",
            name="tamaño_archivo",
        ),
        migrations.AddField(
            model_name="reportegenerado",
            name="tamano_archivo",
            field=models.IntegerField(
                blank=True, null=True, verbose_name=" Tamaño del archivo (bytes)"
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="accion_recomendada",
            field=models.TextField(verbose_name=" Acción recomendada"),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="comentario_resolucion",
            field=models.TextField(
                blank=True, verbose_name=" Comentario de resolución"
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="comentario_revision",
            field=models.TextField(blank=True, verbose_name=" Comentario de revisión"),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="descripcion",
            field=models.TextField(verbose_name=" Descripción detallada"),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="embarazo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="embarazos.embarazo",
                verbose_name=" Embarazo",
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="escalamiento_automatico",
            field=models.BooleanField(
                default=False, verbose_name=" ¿Escalamiento automático"
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="estado",
            field=models.CharField(
                choices=[
                    ("activa", " Activa"),
                    ("revisada", " Revisada"),
                    ("resuelta", " Resuelta"),
                    ("descartada", "⚫ Descartada"),
                    ("escalada", " Escalada"),
                ],
                default="activa",
                max_length=15,
                verbose_name=" Estado actual",
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name=" Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="fecha_revision",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name=" Fecha de revisión"
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="medico_responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alertas_responsable",
                to=settings.AUTH_USER_MODEL,
                verbose_name="\u200d⚕️ Médico Responsable",
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="modulo_origen",
            field=models.CharField(
                choices=[
                    ("pacientes", " Módulo de Pacientes"),
                    ("embarazos", " Módulo de Embarazos"),
                    ("controles", " Controles Prenatales"),
                    ("ecografias", " Ecografías"),
                    ("laboratorio", " Laboratorio"),
                    ("calculadoras", " Calculadoras Médicas"),
                    ("partos", " Partos"),
                    ("sistema", "⚙️ Sistema"),
                ],
                max_length=50,
                verbose_name=" Módulo de origen",
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="notificacion_enviada",
            field=models.BooleanField(
                default=False, verbose_name=" ¿Notificación enviada"
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="paciente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pacientes.paciente",
                verbose_name=" Paciente",
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="prioridad",
            field=models.CharField(
                choices=[
                    ("baja", " Baja"),
                    ("media", " Media"),
                    ("alta", " Alta"),
                    ("critica", " Crítica"),
                    ("emergencia", " EMERGENCIA"),
                ],
                max_length=15,
                verbose_name="⚡ Prioridad",
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="protocolo_seguimiento",
            field=models.TextField(
                blank=True, verbose_name=" Protocolo de seguimiento"
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="recordatorio_enviado",
            field=models.BooleanField(
                default=False, verbose_name=" ¿Recordatorio enviado"
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="registro_origen_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name=" ID del registro relacionado"
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("valor_critico", " Valor crítico detectado"),
                    ("seguimiento_vencido", "⏰ Seguimiento vencido"),
                    ("medicamento_contraindicado", " Medicamento contraindicado"),
                    ("riesgo_alto", "⚠️ Riesgo alto detectado"),
                    ("resultado_anormal", " Resultado anormal"),
                    ("cita_perdida", " Cita perdida"),
                    ("protocolo_incumplido", " Protocolo no seguido"),
                    ("auditoria", " Requiere auditoría"),
                ],
                max_length=30,
                verbose_name="️ Tipo de alerta",
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="titulo",
            field=models.CharField(max_length=200, verbose_name=" Título de la alerta"),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="usuario_resolucion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alertas_resueltas",
                to=settings.AUTH_USER_MODEL,
                verbose_name=" Usuario que resolvió",
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="usuario_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alertas_revisadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name=" Usuario que revisó",
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="valor_actual",
            field=models.CharField(
                blank=True, max_length=100, verbose_name=" Valor actual"
            ),
        ),
        migrations.AlterField(
            model_name="auditoriareporte",
            name="accion",
            field=models.CharField(
                choices=[
                    ("generacion", " Generación de reporte"),
                    ("descarga", " Descarga"),
                    ("visualizacion", " Visualización"),
                    ("modificacion", "✏️ Modificación"),
                    ("eliminacion", "️ Eliminación"),
                    ("compartir", " Compartir"),
                ],
                max_length=20,
                verbose_name="⚡ Acción realizada",
            ),
        ),
        migrations.AlterField(
            model_name="auditoriareporte",
            name="cumple_ley_3871",
            field=models.BooleanField(
                default=True, verbose_name="⚖️ ¿Cumple con la Ley 3871"
            ),
        ),
        migrations.AlterField(
            model_name="auditoriareporte",
            name="direccion_ip",
            field=models.GenericIPAddressField(verbose_name=" Dirección IP"),
        ),
        migrations.AlterField(
            model_name="auditoriareporte",
            name="fecha_accion",
            field=models.DateTimeField(auto_now_add=True, verbose_name=" Fecha y hora"),
        ),
        migrations.AlterField(
            model_name="auditoriareporte",
            name="justificacion_acceso",
            field=models.TextField(
                blank=True, verbose_name=" Justificación del acceso"
            ),
        ),
        migrations.AlterField(
            model_name="auditoriareporte",
            name="observaciones",
            field=models.TextField(blank=True, verbose_name=" Observaciones"),
        ),
        migrations.AlterField(
            model_name="auditoriareporte",
            name="reporte_generado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reportes.reportegenerado",
                verbose_name=" Reporte",
            ),
        ),
        migrations.AlterField(
            model_name="auditoriareporte",
            name="user_agent",
            field=models.TextField(verbose_name=" Navegador/Dispositivo"),
        ),
        migrations.AlterField(
            model_name="auditoriareporte",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name=" Usuario",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="activo",
            field=models.BooleanField(default=True, verbose_name="✅ ¿Está activo"),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("pacientes", " Pacientes"),
                    ("embarazos", " Embarazos"),
                    ("controles", " Controles Prenatales"),
                    ("partos", " Partos"),
                    ("calculadoras", " Calculadoras Médicas"),
                    ("calidad", "⭐ Calidad de Atención"),
                    ("seguridad", "️ Seguridad"),
                    ("productividad", " Productividad"),
                ],
                max_length=20,
                verbose_name=" Categoría",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="codigo",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="️ Código único"
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="descripcion",
            field=models.TextField(
                help_text="Explica qué mide este indicador", verbose_name=" Descripción"
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="frecuencia_actualizacion",
            field=models.CharField(
                choices=[
                    ("tiempo_real", "⚡ Tiempo real"),
                    ("cada_hora", " Cada hora"),
                    ("diario", " Diario"),
                    ("semanal", " Semanal"),
                ],
                default="diario",
                max_length=20,
                verbose_name=" ¿Con qué frecuencia se actualiza",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="icono",
            field=models.CharField(
                blank=True,
                help_text="Nombre del icono (opcional)",
                max_length=50,
                verbose_name=" Icono",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="meta_minima",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name=" Meta mínima aceptable",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="meta_optima",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name=" Meta óptima",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="nombre",
            field=models.CharField(
                help_text="Ej: Total de Pacientes Activos",
                max_length=200,
                verbose_name=" Nombre del Indicador",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="orden_dashboard",
            field=models.IntegerField(default=0, verbose_name=" Orden en el dashboard"),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("numero", " Número simple"),
                    ("porcentaje", " Porcentaje"),
                    ("tendencia", " Tendencia"),
                    ("ratio", "⚖️ Proporción"),
                    ("tiempo", "⏱️ Tiempo promedio"),
                ],
                max_length=20,
                verbose_name=" Tipo de indicador",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="unidad_medida",
            field=models.CharField(
                blank=True,
                help_text="Ej: pacientes, %, minutos, días",
                max_length=20,
                verbose_name=" Unidad de medida",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="valor_actual",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name=" Valor actual",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="valor_anterior",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name=" Valor anterior",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="visible_administrador",
            field=models.BooleanField(
                default=True, verbose_name=" ¿Visible para administradores"
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="visible_director",
            field=models.BooleanField(
                default=True, verbose_name=" ¿Visible para director"
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="visible_medico",
            field=models.BooleanField(
                default=True, verbose_name="\u200d⚕️ ¿Visible para médicos"
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="accesos_descarga",
            field=models.IntegerField(default=0, verbose_name=" Número de descargas"),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "⏳ Pendiente"),
                    ("procesando", "⚙️ Procesando"),
                    ("completado", "✅ Completado"),
                    ("error", "❌ Error"),
                    ("expirado", "⏰ Expirado"),
                ],
                default="pendiente",
                max_length=20,
                verbose_name=" Estado del reporte",
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="fecha_fin",
            field=models.DateField(
                blank=True, null=True, verbose_name=" Fecha de fin del período"
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="fecha_inicio",
            field=models.DateField(
                blank=True, null=True, verbose_name=" Fecha de inicio del período"
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="fecha_solicitud",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name=" Fecha de solicitud"
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="filtro_medico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reportes_filtrados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="\u200d⚕️ Médico específico",
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="filtro_paciente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pacientes.paciente",
                verbose_name=" Paciente específico",
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="filtro_servicio",
            field=models.CharField(
                blank=True, max_length=100, verbose_name=" Servicio médico"
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="formato",
            field=models.CharField(
                choices=[
                    ("pd", " PDF"),
                    ("excel", " Excel"),
                    ("csv", " CSV"),
                    ("json", "⚙️ JSON"),
                ],
                default="pd",
                max_length=10,
                verbose_name=" Formato de descarga",
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="hash_archivo",
            field=models.CharField(
                blank=True,
                max_length=128,
                verbose_name=" Hash de seguridad del archivo",
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="observaciones",
            field=models.TextField(
                blank=True, verbose_name=" Observaciones adicionales"
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="ruta_archivo",
            field=models.CharField(
                blank=True, max_length=500, verbose_name=" Ruta del archivo"
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="tipo_reporte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reportes.tiporeporte",
                verbose_name=" Tipo de Reporte",
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="total_registros",
            field=models.IntegerField(
                blank=True, null=True, verbose_name=" Total de registros incluidos"
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="usuario_solicitante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reportes_solicitados",
                to=settings.AUTH_USER_MODEL,
                verbose_name=" Usuario que solicitó el reporte",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="activo",
            field=models.BooleanField(default=True, verbose_name="✅ ¿Está activo"),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="automatico",
            field=models.BooleanField(
                default=False,
                help_text="Si está activado, el reporte se generará según la frecuencia seleccionada",
                verbose_name=" ¿Generar automáticamente",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("estadistico", " Estadísticas y Métricas"),
                    ("paciente", " Reportes de Pacientes"),
                    ("institucional", " Reportes Institucionales"),
                    ("regulatorio", " Cumplimiento Regulatorio"),
                    ("clinico", " Reportes Clínicos"),
                    ("financiero", " Reportes Financieros"),
                ],
                max_length=20,
                verbose_name=" Categoría del Reporte",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="codigo",
            field=models.CharField(
                blank=True,
                help_text="Código interno (se genera automáticamente si se deja vacío)",
                max_length=50,
                unique=True,
                verbose_name=" Código Único",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="confidencial",
            field=models.BooleanField(
                default=False,
                help_text="Solo usuarios autorizados podrán ver este reporte",
                verbose_name=" ¿Es confidencial",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="descripcion",
            field=models.TextField(
                help_text="Describe qué información incluye este reporte",
                verbose_name=" Descripción",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="formato_csv",
            field=models.BooleanField(
                default=False,
                help_text="Formato simple para importar en otros sistemas",
                verbose_name=" ¿Disponible en CSV",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="formato_excel",
            field=models.BooleanField(
                default=True,
                help_text="Formato ideal para análisis de datos",
                verbose_name=" ¿Disponible en Excel",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="formato_json",
            field=models.BooleanField(
                default=False,
                help_text="Formato para integración con otros sistemas",
                verbose_name="⚙️ ¿Disponible en JSON",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="formato_pdf",
            field=models.BooleanField(
                default=True,
                help_text="Formato ideal para imprimir y compartir",
                verbose_name=" ¿Disponible en PDF",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="frecuencia",
            field=models.CharField(
                choices=[
                    ("bajo_demanda", " Generar cuando se necesite"),
                    ("diario", " Todos los días"),
                    ("semanal", " Cada semana"),
                    ("mensual", "️ Mensualmente"),
                    ("trimestral", " Cada 3 meses"),
                    ("anual", " Anualmente"),
                ],
                default="bajo_demanda",
                max_length=20,
                verbose_name="⏰ ¿Con qué frecuencia se genera",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="incluir_fecha_fin",
            field=models.BooleanField(
                default=True, verbose_name=" ¿Permitir filtrar por fecha de fin"
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="incluir_fecha_inicio",
            field=models.BooleanField(
                default=True, verbose_name=" ¿Permitir filtrar por fecha de inicio"
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="incluir_medico",
            field=models.BooleanField(
                default=False, verbose_name="\u200d⚕️ ¿Permitir filtrar por médico"
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="incluir_paciente",
            field=models.BooleanField(
                default=False, verbose_name=" ¿Permitir filtrar por paciente específico"
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="incluir_servicio",
            field=models.BooleanField(
                default=False, verbose_name=" ¿Permitir filtrar por servicio médico"
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="nombre",
            field=models.CharField(
                help_text="Ej: Reporte de Pacientes del Mes",
                max_length=200,
                verbose_name=" Nombre del Reporte",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="permitir_administrador",
            field=models.BooleanField(
                default=True,
                verbose_name=" ¿Los administradores pueden generar este reporte",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="permitir_director",
            field=models.BooleanField(
                default=True,
                verbose_name=" ¿El director médico puede generar este reporte",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="permitir_enfermero",
            field=models.BooleanField(
                default=False,
                verbose_name="\u200d⚕️ ¿Los enfermeros pueden generar este reporte",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="permitir_medico",
            field=models.BooleanField(
                default=True,
                verbose_name="\u200d⚕️ ¿Los médicos pueden generar este reporte",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="requiere_parametros",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el usuario debe configurar parámetros específicos",
                verbose_name=" ¿Requiere parámetros adicionales",
            ),
        ),
    ]
