# Generated by Django 6.0.5 on 2026-06-21 01:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0007_remove_reportegenerado_tamaño_archivo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertamedica",
            name="estado",
            field=models.CharField(
                choices=[
                    ("activa", "Activa"),
                    ("revisada", "Revisada"),
                    ("resuelta", "Resuelta"),
                    ("descartada", "Descartada"),
                    ("escalada", "Escalada"),
                ],
                default="activa",
                max_length=15,
                verbose_name=" Estado actual",
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="modulo_origen",
            field=models.CharField(
                choices=[
                    ("pacientes", "Módulo de Pacientes"),
                    ("embarazos", "Módulo de Embarazos"),
                    ("controles", "Controles Prenatales"),
                    ("ecografias", "Ecografías"),
                    ("laboratorio", "Laboratorio"),
                    ("calculadoras", "Calculadoras Médicas"),
                    ("partos", "Partos"),
                    ("sistema", "Sistema"),
                ],
                max_length=50,
                verbose_name=" Módulo de origen",
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="prioridad",
            field=models.CharField(
                choices=[
                    ("baja", "Baja"),
                    ("media", "Media"),
                    ("alta", "Alta"),
                    ("critica", "Crítica"),
                    ("emergencia", "EMERGENCIA"),
                ],
                max_length=15,
                verbose_name="⚡ Prioridad",
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("valor_critico", "Valor crítico detectado"),
                    ("seguimiento_vencido", "Seguimiento vencido"),
                    ("medicamento_contraindicado", "Medicamento contraindicado"),
                    ("riesgo_alto", "Riesgo alto detectado"),
                    ("resultado_anormal", "Resultado anormal"),
                    ("cita_perdida", "Cita perdida"),
                    ("protocolo_incumplido", "Protocolo no seguido"),
                    ("auditoria", "Requiere auditoría"),
                ],
                max_length=30,
                verbose_name="️ Tipo de alerta",
            ),
        ),
        migrations.CreateModel(
            name="ConfiguracionAlertas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alertar_presion_alta",
                    models.BooleanField(
                        default=True, verbose_name="Alertar sobre presión arterial alta"
                    ),
                ),
                (
                    "limite_presion_sistolica",
                    models.IntegerField(
                        default=140,
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(250),
                        ],
                        verbose_name="Límite superior presión sistólica (mmHg)",
                    ),
                ),
                (
                    "alertar_glucosa_alta",
                    models.BooleanField(
                        default=True, verbose_name="Alertar sobre glucosa elevada"
                    ),
                ),
                (
                    "limite_glucosa_ayunas",
                    models.IntegerField(
                        default=105,
                        validators=[
                            django.core.validators.MinValueValidator(70),
                            django.core.validators.MaxValueValidator(300),
                        ],
                        verbose_name="Límite glucosa en ayunas (mg/dL)",
                    ),
                ),
                (
                    "alertar_resultados_criticos",
                    models.BooleanField(
                        default=True, verbose_name="Alertar sobre resultados críticos"
                    ),
                ),
                (
                    "alertar_resultados_anormales",
                    models.BooleanField(
                        default=True, verbose_name="Alertar sobre resultados anormales"
                    ),
                ),
                (
                    "notificar_por_email",
                    models.BooleanField(
                        default=False, verbose_name="Enviar notificaciones por email"
                    ),
                ),
                (
                    "notificar_por_sistema",
                    models.BooleanField(
                        default=True,
                        verbose_name="Mostrar notificaciones en el sistema",
                    ),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Última Actualización Por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Alertas",
                "verbose_name_plural": "Configuración de Alertas",
                "db_table": "configuracion_alertas",
            },
        ),
    ]
