# Generated by Django 6.0.5 on 2026-07-12 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0008_alter_alertamedica_estado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboardkpi",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("pacientes", "Pacientes"),
                    ("embarazos", "Embarazos"),
                    ("controles", "Controles Prenatales"),
                    ("partos", "Partos"),
                    ("calculadoras", "Calculadoras Médicas"),
                    ("calidad", "Calidad de Atención"),
                    ("seguridad", "Seguridad"),
                    ("productividad", "Productividad"),
                ],
                max_length=20,
                verbose_name=" Categoría",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="frecuencia_actualizacion",
            field=models.CharField(
                choices=[
                    ("tiempo_real", "Tiempo real"),
                    ("cada_hora", "Cada hora"),
                    ("diario", "Diario"),
                    ("semanal", "Semanal"),
                ],
                default="diario",
                max_length=20,
                verbose_name=" ¿Con qué frecuencia se actualiza",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("numero", "Número simple"),
                    ("porcentaje", "Porcentaje"),
                    ("tendencia", "Tendencia"),
                    ("ratio", "Proporción"),
                    ("tiempo", "Tiempo promedio"),
                ],
                max_length=20,
                verbose_name=" Tipo de indicador",
            ),
        ),
    ]
