# Generated by Django 5.1.3 on 2025-12-17 11:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("controles", "0005_alter_controlprenatal_altura_uterina"),
        ("embarazos", "0004_embarazo_peso_pregestacional_embarazo_talla_materna"),
        ("pacientes", "0005_paciente_estado_civil_paciente_ocupacion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotaEvolucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_consulta",
                    models.DateTimeField(verbose_name="Fecha y Hora de Consulta"),
                ),
                (
                    "tipo_consulta",
                    models.CharField(
                        choices=[
                            ("control_prenatal", "Control Prenatal"),
                            ("urgencia", "Consulta de Urgencia"),
                            ("seguimiento", "Seguimiento"),
                            ("interconsulta", "Interconsulta"),
                            ("puerperio", "Control Puerperio"),
                            ("otro", "Otro"),
                        ],
                        default="control_prenatal",
                        max_length=30,
                        verbose_name="Tipo de Consulta",
                    ),
                ),
                (
                    "motivo_consulta",
                    models.TextField(
                        help_text="Razón principal de la consulta según paciente",
                        verbose_name="Motivo de Consulta",
                    ),
                ),
                (
                    "presion_arterial_sistolica",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(250),
                        ],
                        verbose_name="Presión Arterial Sistólica (mmHg)",
                    ),
                ),
                (
                    "presion_arterial_diastolica",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(150),
                        ],
                        verbose_name="Presión Arterial Diastólica (mmHg)",
                    ),
                ),
                (
                    "frecuencia_cardiaca",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(40),
                            django.core.validators.MaxValueValidator(200),
                        ],
                        verbose_name="Frecuencia Cardíaca (lpm)",
                    ),
                ),
                (
                    "frecuencia_respiratoria",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(40),
                        ],
                        verbose_name="Frecuencia Respiratoria (rpm)",
                    ),
                ),
                (
                    "temperatura",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(35.0),
                            django.core.validators.MaxValueValidator(42.0),
                        ],
                        verbose_name="Temperatura (°C)",
                    ),
                ),
                (
                    "saturacion_oxigeno",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(70),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Saturación de Oxígeno (%)",
                    ),
                ),
                (
                    "edad_gestacional_semanas",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(4),
                            django.core.validators.MaxValueValidator(45),
                        ],
                        verbose_name="Edad Gestacional (semanas)",
                    ),
                ),
                (
                    "edad_gestacional_dias",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                        verbose_name="Edad Gestacional (días adicionales)",
                    ),
                ),
                (
                    "altura_uterina",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(60),
                        ],
                        verbose_name="Altura Uterina (cm)",
                    ),
                ),
                (
                    "frecuencia_cardiaca_fetal",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="Frecuencia Cardíaca Fetal (lpm)",
                    ),
                ),
                (
                    "presentacion_fetal",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Cefálica, Pélvica, Transversa",
                        max_length=50,
                        verbose_name="Presentación Fetal",
                    ),
                ),
                (
                    "movimientos_fetales",
                    models.CharField(
                        blank=True,
                        help_text="Presentes/Ausentes, Frecuencia",
                        max_length=100,
                        verbose_name="Movimientos Fetales",
                    ),
                ),
                (
                    "examen_fisico",
                    models.TextField(
                        help_text="Hallazgos del examen físico general y por sistemas",
                        verbose_name="Examen Físico Completo",
                    ),
                ),
                (
                    "examen_obstetrico",
                    models.TextField(
                        blank=True,
                        help_text="Maniobras de Leopold, especuloscopía, tacto vaginal",
                        verbose_name="Examen Obstétrico",
                    ),
                ),
                (
                    "diagnosticos",
                    models.TextField(
                        help_text="Lista de diagnósticos actuales (CIE-10 si es posible)",
                        verbose_name="Impresión Diagnóstica",
                    ),
                ),
                (
                    "plan_tratamiento",
                    models.TextField(
                        help_text="Medicamentos, indicaciones, estudios a solicitar",
                        verbose_name="Plan de Tratamiento",
                    ),
                ),
                (
                    "indicaciones",
                    models.TextField(
                        blank=True,
                        help_text="Signos de alarma, cuidados, próxima cita",
                        verbose_name="Indicaciones al Paciente",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, verbose_name="Observaciones Adicionales",
                    ),
                ),
                (
                    "fecha_revision",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Revisión",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro",
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Modificación",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Nota visible en el sistema",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "control_prenatal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notas_evolucion",
                        to="controles.controlprenatal",
                        verbose_name="Control Prenatal Asociado",
                    ),
                ),
                (
                    "embarazo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notas_evolucion",
                        to="embarazos.embarazo",
                        verbose_name="Embarazo Asociado",
                    ),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notas_evolucion_creadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Médico Responsable",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_evolucion",
                        to="pacientes.paciente",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "revisado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notas_evolucion_revisadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Revisado Por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de Evolución",
                "verbose_name_plural": "Notas de Evolución",
                "db_table": "notas_evolucion",
                "ordering": ["-fecha_consulta"],
                "indexes": [
                    models.Index(
                        fields=["paciente", "-fecha_consulta"],
                        name="notas_evolu_pacient_44b0a6_idx",
                    ),
                    models.Index(
                        fields=["embarazo", "-fecha_consulta"],
                        name="notas_evolu_embaraz_fffdf7_idx",
                    ),
                    models.Index(
                        fields=["medico", "-fecha_consulta"],
                        name="notas_evolu_medico__204e09_idx",
                    ),
                ],
            },
        ),
    ]
