# Generated by Django 5.1.3 on 2025-11-04 05:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "embarazo_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Relación con el embarazo",
                        null=True,
                        verbose_name="ID del Embarazo",
                    ),
                ),
                (
                    "paciente_id",
                    models.IntegerField(
                        help_text="Relación con el paciente",
                        verbose_name="ID del Paciente",
                    ),
                ),
                (
                    "medico_responsable_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Médico que atiende el parto",
                        null=True,
                        verbose_name="ID del Médico Responsable",
                    ),
                ),
                (
                    "numero_parto",
                    models.CharField(
                        help_text="Número único del parto",
                        max_length=20,
                        unique=True,
                        verbose_name="Número de Parto",
                    ),
                ),
                (
                    "fecha_ingreso",
                    models.DateTimeField(verbose_name="Fecha y Hora de Ingreso"),
                ),
                (
                    "fecha_inicio_trabajo_parto",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Inicio del Trabajo de Parto",
                    ),
                ),
                (
                    "fecha_parto",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha y Hora del Parto"
                    ),
                ),
                (
                    "edad_gestacional_parto",
                    models.CharField(
                        help_text="Ej: 39+2",
                        max_length=10,
                        verbose_name="Edad Gestacional al Parto",
                    ),
                ),
                (
                    "tipo_parto",
                    models.CharField(
                        choices=[
                            ("vaginal_espontaneo", "Vaginal Espontáneo"),
                            ("vaginal_instrumentado", "Vaginal Instrumentado"),
                            ("cesarea_electiva", "Cesárea Electiva"),
                            ("cesarea_urgencia", "Cesárea de Urgencia"),
                            ("cesarea_emergencia", "Cesárea de Emergencia"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Parto",
                    ),
                ),
                (
                    "presentacion_fetal",
                    models.CharField(
                        choices=[
                            ("cefalica", "Cefálica"),
                            ("podalica", "Podálica"),
                            ("transversa", "Transversa"),
                            ("oblicua", "Oblicua"),
                        ],
                        default="cefalica",
                        max_length=20,
                        verbose_name="Presentación Fetal",
                    ),
                ),
                (
                    "posicion_fetal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("oia", "Occípito Ilíaca Anterior"),
                            ("oip", "Occípito Ilíaca Posterior"),
                            ("oit", "Occípito Ilíaca Transversa"),
                            ("oda", "Occípito Derecha Anterior"),
                            ("odp", "Occípito Derecha Posterior"),
                            ("odt", "Occípito Derecha Transversa"),
                        ],
                        max_length=20,
                        verbose_name="Posición Fetal",
                    ),
                ),
                (
                    "estado_membranas",
                    models.CharField(
                        choices=[
                            ("integras", "Membranas Íntegras"),
                            ("rotas_espontaneas", "Rotura Espontánea"),
                            ("rotas_artificiales", "Rotura Artificial"),
                        ],
                        default="integras",
                        max_length=30,
                        verbose_name="Estado de Membranas",
                    ),
                ),
                (
                    "hora_rotura_membranas",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Hora de Rotura de Membranas",
                    ),
                ),
                (
                    "caracteristicas_liquido",
                    models.CharField(
                        blank=True,
                        help_text="Claro, meconial, sanguinolento",
                        max_length=100,
                        verbose_name="Características del Líquido Amniótico",
                    ),
                ),
                (
                    "duracion_trabajo_parto_horas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Duración Total del Trabajo de Parto (horas)",
                    ),
                ),
                (
                    "duracion_periodo_expulsivo_minutos",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(600),
                        ],
                        verbose_name="Duración del Período Expulsivo (minutos)",
                    ),
                ),
                (
                    "analgesia_utilizada",
                    models.BooleanField(
                        default=False, verbose_name="¿Se utilizó analgesia?"
                    ),
                ),
                (
                    "tipo_analgesia",
                    models.CharField(
                        blank=True,
                        help_text="Epidural, raquídea, general, local",
                        max_length=100,
                        verbose_name="Tipo de Analgesia",
                    ),
                ),
                (
                    "episiotomia",
                    models.BooleanField(
                        default=False, verbose_name="¿Se realizó episiotomía?"
                    ),
                ),
                (
                    "tipo_episiotomia",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Tipo de Episiotomía"
                    ),
                ),
                (
                    "desgarros",
                    models.BooleanField(default=False, verbose_name="¿Hubo desgarros?"),
                ),
                (
                    "grado_desgarros",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Grado y Localización de Desgarros",
                    ),
                ),
                (
                    "tipo_alumbramiento",
                    models.CharField(
                        choices=[
                            ("espontaneo", "Espontáneo"),
                            ("dirigido", "Dirigido"),
                            ("manual", "Manual"),
                        ],
                        default="espontaneo",
                        max_length=50,
                        verbose_name="Tipo de Alumbramiento",
                    ),
                ),
                (
                    "placenta_completa",
                    models.BooleanField(
                        default=True, verbose_name="¿Placenta completa?"
                    ),
                ),
                (
                    "peso_placenta",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                        verbose_name="Peso de la Placenta (g)",
                    ),
                ),
                (
                    "perdida_sanguinea_estimada",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5000),
                        ],
                        verbose_name="Pérdida Sanguínea Estimada (ml)",
                    ),
                ),
                (
                    "hemorragia_postparto",
                    models.BooleanField(
                        default=False, verbose_name="¿Hemorragia postparto?"
                    ),
                ),
                (
                    "complicaciones_maternas",
                    models.TextField(
                        blank=True,
                        help_text="Describir cualquier complicación durante el parto",
                        verbose_name="Complicaciones Maternas",
                    ),
                ),
                (
                    "oxitocina_utilizada",
                    models.BooleanField(
                        default=False, verbose_name="¿Se utilizó oxitocina?"
                    ),
                ),
                (
                    "dosis_oxitocina",
                    models.CharField(
                        blank=True,
                        help_text="UI totales utilizadas",
                        max_length=100,
                        verbose_name="Dosis de Oxitocina",
                    ),
                ),
                (
                    "otros_medicamentos",
                    models.TextField(
                        blank=True, verbose_name="Otros Medicamentos Utilizados"
                    ),
                ),
                (
                    "observaciones_parto",
                    models.TextField(
                        blank=True, verbose_name="Observaciones del Parto"
                    ),
                ),
                (
                    "indicaciones_cesarea",
                    models.TextField(
                        blank=True,
                        help_text="Solo completar si es cesárea",
                        verbose_name="Indicaciones de Cesárea",
                    ),
                ),
                (
                    "parto_finalizado",
                    models.BooleanField(
                        default=False, verbose_name="¿Parto finalizado?"
                    ),
                ),
                (
                    "trabajo_parto_espontaneo",
                    models.BooleanField(
                        default=True, verbose_name="¿Trabajo de parto espontáneo?"
                    ),
                ),
                (
                    "induccion_parto",
                    models.BooleanField(
                        default=False, verbose_name="¿Se indujo el parto?"
                    ),
                ),
                (
                    "metodo_induccion",
                    models.CharField(
                        blank=True,
                        help_text="Prostaglandinas, oxitocina, amniotomía",
                        max_length=200,
                        verbose_name="Método de Inducción",
                    ),
                ),
                (
                    "monitoreo_fetal_continuo",
                    models.BooleanField(
                        default=False, verbose_name="¿Monitoreo fetal continuo?"
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Parto",
                "verbose_name_plural": "Partos",
                "db_table": "partos",
                "ordering": ["-fecha_parto"],
                "indexes": [
                    models.Index(
                        fields=["paciente_id", "-fecha_parto"],
                        name="partos_pacient_9e7fcb_idx",
                    ),
                    models.Index(
                        fields=["fecha_parto"], name="partos_fecha_p_c67a9b_idx"
                    ),
                    models.Index(
                        fields=["tipo_parto"], name="partos_tipo_pa_de8e73_idx"
                    ),
                    models.Index(
                        fields=["numero_parto"], name="partos_numero__dd22b8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PartogramaRegistro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hora_registro",
                    models.DateTimeField(verbose_name="Hora del Registro"),
                ),
                (
                    "horas_trabajo_parto",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(48),
                        ],
                        verbose_name="Horas en Trabajo de Parto",
                    ),
                ),
                (
                    "dilatacion_cervical",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Dilatación Cervical (cm)",
                    ),
                ),
                (
                    "borramiento_cervical",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Borramiento Cervical (%)",
                    ),
                ),
                (
                    "estacion_fetal",
                    models.CharField(
                        help_text="Ej: -3, -2, -1, 0, +1, +2, +3",
                        max_length=10,
                        verbose_name="Estación Fetal",
                    ),
                ),
                (
                    "contracciones_10min",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Contracciones en 10 minutos",
                    ),
                ),
                (
                    "duracion_contracciones",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(120),
                        ],
                        verbose_name="Duración Contracciones (segundos)",
                    ),
                ),
                (
                    "intensidad_contracciones",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("leves", "Leves"),
                            ("moderadas", "Moderadas"),
                            ("fuertes", "Fuertes"),
                        ],
                        max_length=20,
                        verbose_name="Intensidad de Contracciones",
                    ),
                ),
                (
                    "fcf_baseline",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(80),
                            django.core.validators.MaxValueValidator(200),
                        ],
                        verbose_name="FCF Basal (lpm)",
                    ),
                ),
                (
                    "variabilidad_fcf",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ausente", "Ausente"),
                            ("minima", "Mínima"),
                            ("moderada", "Moderada"),
                            ("marcada", "Marcada"),
                        ],
                        max_length=20,
                        verbose_name="Variabilidad FCF",
                    ),
                ),
                (
                    "desaceleraciones",
                    models.CharField(
                        blank=True,
                        help_text="Tardías, variables, prolongadas",
                        max_length=100,
                        verbose_name="Desaceleraciones",
                    ),
                ),
                (
                    "presion_arterial_sistolica",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(70),
                            django.core.validators.MaxValueValidator(250),
                        ],
                        verbose_name="Presión Arterial Sistólica (mmHg)",
                    ),
                ),
                (
                    "presion_arterial_diastolica",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(40),
                            django.core.validators.MaxValueValidator(150),
                        ],
                        verbose_name="Presión Arterial Diastólica (mmHg)",
                    ),
                ),
                (
                    "temperatura",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(35.0),
                            django.core.validators.MaxValueValidator(42.0),
                        ],
                        verbose_name="Temperatura (°C)",
                    ),
                ),
                (
                    "pulso_materno",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(40),
                            django.core.validators.MaxValueValidator(150),
                        ],
                        verbose_name="Pulso Materno (lpm)",
                    ),
                ),
                (
                    "oxitocina_dosis",
                    models.CharField(
                        blank=True,
                        help_text="mU/min",
                        max_length=50,
                        verbose_name="Dosis de Oxitocina",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, verbose_name="Observaciones del Registro"
                    ),
                ),
                (
                    "alerta_progreso_lento",
                    models.BooleanField(
                        default=False, verbose_name="Alerta: Progreso lento"
                    ),
                ),
                (
                    "alerta_fcf_anormal",
                    models.BooleanField(
                        default=False, verbose_name="Alerta: FCF anormal"
                    ),
                ),
                (
                    "alerta_signos_vitales",
                    models.BooleanField(
                        default=False, verbose_name="Alerta: Signos vitales alterados"
                    ),
                ),
                (
                    "registrado_por_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID Usuario que registró"
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "parto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partograma",
                        to="partos.parto",
                        verbose_name="Parto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Partograma",
                "verbose_name_plural": "Registros de Partograma",
                "db_table": "partograma_registros",
                "ordering": ["parto", "hora_registro"],
                "indexes": [
                    models.Index(
                        fields=["parto", "hora_registro"],
                        name="partograma__parto_i_02523f_idx",
                    ),
                    models.Index(
                        fields=["dilatacion_cervical"],
                        name="partograma__dilatac_3fc447_idx",
                    ),
                    models.Index(
                        fields=["fcf_baseline"], name="partograma__fcf_bas_4c5818_idx"
                    ),
                ],
                "unique_together": {("parto", "hora_registro")},
            },
        ),
        migrations.CreateModel(
            name="RecienNacido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_gemelo",
                    models.IntegerField(
                        default=1,
                        help_text="1 para único, 2,3,4,5 para múltiples",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Número de Gemelo",
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateTimeField(verbose_name="Fecha y Hora de Nacimiento"),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[
                            ("masculino", "Masculino"),
                            ("femenino", "Femenino"),
                            ("indeterminado", "Indeterminado"),
                        ],
                        max_length=20,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "estado_nacimiento",
                    models.CharField(
                        choices=[
                            ("vivo", "Vivo"),
                            ("mortinato", "Mortinato"),
                            ("muerte_neonatal", "Muerte Neonatal"),
                        ],
                        default="vivo",
                        max_length=20,
                        verbose_name="Estado al Nacimiento",
                    ),
                ),
                (
                    "peso_nacimiento",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(300),
                            django.core.validators.MaxValueValidator(6000),
                        ],
                        verbose_name="Peso al Nacimiento (g)",
                    ),
                ),
                (
                    "talla_nacimiento",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(60),
                        ],
                        verbose_name="Talla al Nacimiento (cm)",
                    ),
                ),
                (
                    "perimetro_cefalico",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(50),
                        ],
                        verbose_name="Perímetro Cefálico (cm)",
                    ),
                ),
                (
                    "apgar_1_minuto",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Apgar 1 minuto",
                    ),
                ),
                (
                    "apgar_5_minutos",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Apgar 5 minutos",
                    ),
                ),
                (
                    "apgar_10_minutos",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Apgar 10 minutos",
                    ),
                ),
                (
                    "requirio_reanimacion",
                    models.BooleanField(
                        default=False, verbose_name="¿Requirió reanimación?"
                    ),
                ),
                (
                    "tipo_reanimacion",
                    models.CharField(
                        blank=True,
                        help_text="Estimulación, O2, VPP, masaje cardíaco, intubación",
                        max_length=200,
                        verbose_name="Tipo de Reanimación",
                    ),
                ),
                (
                    "malformaciones_congenitas",
                    models.BooleanField(
                        default=False, verbose_name="¿Malformaciones congénitas?"
                    ),
                ),
                (
                    "descripcion_malformaciones",
                    models.TextField(
                        blank=True, verbose_name="Descripción de Malformaciones"
                    ),
                ),
                (
                    "destino_rn",
                    models.CharField(
                        choices=[
                            ("alojamiento_conjunto", "Alojamiento Conjunto"),
                            ("neonatologia", "Neonatología"),
                            ("uci_neonatal", "UCI Neonatal"),
                            ("traslado", "Traslado a otro centro"),
                            ("fallecido", "Fallecido"),
                        ],
                        default="alojamiento_conjunto",
                        max_length=100,
                        verbose_name="Destino del Recién Nacido",
                    ),
                ),
                (
                    "llanto_inmediato",
                    models.BooleanField(
                        default=True, verbose_name="¿Llanto inmediato?"
                    ),
                ),
                (
                    "respiracion_espontanea",
                    models.BooleanField(
                        default=True, verbose_name="¿Respiración espontánea?"
                    ),
                ),
                (
                    "tono_muscular_normal",
                    models.BooleanField(
                        default=True, verbose_name="¿Tono muscular normal?"
                    ),
                ),
                (
                    "observaciones_rn",
                    models.TextField(
                        blank=True, verbose_name="Observaciones del Recién Nacido"
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "parto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recien_nacidos",
                        to="partos.parto",
                        verbose_name="Parto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recién Nacido",
                "verbose_name_plural": "Recién Nacidos",
                "db_table": "recien_nacidos",
                "ordering": ["parto", "numero_gemelo"],
                "indexes": [
                    models.Index(
                        fields=["parto", "numero_gemelo"],
                        name="recien_naci_parto_i_0d55d2_idx",
                    ),
                    models.Index(
                        fields=["fecha_nacimiento"],
                        name="recien_naci_fecha_n_8a8ce9_idx",
                    ),
                    models.Index(
                        fields=["peso_nacimiento"],
                        name="recien_naci_peso_na_7ee8b8_idx",
                    ),
                ],
                "unique_together": {("parto", "numero_gemelo")},
            },
        ),
    ]
