# Generated by Django 5.1.3 on 2026-01-02 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ecografias", "0004_anatomiafetal_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EcografiaArchivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(upload_to="ecografias/archivos/%Y/%m/%d/"),
                ),
                (
                    "tipo_archivo",
                    models.CharField(
                        choices=[
                            ("imagen", "Imagen"),
                            ("video", "Video"),
                            ("dicom", "DICOM"),
                            ("pdf", "PDF"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nombre_archivo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("tamaño_bytes", models.BigIntegerField(blank=True, null=True)),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "ecografia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archivos",
                        to="ecografias.ecografia",
                    ),
                ),
                (
                    "subido_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo de Ecografía",
                "verbose_name_plural": "Archivos de Ecografías",
                "db_table": "ecografias_archivos",
                "ordering": ["-fecha_subida"],
            },
        ),
    ]
