# Generated by Django 6.0.5 on 2026-05-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecografias_archivos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ecografiaarchivo",
            name="tamaño_bytes",
        ),
        migrations.AddField(
            model_name="ecografiaarchivo",
            name="tamano_bytes",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ecografiaarchivo",
            name="tipo_archivo",
            field=models.CharField(
                choices=[
                    ("imagen", "Imagen"),
                    ("video", "Video"),
                    ("dicom", "DICOM"),
                    ("pd", "PDF"),
                ],
                max_length=20,
            ),
        ),
    ]
