# Generated by Django 5.1.3 on 2026-01-03 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("laboratorio", "0004_examenlaboratorio_created_by_and_more"),
        ("pacientes", "0006_paciente_created_by_paciente_updated_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EstadisticasIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(unique=True)),
                ("total_consultas", models.IntegerField(default=0)),
                ("consultas_por_categoria", models.JSONField(default=dict)),
                ("tiempo_respuesta_promedio_ms", models.IntegerField(default=0)),
                ("total_analisis_ml", models.IntegerField(default=0)),
                ("alertas_criticas_generadas", models.IntegerField(default=0)),
                ("patologias_detectadas", models.JSONField(default=dict)),
                ("precision_promedio", models.FloatField(default=0.0)),
                ("confianza_promedio", models.FloatField(default=0.0)),
                ("total_feedback", models.IntegerField(default=0)),
                ("feedback_positivo", models.IntegerField(default=0)),
                ("rating_promedio", models.FloatField(default=0.0)),
                ("usuarios_activos", models.IntegerField(default=0)),
                ("nuevos_usuarios", models.IntegerField(default=0)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Estadísticas IA",
                "verbose_name_plural": "Estadísticas IA",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="ConsultaIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consulta_original",
                    models.TextField(help_text="Texto original de la consulta"),
                ),
                (
                    "consulta_procesada",
                    models.TextField(help_text="Texto procesado/normalizado"),
                ),
                (
                    "idioma_detectado",
                    models.CharField(
                        choices=[
                            ("es", "Español"),
                            ("en", "Inglés"),
                            ("auto", "Auto-detectado"),
                        ],
                        default="auto",
                        max_length=10,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("preeclampsia", "Preeclampsia"),
                            ("diabetes", "Diabetes Gestacional"),
                            ("rciu", "Restricción Crecimiento Intrauterino"),
                            ("laboratorio", "Análisis de Laboratorio"),
                            ("edad_gestacional", "Edad Gestacional"),
                            ("general", "Consulta General"),
                            ("emergencia", "Emergencia Obstétrica"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "respuesta_ia",
                    models.TextField(help_text="Respuesta generada por la IA"),
                ),
                (
                    "confianza",
                    models.FloatField(
                        default=0.0, help_text="Nivel de confianza (0-100)",
                    ),
                ),
                (
                    "requiere_ml",
                    models.BooleanField(
                        default=False, help_text="Si requiere análisis ML avanzado",
                    ),
                ),
                (
                    "resultado_ml",
                    models.JSONField(
                        blank=True, help_text="Resultados del análisis ML", null=True,
                    ),
                ),
                (
                    "util",
                    models.BooleanField(
                        blank=True, help_text="¿Fue útil la respuesta?", null=True,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True, help_text="Calificación 1-5", null=True,
                    ),
                ),
                (
                    "comentario_feedback",
                    models.TextField(blank=True, help_text="Comentario del usuario"),
                ),
                ("fecha_consulta", models.DateTimeField(auto_now_add=True)),
                (
                    "tiempo_respuesta_ms",
                    models.IntegerField(
                        default=0, help_text="Tiempo de procesamiento en ms",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "paciente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pacientes.paciente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultas_ia",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta IA",
                "verbose_name_plural": "Consultas IA",
                "ordering": ["-fecha_consulta"],
            },
        ),
        migrations.CreateModel(
            name="AnalisisLaboratorioML",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_analisis",
                    models.CharField(
                        choices=[
                            ("hemograma", "Hemograma Completo"),
                            ("glucosa", "Glucosa / Diabetes"),
                            ("funcion_hepatica", "Función Hepática"),
                            ("funcion_renal", "Función Renal"),
                            ("proteinas", "Proteínas / Proteinuria"),
                            ("tiroides", "Perfil Tiroideo"),
                            ("completo", "Análisis Completo"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "datos_entrada",
                    models.JSONField(help_text="Valores de laboratorio analizados"),
                ),
                (
                    "prediccion",
                    models.CharField(
                        help_text="Predicción del modelo ML", max_length=200,
                    ),
                ),
                (
                    "riesgo_detectado",
                    models.CharField(
                        choices=[
                            ("bajo", "Riesgo Bajo"),
                            ("medio", "Riesgo Medio"),
                            ("alto", "Riesgo Alto"),
                            ("critico", "Riesgo Crítico"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "probabilidad",
                    models.FloatField(help_text="Probabilidad de la predicción (0-1)"),
                ),
                (
                    "confianza_modelo",
                    models.FloatField(
                        default=0.0, help_text="Confianza del modelo (0-100)",
                    ),
                ),
                (
                    "patologias_detectadas",
                    models.JSONField(
                        default=list, help_text="Lista de patologías detectadas",
                    ),
                ),
                (
                    "alertas_criticas",
                    models.JSONField(
                        default=list, help_text="Alertas críticas generadas",
                    ),
                ),
                (
                    "recomendaciones",
                    models.JSONField(
                        default=list, help_text="Recomendaciones basadas en ML",
                    ),
                ),
                (
                    "acciones_sugeridas",
                    models.JSONField(
                        default=list, help_text="Acciones inmediatas sugeridas",
                    ),
                ),
                (
                    "valores_fuera_rango",
                    models.JSONField(default=list, help_text="Valores fuera de rango"),
                ),
                (
                    "tendencia_temporal",
                    models.JSONField(
                        blank=True, help_text="Análisis de tendencia", null=True,
                    ),
                ),
                (
                    "modelo_usado",
                    models.CharField(default="RandomForest_v1", max_length=100),
                ),
                ("version_modelo", models.CharField(default="1.0", max_length=20)),
                ("fecha_analisis", models.DateTimeField(auto_now_add=True)),
                ("tiempo_procesamiento_ms", models.IntegerField(default=0)),
                ("validado_por_medico", models.BooleanField(default=False)),
                ("fecha_validacion", models.DateTimeField(blank=True, null=True)),
                ("notas_validacion", models.TextField(blank=True)),
                (
                    "medico_validador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validaciones_ml",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analisis_ml",
                        to="pacientes.paciente",
                    ),
                ),
                (
                    "resultado_lab",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laboratorio.resultadolaboratorio",
                    ),
                ),
                (
                    "consulta_ia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ia_medica.consultaia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análisis ML Laboratorio",
                "verbose_name_plural": "Análisis ML Laboratorio",
                "ordering": ["-fecha_analisis"],
            },
        ),
        migrations.CreateModel(
            name="DatasetEntrenamientoIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_dato",
                    models.CharField(
                        choices=[
                            ("consulta_respuesta", "Par Consulta-Respuesta"),
                            ("caso_clinico", "Caso Clínico"),
                            ("laboratorio", "Resultado de Laboratorio"),
                            ("diagnostico", "Diagnóstico"),
                            ("protocolo", "Protocolo Médico"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "fuente",
                    models.CharField(
                        choices=[
                            ("manual", "Ingreso Manual"),
                            ("literatura", "Literatura Médica"),
                            ("guias_clinicas", "Guías Clínicas"),
                            ("casos_reales", "Casos Reales (Anonimizados)"),
                            ("acog", "Guías ACOG"),
                            ("who", "Guías OMS/WHO"),
                        ],
                        max_length=50,
                    ),
                ),
                ("idioma", models.CharField(default="es", max_length=10)),
                (
                    "texto_entrada",
                    models.TextField(
                        help_text="Texto de entrada (consulta, síntomas, etc.)",
                    ),
                ),
                (
                    "texto_salida",
                    models.TextField(
                        help_text="Texto esperado de salida (respuesta, diagnóstico)",
                    ),
                ),
                (
                    "especialidad",
                    models.CharField(
                        default="Ginecología y Obstetricia", max_length=100,
                    ),
                ),
                ("categoria_medica", models.CharField(max_length=100)),
                (
                    "keywords",
                    models.JSONField(default=list, help_text="Palabras clave médicas"),
                ),
                (
                    "datos_estructurados",
                    models.JSONField(
                        blank=True, help_text="Datos en formato ML", null=True,
                    ),
                ),
                (
                    "etiquetas",
                    models.JSONField(
                        default=list, help_text="Etiquetas para clasificación",
                    ),
                ),
                ("validado", models.BooleanField(default=False)),
                ("fecha_validacion", models.DateTimeField(blank=True, null=True)),
                ("usado_entrenamiento", models.BooleanField(default=False)),
                ("fecha_ultimo_uso", models.DateTimeField(blank=True, null=True)),
                (
                    "efectividad",
                    models.FloatField(
                        blank=True, help_text="Efectividad en entrenamiento", null=True,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "validador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dataset Entrenamiento IA",
                "verbose_name_plural": "Datasets Entrenamiento IA",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionModeloIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_modelo", models.CharField(max_length=100, unique=True)),
                (
                    "tipo_modelo",
                    models.CharField(
                        choices=[
                            ("nlp", "Procesamiento Lenguaje Natural"),
                            ("ml_laboratorio", "ML Análisis Laboratorio"),
                            ("clasificacion", "Clasificación Patologías"),
                            ("prediccion_riesgo", "Predicción de Riesgos"),
                        ],
                        max_length=50,
                    ),
                ),
                ("version", models.CharField(max_length=20)),
                ("descripcion", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("desarrollo", "En Desarrollo"),
                            ("entrenamiento", "En Entrenamiento"),
                            ("prueba", "En Pruebas"),
                            ("produccion", "En Producción"),
                            ("deprecado", "Deprecado"),
                        ],
                        default="desarrollo",
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(default=False)),
                (
                    "precision",
                    models.FloatField(
                        default=0.0, help_text="Precisión del modelo (0-100)",
                    ),
                ),
                ("recall", models.FloatField(default=0.0)),
                ("f1_score", models.FloatField(default=0.0)),
                ("accuracy", models.FloatField(default=0.0)),
                (
                    "parametros",
                    models.JSONField(
                        default=dict, help_text="Hiperparámetros del modelo",
                    ),
                ),
                (
                    "features_usadas",
                    models.JSONField(default=list, help_text="Features utilizadas"),
                ),
                (
                    "dataset_entrenamiento",
                    models.TextField(help_text="Descripción del dataset usado"),
                ),
                ("fecha_entrenamiento", models.DateTimeField(blank=True, null=True)),
                ("epocas", models.IntegerField(default=0)),
                (
                    "ruta_modelo",
                    models.CharField(
                        blank=True,
                        help_text="Ruta al archivo del modelo",
                        max_length=500,
                    ),
                ),
                ("ruta_vectorizer", models.CharField(blank=True, max_length=500)),
                ("ruta_scaler", models.CharField(blank=True, max_length=500)),
                ("total_predicciones", models.IntegerField(default=0)),
                ("predicciones_correctas", models.IntegerField(default=0)),
                ("ultima_prediccion", models.DateTimeField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("notas", models.TextField(blank=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración Modelo IA",
                "verbose_name_plural": "Configuraciones Modelos IA",
                "ordering": ["-fecha_creacion"],
                "unique_together": {("nombre_modelo", "version")},
            },
        ),
        migrations.AddIndex(
            model_name="consultaia",
            index=models.Index(
                fields=["-fecha_consulta"], name="ia_medica_c_fecha_c_f15aa1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consultaia",
            index=models.Index(
                fields=["usuario", "-fecha_consulta"],
                name="ia_medica_c_usuario_21b833_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consultaia",
            index=models.Index(
                fields=["categoria"], name="ia_medica_c_categor_712c40_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analisislaboratorioml",
            index=models.Index(
                fields=["-fecha_analisis"], name="ia_medica_a_fecha_a_431d50_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analisislaboratorioml",
            index=models.Index(
                fields=["paciente", "-fecha_analisis"],
                name="ia_medica_a_pacient_04bc7c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analisislaboratorioml",
            index=models.Index(
                fields=["riesgo_detectado"], name="ia_medica_a_riesgo__7d2441_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="datasetentrenamientoia",
            index=models.Index(
                fields=["tipo_dato"], name="ia_medica_d_tipo_da_6325b1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="datasetentrenamientoia",
            index=models.Index(
                fields=["categoria_medica"], name="ia_medica_d_categor_fd4efe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="datasetentrenamientoia",
            index=models.Index(
                fields=["validado"], name="ia_medica_d_validad_3e550b_idx",
            ),
        ),
    ]
