# Generated by Django 6.0.4 on 2026-04-24 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import ia_medica.models


class Migration(migrations.Migration):
    dependencies = [
        ("ia_medica", "0001_initial"),
        ("pacientes", "0006_paciente_created_by_paciente_updated_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagenEcografica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        help_text="Archivo de imagen ecográfica",
                        upload_to=ia_medica.models.imagen_ecografica_upload_path,
                    ),
                ),
                (
                    "nombre_original",
                    models.CharField(
                        help_text="Nombre original del archivo", max_length=255,
                    ),
                ),
                (
                    "tamanio_bytes",
                    models.BigIntegerField(default=0, help_text="Tamaño en bytes"),
                ),
                (
                    "formato",
                    models.CharField(
                        default="jpg",
                        help_text="Formato: jpg, png, tiff, dicom",
                        max_length=20,
                    ),
                ),
                (
                    "resolucion_ancho",
                    models.IntegerField(default=0, help_text="Ancho en píxeles"),
                ),
                (
                    "resolucion_alto",
                    models.IntegerField(default=0, help_text="Alto en píxeles"),
                ),
                (
                    "tipo_imagen",
                    models.CharField(
                        choices=[
                            ("eco_2d", "Ecografía 2D"),
                            ("eco_3d", "Ecografía 3D"),
                            ("eco_4d", "Ecografía 4D"),
                            ("doppler", "Doppler Fetal"),
                            ("morfologica", "Ecografía Morfológica"),
                            ("transvaginal", "Ecografía Transvaginal"),
                            ("dicom", "Imagen DICOM"),
                            ("otro", "Otro"),
                        ],
                        default="eco_2d",
                        max_length=30,
                    ),
                ),
                (
                    "semana_gestacional",
                    models.IntegerField(
                        blank=True,
                        help_text="Semana gestacional al momento de la imagen",
                        null=True,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, help_text="Descripción clínica de la imagen",
                    ),
                ),
                (
                    "notas_tecnicas",
                    models.TextField(
                        blank=True, help_text="Notas técnicas del operador",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de Análisis"),
                            ("procesando", "Procesando"),
                            ("analizada", "Analizada"),
                            ("error", "Error en Análisis"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "es_principal",
                    models.BooleanField(
                        default=False, help_text="Imagen principal del paciente",
                    ),
                ),
                (
                    "dicom_metadata",
                    models.JSONField(
                        blank=True, help_text="Metadatos DICOM extraídos", null=True,
                    ),
                ),
                (
                    "fecha_captura",
                    models.DateField(
                        blank=True, help_text="Fecha de captura de la imagen", null=True,
                    ),
                ),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        help_text="Paciente dueña de la imagen",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes_cnn",
                        to="pacientes.paciente",
                    ),
                ),
                (
                    "subida_por",
                    models.ForeignKey(
                        help_text="Usuario que subió la imagen",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imagenes_subidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen Ecográfica CNN",
                "verbose_name_plural": "Imágenes Ecográficas CNN",
                "ordering": ["-fecha_subida"],
            },
        ),
        migrations.CreateModel(
            name="AnalisisCNN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modelo_usado",
                    models.CharField(
                        choices=[
                            ("resnet50", "ResNet-50 (Clasificación)"),
                            ("unet", "U-Net (Segmentación)"),
                            ("efficientnet", "EfficientNet-B4 (Alta Precisión)"),
                            ("yolo_fetal", "YOLO Fetal (Detección)"),
                            ("custom_cnn", "CNN Personalizada"),
                        ],
                        default="resnet50",
                        max_length=30,
                    ),
                ),
                ("version_modelo", models.CharField(default="1.0.0", max_length=20)),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("anomalia_leve", "Anomalía Leve"),
                            ("anomalia_moderada", "Anomalía Moderada"),
                            ("anomalia_grave", "Anomalía Grave"),
                            ("requiere_revision", "Requiere Revisión Médica"),
                            ("indeterminado", "Indeterminado"),
                        ],
                        default="indeterminado",
                        max_length=30,
                    ),
                ),
                (
                    "confianza",
                    models.FloatField(
                        default=0.0, help_text="Confianza de la predicción (0.0 - 1.0)",
                    ),
                ),
                (
                    "score_general",
                    models.FloatField(
                        default=0.0, help_text="Score general del análisis (0-100)",
                    ),
                ),
                (
                    "predicciones",
                    models.JSONField(
                        default=list,
                        help_text="Lista de predicciones: [{clase, confianza, probabilidad}]",
                    ),
                ),
                (
                    "clases_detectadas",
                    models.JSONField(
                        default=list,
                        help_text="Clases/estructuras anatómicas detectadas",
                    ),
                ),
                (
                    "bounding_boxes",
                    models.JSONField(
                        blank=True,
                        help_text="Coordenadas de detecciones: [{x, y, w, h, clase, confianza}]",
                        null=True,
                    ),
                ),
                (
                    "estructuras_detectadas",
                    models.JSONField(
                        default=dict,
                        help_text="Estructuras fetales identificadas: {cabeza, columna, corazon, etc}",
                    ),
                ),
                (
                    "medidas_estimadas",
                    models.JSONField(
                        blank=True,
                        help_text="Medidas estimadas por IA: {bpd, hc, ac, fl}",
                        null=True,
                    ),
                ),
                (
                    "anomalias_detectadas",
                    models.JSONField(
                        default=list, help_text="Lista de anomalías detectadas",
                    ),
                ),
                (
                    "alertas",
                    models.JSONField(
                        default=list, help_text="Alertas clínicas generadas",
                    ),
                ),
                (
                    "recomendaciones",
                    models.JSONField(
                        default=list, help_text="Recomendaciones clínicas",
                    ),
                ),
                (
                    "heatmap_data",
                    models.JSONField(
                        blank=True,
                        help_text="Datos del mapa de calor Grad-CAM",
                        null=True,
                    ),
                ),
                ("tiempo_procesamiento_ms", models.IntegerField(default=0)),
                ("validado_por_medico", models.BooleanField(default=False)),
                ("notas_medico", models.TextField(blank=True)),
                ("fecha_validacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_analisis", models.DateTimeField(auto_now_add=True)),
                (
                    "medico_validador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validaciones_cnn",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "realizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analisis_cnn_realizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "imagen",
                    models.OneToOneField(
                        help_text="Imagen analizada",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analisis_cnn",
                        to="ia_medica.imagenecografica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análisis CNN",
                "verbose_name_plural": "Análisis CNN",
                "ordering": ["-fecha_analisis"],
            },
        ),
        migrations.CreateModel(
            name="ModeloCNNConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                (
                    "codigo",
                    models.CharField(
                        help_text="Identificador: resnet50, unet, etc.",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("arquitectura", models.CharField(max_length=100)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("entrenando", "En Entrenamiento"),
                            ("prueba", "En Pruebas"),
                        ],
                        default="activo",
                        max_length=20,
                    ),
                ),
                (
                    "accuracy",
                    models.FloatField(
                        default=0.0, help_text="Precisión en validación (0-100)",
                    ),
                ),
                (
                    "sensitivity",
                    models.FloatField(
                        default=0.0, help_text="Sensibilidad/Recall (0-100)",
                    ),
                ),
                (
                    "specificity",
                    models.FloatField(default=0.0, help_text="Especificidad (0-100)"),
                ),
                (
                    "auc_roc",
                    models.FloatField(default=0.0, help_text="AUC-ROC score (0-1)"),
                ),
                ("f1_score", models.FloatField(default=0.0)),
                ("dataset_entrenamiento", models.CharField(blank=True, max_length=200)),
                ("total_imagenes_entrenamiento", models.IntegerField(default=0)),
                ("epocas_entrenamiento", models.IntegerField(default=0)),
                ("fecha_entrenamiento", models.DateTimeField(blank=True, null=True)),
                ("total_predicciones", models.IntegerField(default=0)),
                ("predicciones_hoy", models.IntegerField(default=0)),
                ("tiempo_promedio_ms", models.IntegerField(default=0)),
                ("ruta_pesos", models.CharField(blank=True, max_length=500)),
                ("version", models.CharField(default="1.0.0", max_length=20)),
                (
                    "clases_detectables",
                    models.JSONField(
                        default=list, help_text="Lista de clases que puede detectar",
                    ),
                ),
                ("parametros_config", models.JSONField(default=dict)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración Modelo CNN",
                "verbose_name_plural": "Configuraciones Modelos CNN",
                "ordering": ["-accuracy"],
            },
        ),
        migrations.AddIndex(
            model_name="imagenecografica",
            index=models.Index(
                fields=["paciente", "-fecha_subida"],
                name="ia_medica_i_pacient_45e55b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="imagenecografica",
            index=models.Index(
                fields=["tipo_imagen"], name="ia_medica_i_tipo_im_31c238_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="imagenecografica",
            index=models.Index(fields=["estado"], name="ia_medica_i_estado_11da6d_idx"),
        ),
        migrations.AddIndex(
            model_name="analisiscnn",
            index=models.Index(
                fields=["-fecha_analisis"], name="ia_medica_a_fecha_a_672f8f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analisiscnn",
            index=models.Index(
                fields=["resultado"], name="ia_medica_a_resulta_801174_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analisiscnn",
            index=models.Index(
                fields=["modelo_usado"], name="ia_medica_a_modelo__58d483_idx",
            ),
        ),
    ]
