# Generated by Django 6.0.4 on 2026-05-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ia_medica", "0002_imagenecografica_analisiscnn_modelocnnconfig_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analisiscnn",
            name="heatmap_data",
        ),
        migrations.AddField(
            model_name="analisiscnn",
            name="ac_mm",
            field=models.FloatField(blank=True, null=True, verbose_name="AC (mm)"),
        ),
        migrations.AddField(
            model_name="analisiscnn",
            name="bpd_mm",
            field=models.FloatField(blank=True, null=True, verbose_name="BPD (mm)"),
        ),
        migrations.AddField(
            model_name="analisiscnn",
            name="fl_mm",
            field=models.FloatField(blank=True, null=True, verbose_name="FL (mm)"),
        ),
        migrations.AddField(
            model_name="analisiscnn",
            name="hc_mm",
            field=models.FloatField(blank=True, null=True, verbose_name="HC (mm)"),
        ),
        migrations.AddField(
            model_name="analisiscnn",
            name="mapa_calor",
            field=models.TextField(
                blank=True, help_text="PNG base64 del mapa de calor Grad-CAM", null=True,
            ),
        ),
        migrations.AddField(
            model_name="analisiscnn",
            name="nivel_riesgo",
            field=models.CharField(
                blank=True,
                choices=[("BAJO", "Bajo"), ("MODERADO", "Moderado"), ("ALTO", "Alto")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="analisiscnn",
            name="observaciones_medico",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="analisiscnn",
            name="patologias",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="analisiscnn",
            name="riesgo_parto_prematuro",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analisiscnn",
            name="riesgo_preeclampsia",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analisiscnn",
            name="shap_valores",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analisiscnn",
            name="tiempo_inferencia_ms",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
