# Generated by Django 6.0.5 on 2026-05-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ia_medica", "0004_5nf_patologia_detectada"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="alertacnnanalisis",
            name="alerta_cnn_analisis_idx",
        ),
        migrations.RemoveIndex(
            model_name="patologiadetectadacnn",
            name="patologia_confianza_idx",
        ),
        migrations.RemoveIndex(
            model_name="patologiadetectadacnn",
            name="patologia_analisis_sev_idx",
        ),
        migrations.AlterField(
            model_name="alertacnnanalisis",
            name="codigo",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="alertacnnanalisis",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="alertacnnanalisis",
            name="procesada",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="alertacnnanalisis",
            name="severidad",
            field=models.CharField(
                choices=[
                    ("CRITICO", "Crítico"),
                    ("ALTO", "Alto"),
                    ("MEDIO", "Medio"),
                    ("BAJO", "Bajo"),
                    ("INFO", "Info"),
                ],
                db_index=True,
                default="MEDIO",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="consultaia",
            name="util",
            field=models.BooleanField(
                blank=True, help_text="¿Fue útil la respuesta", null=True
            ),
        ),
        migrations.AlterField(
            model_name="patologiadetectadacnn",
            name="codigo_cie10",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="patologiadetectadacnn",
            name="confianza",
            field=models.FloatField(verbose_name="Confianza (0-1)"),
        ),
        migrations.AlterField(
            model_name="patologiadetectadacnn",
            name="descripcion",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="patologiadetectadacnn",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="patologiadetectadacnn",
            name="patologia",
            field=models.CharField(
                db_index=True, max_length=80, verbose_name="Patología"
            ),
        ),
        migrations.AlterField(
            model_name="patologiadetectadacnn",
            name="recomendacion",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="patologiadetectadacnn",
            name="requiere_especialista",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="patologiadetectadacnn",
            name="severidad",
            field=models.CharField(
                choices=[
                    ("alta", "Alta"),
                    ("media-alta", "Media-Alta"),
                    ("media", "Media"),
                    ("baja", "Baja"),
                ],
                db_index=True,
                default="media",
                max_length=20,
            ),
        ),
    ]
