# Generated by Django 6.0.5 on 2026-06-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ia_medica", "0005_remove_alertacnnanalisis_alerta_cnn_analisis_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analisiscnn",
            name="sugerencia_diagnostica",
            field=models.JSONField(
                blank=True,
                help_text="Diagnóstico sugerido: {patologia, confianza, descripcion, icd10, recomendacion}",
                null=True,
            ),
        ),
    ]
