# Generated by Django 6.0.5 on 2026-06-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ia_medica", "0006_analisiscnn_sugerencia_diagnostica"),
    ]

    operations = [
        migrations.AddField(
            model_name="analisiscnn",
            name="reporte_narrativo_fecha",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analisiscnn",
            name="reporte_narrativo_ia",
            field=models.JSONField(
                blank=True,
                help_text="Reporte narrativo generado por LLM local con vision (Ollama), grounded en el resultado real del CNN.",
                null=True,
            ),
        ),
    ]
