# Generated by Django 5.1.3 on 2025-11-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CatRol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("medico", "Médico"),
                            ("enfermera", "Enfermera"),
                            ("administrativo", "Administrativo"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("descripcion", models.TextField()),
                (
                    "permisos",
                    models.JSONField(
                        default=dict,
                        help_text="Permisos específicos del rol en formato JSON",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "db_table": "cat_roles",
            },
        ),
    ]
