# Generated by Django 6.0.5 on 2026-06-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0002_seed_cat_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catrol",
            name="nombre",
            field=models.CharField(
                choices=[
                    ("medico", "Médico"),
                    ("enfermera", "Enfermera"),
                    ("laboratorista", "Laboratorista"),
                    ("administrador", "Administrador"),
                    ("recepcion", "Recepción"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
