# Generated by Django 5.1.3 on 2025-11-27 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionNotificaciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recibir_push",
                    models.BooleanField(
                        default=True,
                        help_text="Notificaciones en la aplicación web/móvil",
                        verbose_name="Recibir Notificaciones Push",
                    ),
                ),
                (
                    "recibir_email",
                    models.BooleanField(
                        default=True, verbose_name="Recibir Notificaciones por Email",
                    ),
                ),
                (
                    "recibir_sms",
                    models.BooleanField(
                        default=False, verbose_name="Recibir Notificaciones por SMS",
                    ),
                ),
                (
                    "notificar_citas",
                    models.BooleanField(default=True, verbose_name="Notificar Citas"),
                ),
                (
                    "notificar_examenes",
                    models.BooleanField(
                        default=True, verbose_name="Notificar Exámenes",
                    ),
                ),
                (
                    "notificar_alertas",
                    models.BooleanField(
                        default=True, verbose_name="Notificar Alertas Médicas",
                    ),
                ),
                (
                    "notificar_mensajes",
                    models.BooleanField(
                        default=True, verbose_name="Notificar Mensajes",
                    ),
                ),
                (
                    "notificar_documentos",
                    models.BooleanField(
                        default=True, verbose_name="Notificar Documentos",
                    ),
                ),
                (
                    "recordatorio_citas_horas",
                    models.IntegerField(
                        default=24,
                        help_text="Cuántas horas antes de la cita enviar recordatorio",
                        verbose_name="Recordar Citas (horas antes)",
                    ),
                ),
                (
                    "recordatorio_controles",
                    models.BooleanField(
                        default=True, verbose_name="Recordar Controles Prenatales",
                    ),
                ),
                (
                    "no_molestar_inicio",
                    models.TimeField(
                        blank=True,
                        help_text="Hora de inicio del modo no molestar (ej: 22:00)",
                        null=True,
                        verbose_name="No Molestar - Inicio",
                    ),
                ),
                (
                    "no_molestar_fin",
                    models.TimeField(
                        blank=True,
                        help_text="Hora de fin del modo no molestar (ej: 08:00)",
                        null=True,
                        verbose_name="No Molestar - Fin",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_notificaciones",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Notificaciones",
                "verbose_name_plural": "Configuraciones de Notificaciones",
                "db_table": "configuracion_notificaciones",
            },
        ),
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("cita_proxima", "Cita Próxima"),
                            ("cita_confirmada", "Cita Confirmada"),
                            ("cita_cancelada", "Cita Cancelada"),
                            ("cita_reagendada", "Cita Reagendada"),
                            ("examen_listo", "Resultado de Examen Listo"),
                            ("examen_critico", "Resultado Crítico de Examen"),
                            ("examen_solicitado", "Examen Solicitado"),
                            ("alerta_critica", "Alerta Médica Crítica"),
                            ("alerta_advertencia", "Advertencia Médica"),
                            ("alerta_informacion", "Información Médica"),
                            ("recordatorio", "Recordatorio General"),
                            ("recordatorio_medicacion", "Recordatorio de Medicación"),
                            ("recordatorio_control", "Recordatorio de Control"),
                            ("documento_listo", "Documento Listo"),
                            ("receta_nueva", "Nueva Receta Médica"),
                            ("certificado_listo", "Certificado Médico Listo"),
                            ("mensaje_medico", "Mensaje del Médico"),
                            ("novedad_sistema", "Novedad del Sistema"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Notificación",
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("normal", "Normal"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                            ("critica", "Crítica"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Título breve de la notificación",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                (
                    "mensaje",
                    models.TextField(
                        help_text="Contenido detallado de la notificación",
                        verbose_name="Mensaje",
                    ),
                ),
                (
                    "icono",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del icono para UI (ej: bell, alert-circle, check-circle)",
                        max_length=50,
                        verbose_name="Icono",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Color para UI (ej: blue, red, green, yellow)",
                        max_length=20,
                        verbose_name="Color",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="URL para redireccionar al hacer clic (ruta del frontend)",
                        max_length=255,
                        verbose_name="URL de Acción",
                    ),
                ),
                (
                    "url_texto",
                    models.CharField(
                        blank=True,
                        help_text="Texto del botón de acción (ej: Ver Detalle, Ir a Cita)",
                        max_length=100,
                        verbose_name="Texto del Botón",
                    ),
                ),
                (
                    "leida",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el usuario ya leyó la notificación",
                        verbose_name="Leída",
                    ),
                ),
                (
                    "fecha_leida",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Lectura",
                    ),
                ),
                (
                    "archivada",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el usuario archivó la notificación",
                        verbose_name="Archivada",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Datos adicionales en formato JSON (IDs relacionados, etc.)",
                        verbose_name="Metadatos",
                    ),
                ),
                (
                    "entidad_tipo",
                    models.CharField(
                        blank=True,
                        help_text="Ej: cita, examen, control, parto",
                        max_length=50,
                        verbose_name="Tipo de Entidad Relacionada",
                    ),
                ),
                (
                    "entidad_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID de Entidad Relacionada",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "fecha_expiracion",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha en que la notificación deja de ser relevante",
                        null=True,
                        verbose_name="Fecha de Expiración",
                    ),
                ),
                (
                    "enviada_push",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si se envió notificación push",
                        verbose_name="Enviada por Push",
                    ),
                ),
                (
                    "enviada_email",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si se envió por correo electrónico",
                        verbose_name="Enviada por Email",
                    ),
                ),
                (
                    "enviada_sms",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si se envió por SMS",
                        verbose_name="Enviada por SMS",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        help_text="Usuario que recibirá la notificación",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario Destinatario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "db_table": "notificaciones",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="HistorialNotificaciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("creada", "Creada"),
                            ("enviada_push", "Enviada por Push"),
                            ("enviada_email", "Enviada por Email"),
                            ("enviada_sms", "Enviada por SMS"),
                            ("leida", "Leída"),
                            ("archivada", "Archivada"),
                            ("expirada", "Expirada"),
                        ],
                        max_length=50,
                        verbose_name="Acción",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "detalles",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Detalles Adicionales",
                    ),
                ),
                (
                    "notificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="notificaciones.notificacion",
                        verbose_name="Notificación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Notificación",
                "verbose_name_plural": "Historial de Notificaciones",
                "db_table": "historial_notificaciones",
                "ordering": ["-fecha"],
            },
        ),
        migrations.AddIndex(
            model_name="notificacion",
            index=models.Index(
                fields=["usuario", "-fecha_creacion"],
                name="notificacio_usuario_cf1441_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificacion",
            index=models.Index(
                fields=["usuario", "leida"], name="notificacio_usuario_ef49b7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificacion",
            index=models.Index(fields=["tipo"], name="notificacio_tipo_f5d897_idx"),
        ),
        migrations.AddIndex(
            model_name="notificacion",
            index=models.Index(
                fields=["prioridad"], name="notificacio_priorid_eb1da5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificacion",
            index=models.Index(
                fields=["fecha_creacion"], name="notificacio_fecha_c_24f290_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificacion",
            index=models.Index(
                fields=["entidad_tipo", "entidad_id"],
                name="notificacio_entidad_1323ac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="historialnotificaciones",
            index=models.Index(
                fields=["notificacion", "-fecha"], name="historial_n_notific_44b634_idx",
            ),
        ),
    ]
