# Generated by Django 5.1.3 on 2025-12-14 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="descripcion",
            field=models.TextField(
                blank=True,
                help_text="Biografía o descripción del usuario",
                null=True,
                verbose_name="Descripción",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="foto",
            field=models.ImageField(
                blank=True,
                help_text="Imagen de perfil del usuario",
                null=True,
                upload_to="usuarios/fotos/",
                verbose_name="Foto de Perfil",
            ),
        ),
        migrations.CreateModel(
            name="HorarioAtencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.CharField(
                        choices=[
                            ("lunes", "Lunes"),
                            ("martes", "Martes"),
                            ("miercoles", "Miércoles"),
                            ("jueves", "Jueves"),
                            ("viernes", "Viernes"),
                            ("sabado", "Sábado"),
                            ("domingo", "Domingo"),
                        ],
                        max_length=10,
                        verbose_name="Día de la Semana",
                    ),
                ),
                ("hora_inicio", models.TimeField(verbose_name="Hora de Inicio")),
                ("hora_fin", models.TimeField(verbose_name="Hora de Fin")),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Si está desactivado, no se mostrarán citas en este horario",
                        verbose_name="Activo",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios_atencion",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horario de Atención",
                "verbose_name_plural": "Horarios de Atención",
                "db_table": "usuarios_horarios_atencion",
                "ordering": ["dia_semana", "hora_inicio"],
                "unique_together": {("usuario", "dia_semana", "hora_inicio")},
            },
        ),
    ]
