# Generated by Django 6.0.4 on 2026-05-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0003_usuario_mfa_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="mfa_obligatorio",
            field=models.BooleanField(
                default=False,
                help_text="True automáticamente para médicos y administradores — no puede desactivarse",
                verbose_name="MFA Obligatorio",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="bloqueado_hasta",
            field=models.DateTimeField(
                blank=True,
                help_text="Cuenta bloqueada después de 5 intentos fallidos",
                null=True,
                verbose_name="Bloqueado hasta",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="mfa_secret",
            field=models.CharField(
                blank=True,
                help_text="Clave TOTP base32 — nunca exponer en APIs públicas",
                max_length=64,
                null=True,
                verbose_name="Secreto MFA",
            ),
        ),
    ]
