# Generated by Django 6.0.5 on 2026-05-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_add_mfa_obligatorio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Es staf"),
        ),
    ]
