# Generated by Django 5.2.7 on 2025-10-27 19:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controles', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Hemograma Completo, Glucosa en Ayunas', max_length=200, unique=True, verbose_name='Nombre del Examen')),
                ('codigo', models.CharField(help_text='Código interno del examen', max_length=50, unique=True, verbose_name='Código')),
                ('categoria', models.CharField(choices=[('hematologia', 'Hematología'), ('bioquimica', 'Bioquímica'), ('inmunologia', 'Inmunología'), ('microbiologia', 'Microbiología'), ('urinalisis', 'Urianálisis'), ('serologia', 'Serología'), ('hormonal', 'Hormonal'), ('genetica', 'Genética')], max_length=50, verbose_name='Categoría')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del examen', verbose_name='Descripción')),
                ('preparacion', models.TextField(blank=True, help_text='Indicaciones de preparación para el paciente', verbose_name='Preparación')),
                ('tiempo_resultado', models.IntegerField(default=24, help_text='Tiempo estimado para obtener resultados', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Tiempo de Resultado (horas)')),
                ('precio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio del examen en bolivianos', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio (Bs)')),
                ('activo', models.BooleanField(default=True, help_text='Si el examen está disponible', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Examen',
                'verbose_name_plural': 'Tipos de Exámenes',
                'db_table': 'tipos_examenes',
                'ordering': ['categoria', 'nombre'],
                'indexes': [models.Index(fields=['codigo'], name='tipos_exame_codigo_d29ee8_idx'), models.Index(fields=['categoria'], name='tipos_exame_categor_18f6bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExamenLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_muestra', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Toma de Muestra')),
                ('fecha_resultado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resultado')),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='solicitado', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente'), ('stat', 'STAT (Inmediato)')], default='normal', max_length=20, verbose_name='Prioridad')),
                ('indicaciones', models.TextField(blank=True, help_text='Motivo de la solicitud e indicaciones', verbose_name='Indicaciones Clínicas')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones generales del examen', verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('control_prenatal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes', to='controles.controlprenatal', verbose_name='Control Prenatal Asociado')),
                ('medico_solicitante', models.ForeignKey(blank=True, limit_choices_to={'rol': 'medico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Médico Solicitante')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_laboratorio', to='pacientes.paciente', verbose_name='Paciente')),
                ('tipo_examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examenes', to='laboratorio.tipoexamen', verbose_name='Tipo de Examen')),
            ],
            options={
                'verbose_name': 'Examen de Laboratorio',
                'verbose_name_plural': 'Exámenes de Laboratorio',
                'db_table': 'examenes_laboratorio',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='ValorReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(help_text='Ej: Hemoglobina, Glucosa, Hematocrito', max_length=200, verbose_name='Parámetro')),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Mínimo')),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Máximo')),
                ('valor_normal', models.CharField(blank=True, help_text='Para valores cualitativos (Ej: Negativo, Positivo)', max_length=200, verbose_name='Valor Normal')),
                ('unidad', models.CharField(choices=[('mg/dL', 'mg/dL'), ('g/dL', 'g/dL'), ('mmol/L', 'mmol/L'), ('mEq/L', 'mEq/L'), ('pg/mL', 'pg/mL'), ('ng/mL', 'ng/mL'), ('UI/L', 'UI/L'), ('U/L', 'U/L'), ('%', '%'), ('células/mm³', 'células/mm³'), ('10³/µL', '10³/µL'), ('10⁶/µL', '10⁶/µL'), ('segundos', 'segundos'), ('ratio', 'ratio'), ('cualitativo', 'Cualitativo')], max_length=50, verbose_name='Unidad de Medida')),
                ('condicion', models.CharField(blank=True, help_text='Ej: En ayunas, Embarazadas primer trimestre', max_length=200, verbose_name='Condición')),
                ('es_critico_bajo', models.DecimalField(blank=True, decimal_places=2, help_text='Valor por debajo del cual se considera crítico', max_digits=10, null=True, verbose_name='Valor Crítico Bajo')),
                ('es_critico_alto', models.DecimalField(blank=True, decimal_places=2, help_text='Valor por encima del cual se considera crítico', max_digits=10, null=True, verbose_name='Valor Crítico Alto')),
                ('tipo_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_referencia', to='laboratorio.tipoexamen', verbose_name='Tipo de Examen')),
            ],
            options={
                'verbose_name': 'Valor de Referencia',
                'verbose_name_plural': 'Valores de Referencia',
                'db_table': 'valores_referencia',
                'ordering': ['tipo_examen', 'parametro'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Numérico')),
                ('valor_texto', models.CharField(blank=True, help_text='Para resultados cualitativos', max_length=500, verbose_name='Valor Texto')),
                ('es_normal', models.BooleanField(default=True, verbose_name='¿Es Normal?')),
                ('es_critico', models.BooleanField(default=False, verbose_name='¿Es Crítico?')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones del Resultado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='laboratorio.examenlaboratorio', verbose_name='Examen')),
                ('valor_referencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='laboratorio.valorreferencia', verbose_name='Parámetro')),
            ],
            options={
                'verbose_name': 'Resultado de Laboratorio',
                'verbose_name_plural': 'Resultados de Laboratorio',
                'db_table': 'resultados_laboratorio',
                'ordering': ['examen', 'valor_referencia'],
            },
        ),
        migrations.AddIndex(
            model_name='examenlaboratorio',
            index=models.Index(fields=['paciente', '-fecha_solicitud'], name='examenes_la_pacient_3bcedb_idx'),
        ),
        migrations.AddIndex(
            model_name='examenlaboratorio',
            index=models.Index(fields=['estado'], name='examenes_la_estado_9b35d2_idx'),
        ),
        migrations.AddIndex(
            model_name='examenlaboratorio',
            index=models.Index(fields=['-fecha_solicitud'], name='examenes_la_fecha_s_10de24_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='valorreferencia',
            unique_together={('tipo_examen', 'parametro', 'condicion')},
        ),
    ]
