# Generated by Django 5.1.3 on 2025-11-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="resultadolaboratorio",
            index=models.Index(
                fields=["examen"], name="resultados__examen__14f800_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resultadolaboratorio",
            index=models.Index(
                fields=["es_critico"], name="resultados__es_crit_52b546_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resultadolaboratorio",
            index=models.Index(
                fields=["es_normal"], name="resultados__es_norm_0e1fa6_idx"
            ),
        ),
    ]
