# Generated by Django 5.1.3 on 2025-12-04 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "laboratorio",
            "0002_resultadolaboratorio_resultados__examen__14f800_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagenLaboratorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        help_text="Resultado escaneado, foto o PDF del laboratorio",
                        upload_to="laboratorio/%Y/%m/%d/",
                        verbose_name="Archivo/Imagen",
                    ),
                ),
                (
                    "tipo_archivo",
                    models.CharField(
                        choices=[
                            ("hoja_resultados", "Hoja de Resultados"),
                            ("hemograma", "Hemograma"),
                            ("bioquimica", "Bioquímica Clínica"),
                            ("urinalisis", "Urianálisis"),
                            ("cultivo", "Cultivo"),
                            ("antibiograma", "Antibiograma"),
                            ("serologia", "Serología"),
                            ("perfil_hormonal", "Perfil Hormonal"),
                            ("perfil_tiroideo", "Perfil Tiroideo"),
                            ("coagulacion", "Coagulación"),
                            ("inmunologia", "Inmunología"),
                            ("toxicologia", "Toxicología"),
                            ("genetica", "Genética"),
                            ("citologia", "Citología"),
                            ("histopatologia", "Histopatología"),
                            ("microbiologia", "Microbiología"),
                            ("papanicolau", "Papanicolau"),
                            ("biopsia", "Biopsia"),
                            ("otros", "Otros Resultados"),
                        ],
                        default="hoja_resultados",
                        max_length=50,
                        verbose_name="Tipo de Archivo",
                    ),
                ),
                (
                    "formato",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("jpg", "JPG/JPEG"),
                            ("png", "PNG"),
                            ("tiff", "TIFF"),
                            ("dicom", "DICOM"),
                        ],
                        default="pdf",
                        max_length=10,
                        verbose_name="Formato del Archivo",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        default="Resultado de Laboratorio",
                        help_text="Ej: Hemograma completo 12/12/2024",
                        max_length=200,
                        verbose_name="Título del Documento",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Notas adicionales sobre el resultado",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "numero_paginas",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Para documentos multi-página",
                        verbose_name="Número de Páginas",
                    ),
                ),
                (
                    "calidad_digitalizacion",
                    models.CharField(
                        choices=[
                            ("excelente", "Excelente"),
                            ("buena", "Buena"),
                            ("regular", "Regular"),
                            ("baja", "Baja"),
                        ],
                        default="buena",
                        max_length=20,
                        verbose_name="Calidad de Digitalización",
                    ),
                ),
                (
                    "es_documento_oficial",
                    models.BooleanField(
                        default=True,
                        help_text="Documento sellado y firmado por laboratorio",
                        verbose_name="¿Es Documento Oficial?",
                    ),
                ),
                (
                    "laboratorio_externo",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del laboratorio que realizó el examen",
                        max_length=200,
                        verbose_name="Laboratorio Externo",
                    ),
                ),
                (
                    "fecha_digitalizacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Digitalización",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Orden de visualización",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "es_archivo_principal",
                    models.BooleanField(
                        default=False,
                        help_text="Documento principal del resultado",
                        verbose_name="¿Es Archivo Principal?",
                    ),
                ),
                (
                    "texto_extraido_ocr",
                    models.TextField(
                        blank=True,
                        help_text="Texto extraído automáticamente del documento",
                        verbose_name="Texto Extraído (OCR)",
                    ),
                ),
                (
                    "datos_extraidos_ia",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Valores y parámetros detectados automáticamente",
                        verbose_name="Datos Extraídos por IA",
                    ),
                ),
                (
                    "validado_por_medico",
                    models.BooleanField(
                        default=False,
                        help_text="El médico ha verificado que el archivo es correcto",
                        verbose_name="¿Validado por Médico?",
                    ),
                ),
                (
                    "digitalizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="digitalizaciones_laboratorio",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Digitalizado Por",
                    ),
                ),
                (
                    "examen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="laboratorio.examenlaboratorio",
                        verbose_name="Examen de Laboratorio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen/Archivo de Laboratorio",
                "verbose_name_plural": "Imágenes/Archivos de Laboratorio",
                "db_table": "imagenes_laboratorio",
                "ordering": ["examen", "orden"],
                "indexes": [
                    models.Index(
                        fields=["examen", "tipo_archivo"],
                        name="imagenes_la_examen__aad86f_idx",
                    ),
                    models.Index(
                        fields=["fecha_digitalizacion"],
                        name="imagenes_la_fecha_d_b39db5_idx",
                    ),
                ],
            },
        ),
    ]
