# Generated by Django 6.0.5 on 2026-05-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0004_examenlaboratorio_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagenlaboratorio",
            name="es_archivo_principal",
            field=models.BooleanField(
                default=False,
                help_text="Documento principal del resultado",
                verbose_name="¿Es Archivo Principal",
            ),
        ),
        migrations.AlterField(
            model_name="imagenlaboratorio",
            name="es_documento_oficial",
            field=models.BooleanField(
                default=True,
                help_text="Documento sellado y firmado por laboratorio",
                verbose_name="¿Es Documento Oficial",
            ),
        ),
        migrations.AlterField(
            model_name="imagenlaboratorio",
            name="formato",
            field=models.CharField(
                choices=[
                    ("pd", "PDF"),
                    ("jpg", "JPG/JPEG"),
                    ("png", "PNG"),
                    ("tif", "TIFF"),
                    ("dicom", "DICOM"),
                ],
                default="pd",
                max_length=10,
                verbose_name="Formato del Archivo",
            ),
        ),
        migrations.AlterField(
            model_name="imagenlaboratorio",
            name="validado_por_medico",
            field=models.BooleanField(
                default=False,
                help_text="El médico ha verificado que el archivo es correcto",
                verbose_name="¿Validado por Médico",
            ),
        ),
        migrations.AlterField(
            model_name="resultadolaboratorio",
            name="es_critico",
            field=models.BooleanField(default=False, verbose_name="¿Es Crítico"),
        ),
        migrations.AlterField(
            model_name="resultadolaboratorio",
            name="es_normal",
            field=models.BooleanField(default=True, verbose_name="¿Es Normal"),
        ),
    ]
