# Generated by Django 6.0.5 on 2026-06-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0005_alter_imagenlaboratorio_es_archivo_principal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examenlaboratorio",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
