# Generated by Django 5.1.3 on 2025-11-24 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citas", "0001_initial"),
        ("consultorios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cita",
            name="consultorio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="citas",
                to="consultorios.consultorio",
                verbose_name="Consultorio",
            ),
        ),
        migrations.AlterField(
            model_name="cita",
            name="estado",
            field=models.CharField(
                choices=[
                    ("agendada", "Agendada"),
                    ("confirmada", "Confirmada"),
                    ("en_espera", "En Sala de Espera"),
                    (" en_consulta", "En Consulta"),
                    ("completada", "Completada"),
                    ("cancelada", "Cancelada"),
                    ("no_asistio", "No Asistió"),
                ],
                default="agendada",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="historialcita",
            name="estado_anterior",
            field=models.CharField(
                choices=[
                    ("agendada", "Agendada"),
                    ("confirmada", "Confirmada"),
                    ("en_espera", "En Sala de Espera"),
                    (" en_consulta", "En Consulta"),
                    ("completada", "Completada"),
                    ("cancelada", "Cancelada"),
                    ("no_asistio", "No Asistió"),
                ],
                max_length=20,
                verbose_name="Estado Anterior",
            ),
        ),
        migrations.AlterField(
            model_name="historialcita",
            name="estado_nuevo",
            field=models.CharField(
                choices=[
                    ("agendada", "Agendada"),
                    ("confirmada", "Confirmada"),
                    ("en_espera", "En Sala de Espera"),
                    (" en_consulta", "En Consulta"),
                    ("completada", "Completada"),
                    ("cancelada", "Cancelada"),
                    ("no_asistio", "No Asistió"),
                ],
                max_length=20,
                verbose_name="Estado Nuevo",
            ),
        ),
    ]
