# Generated by Django 6.0.4 on 2026-04-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citas", "0003_cita_modificado_por_disponibilidad_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cita",
            name="estado",
            field=models.CharField(
                choices=[
                    ("agendada", "Agendada"),
                    ("confirmada", "Confirmada"),
                    ("en_espera", "En Sala de Espera"),
                    ("en_consulta", "En Consulta"),
                    ("completada", "Completada"),
                    ("cancelada", "Cancelada"),
                    ("no_asistio", "No Asistió"),
                ],
                default="agendada",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="historialcita",
            name="estado_anterior",
            field=models.CharField(
                choices=[
                    ("agendada", "Agendada"),
                    ("confirmada", "Confirmada"),
                    ("en_espera", "En Sala de Espera"),
                    ("en_consulta", "En Consulta"),
                    ("completada", "Completada"),
                    ("cancelada", "Cancelada"),
                    ("no_asistio", "No Asistió"),
                ],
                max_length=20,
                verbose_name="Estado Anterior",
            ),
        ),
        migrations.AlterField(
            model_name="historialcita",
            name="estado_nuevo",
            field=models.CharField(
                choices=[
                    ("agendada", "Agendada"),
                    ("confirmada", "Confirmada"),
                    ("en_espera", "En Sala de Espera"),
                    ("en_consulta", "En Consulta"),
                    ("completada", "Completada"),
                    ("cancelada", "Cancelada"),
                    ("no_asistio", "No Asistió"),
                ],
                max_length=20,
                verbose_name="Estado Nuevo",
            ),
        ),
    ]
