# Generated by Django 5.1.3 on 2025-12-17 11:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("embarazos", "0004_embarazo_peso_pregestacional_embarazo_talla_materna"),
        ("pacientes", "0005_paciente_estado_civil_paciente_ocupacion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoVacuna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre oficial de la vacuna",
                        max_length=100,
                        unique=True,
                        verbose_name="Nombre de la Vacuna",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Descripción detallada de la vacuna y su propósito",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "dosis_requeridas",
                    models.IntegerField(
                        default=1,
                        help_text="Número de dosis necesarias para completar el esquema",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Dosis Requeridas",
                    ),
                ),
                (
                    "intervalo_dosis_dias",
                    models.IntegerField(
                        blank=True,
                        help_text="Días mínimos entre cada dosis (si aplica)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Intervalo entre Dosis (días)",
                    ),
                ),
                (
                    "edad_minima_aplicacion",
                    models.IntegerField(
                        blank=True,
                        help_text="Edad mínima en días para aplicar la vacuna",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Edad Mínima de Aplicación",
                    ),
                ),
                (
                    "contraindicaciones",
                    models.TextField(
                        blank=True,
                        help_text="Condiciones que impiden la aplicación de la vacuna",
                        verbose_name="Contraindicaciones",
                    ),
                ),
                (
                    "efectos_secundarios",
                    models.TextField(
                        blank=True,
                        help_text="Efectos secundarios comunes y raros de la vacuna",
                        verbose_name="Efectos Secundarios",
                    ),
                ),
                (
                    "obligatoria_embarazo",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si es obligatoria durante el embarazo",
                        verbose_name="Obligatoria en Embarazo",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si la vacuna está activa en el catálogo",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Vacuna",
                "verbose_name_plural": "Tipos de Vacunas",
                "db_table": "tipos_vacunas",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(
                        fields=["nombre"], name="tipos_vacun_nombre_026f36_idx",
                    ),
                    models.Index(
                        fields=["activo"], name="tipos_vacun_activo_e3be1f_idx",
                    ),
                    models.Index(
                        fields=["obligatoria_embarazo"],
                        name="tipos_vacun_obligat_fdc715_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RegistroVacuna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_aplicacion",
                    models.DateTimeField(
                        help_text="Fecha y hora en que se aplicó la vacuna",
                        verbose_name="Fecha y Hora de Aplicación",
                    ),
                ),
                (
                    "numero_dosis",
                    models.IntegerField(
                        help_text="Número de dosis dentro del esquema (1, 2, 3, etc.)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Número de Dosis",
                    ),
                ),
                (
                    "lote",
                    models.CharField(
                        help_text="Número de lote de la vacuna",
                        max_length=50,
                        verbose_name="Lote",
                    ),
                ),
                (
                    "laboratorio",
                    models.CharField(
                        help_text="Laboratorio fabricante de la vacuna",
                        max_length=100,
                        verbose_name="Laboratorio",
                    ),
                ),
                (
                    "via_administracion",
                    models.CharField(
                        choices=[
                            ("intramuscular", "Intramuscular"),
                            ("subcutanea", "Subcutánea"),
                            ("oral", "Oral"),
                            ("intradermica", "Intradérmica"),
                        ],
                        help_text="Vía por la cual se administró la vacuna",
                        max_length=20,
                        verbose_name="Vía de Administración",
                    ),
                ),
                (
                    "sitio_aplicacion",
                    models.CharField(
                        help_text="Ubicación anatómica donde se aplicó (ej: Deltoides izquierdo)",
                        max_length=100,
                        verbose_name="Sitio de Aplicación",
                    ),
                ),
                (
                    "proxima_dosis_fecha",
                    models.DateField(
                        blank=True,
                        help_text="Fecha programada para la siguiente dosis (si aplica)",
                        null=True,
                        verbose_name="Fecha de Próxima Dosis",
                    ),
                ),
                (
                    "reacciones_adversas",
                    models.TextField(
                        blank=True,
                        help_text="Reacciones adversas reportadas después de la aplicación",
                        verbose_name="Reacciones Adversas",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones adicionales sobre la aplicación",
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el registro está activo",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro",
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación",
                    ),
                ),
                (
                    "aplicado_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Profesional que aplicó la vacuna",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vacunas_aplicadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aplicado Por",
                    ),
                ),
                (
                    "embarazo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Embarazo durante el cual se aplicó la vacuna",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vacunas",
                        to="embarazos.embarazo",
                        verbose_name="Embarazo",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        help_text="Paciente que recibió la vacuna",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacunas",
                        to="pacientes.paciente",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "tipo_vacuna",
                    models.ForeignKey(
                        help_text="Tipo de vacuna aplicada",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros",
                        to="vacunas.tipovacuna",
                        verbose_name="Tipo de Vacuna",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Vacuna",
                "verbose_name_plural": "Registros de Vacunas",
                "db_table": "registros_vacunas",
                "ordering": ["-fecha_aplicacion"],
                "indexes": [
                    models.Index(
                        fields=["paciente", "tipo_vacuna"],
                        name="registros_v_pacient_e33d87_idx",
                    ),
                    models.Index(
                        fields=["fecha_aplicacion"],
                        name="registros_v_fecha_a_6911d2_idx",
                    ),
                    models.Index(
                        fields=["embarazo"], name="registros_v_embaraz_1fa6ff_idx",
                    ),
                    models.Index(
                        fields=["tipo_vacuna", "numero_dosis"],
                        name="registros_v_tipo_va_f0a130_idx",
                    ),
                    models.Index(
                        fields=["proxima_dosis_fecha"],
                        name="registros_v_proxima_68df55_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "paciente",
                            "tipo_vacuna",
                            "numero_dosis",
                            "fecha_aplicacion",
                        ),
                        name="unique_vacuna_aplicacion",
                    ),
                ],
            },
        ),
    ]
