# Generated by Django 5.1.3 on 2025-11-24 02:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecografias", "0002_alter_imagenecografia_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="anexosfetales",
            old_name="placenta_inserccion_cordon",
            new_name="placenta_insercion_cordon",
        ),
    ]
