# Generated by Django 6.0.5 on 2026-05-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecografias", "0005_5nf_medicion_ecografia"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="medicionecografia",
            name="medicion_imagen_tipo_idx",
        ),
        migrations.RemoveIndex(
            model_name="medicionecografia",
            name="medicion_tipo_rango_idx",
        ),
        migrations.RemoveConstraint(
            model_name="medicionecografia",
            name="uq_medicion_imagen_tipo_feto",
        ),
        migrations.AlterField(
            model_name="imagenecografia",
            name="es_imagen_principal",
            field=models.BooleanField(
                default=False,
                help_text="Imagen representativa de la ecografía",
                verbose_name="¿Es Imagen Principal",
            ),
        ),
        migrations.DeleteModel(
            name="MedicionEcografia",
        ),
    ]
