# Generated by Django 6.0.5 on 2026-06-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ecografias",
            "0006_remove_medicionecografia_medicion_imagen_tipo_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="imagenecografia",
            name="orthanc_instance_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="imagenecografia",
            name="orthanc_study_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
