# Generated by Django 5.1.3 on 2025-11-04 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DashboardKPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre del KPI"),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Código Único"
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("pacientes", "Pacientes"),
                            ("embarazos", "Embarazos"),
                            ("controles", "Controles Prenatales"),
                            ("partos", "Partos"),
                            ("calculadoras", "Calculadoras Médicas"),
                            ("calidad", "Calidad de Atención"),
                            ("seguridad", "Seguridad"),
                            ("productividad", "Productividad"),
                        ],
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("numero", "Número Simple"),
                            ("porcentaje", "Porcentaje"),
                            ("tendencia", "Tendencia"),
                            ("ratio", "Ratio"),
                            ("tiempo", "Tiempo Promedio"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de KPI",
                    ),
                ),
                (
                    "consulta_sql",
                    models.TextField(verbose_name="Consulta SQL para Cálculo"),
                ),
                (
                    "parametros_calculo",
                    models.JSONField(
                        default=dict, verbose_name="Parámetros de Cálculo"
                    ),
                ),
                (
                    "frecuencia_actualizacion",
                    models.CharField(
                        choices=[
                            ("tiempo_real", "Tiempo Real"),
                            ("cada_hora", "Cada Hora"),
                            ("diario", "Diario"),
                            ("semanal", "Semanal"),
                        ],
                        default="diario",
                        max_length=20,
                        verbose_name="Frecuencia de Actualización",
                    ),
                ),
                (
                    "valor_actual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor Actual",
                    ),
                ),
                (
                    "valor_anterior",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor Anterior",
                    ),
                ),
                (
                    "meta_minima",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Meta Mínima",
                    ),
                ),
                (
                    "meta_optima",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Meta Óptima",
                    ),
                ),
                (
                    "unidad_medida",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Unidad de Medida"
                    ),
                ),
                (
                    "color_normal",
                    models.CharField(
                        default="#28a745", max_length=7, verbose_name="Color Normal"
                    ),
                ),
                (
                    "color_advertencia",
                    models.CharField(
                        default="#ffc107",
                        max_length=7,
                        verbose_name="Color Advertencia",
                    ),
                ),
                (
                    "color_critico",
                    models.CharField(
                        default="#dc3545", max_length=7, verbose_name="Color Crítico"
                    ),
                ),
                (
                    "icono",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Icono (Font Awesome)"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "orden_dashboard",
                    models.IntegerField(default=0, verbose_name="Orden en Dashboard"),
                ),
                ("ultima_actualizacion", models.DateTimeField(blank=True, null=True)),
                (
                    "roles_autorizados",
                    models.JSONField(default=list, verbose_name="Roles Autorizados"),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "KPI Dashboard",
                "verbose_name_plural": "KPIs Dashboard",
                "db_table": "dashboard_kpis",
                "ordering": ["categoria", "orden_dashboard"],
            },
        ),
        migrations.CreateModel(
            name="ReporteGenerado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario_solicitante",
                    models.IntegerField(verbose_name="Usuario Solicitante"),
                ),
                (
                    "parametros",
                    models.JSONField(
                        default=dict, verbose_name="Parámetros del Reporte"
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Inicio del Período"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Fin del Período"
                    ),
                ),
                (
                    "filtro_paciente",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Filtro por Paciente"
                    ),
                ),
                (
                    "filtro_medico",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Filtro por Médico"
                    ),
                ),
                (
                    "filtro_servicio",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Filtro por Servicio"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("procesando", "Procesando"),
                            ("completado", "Completado"),
                            ("error", "Error"),
                            ("expirado", "Expirado"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "formato",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                        ],
                        default="pdf",
                        max_length=10,
                        verbose_name="Formato de Salida",
                    ),
                ),
                (
                    "fecha_solicitud",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Solicitud"
                    ),
                ),
                (
                    "fecha_procesamiento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Procesamiento"
                    ),
                ),
                (
                    "fecha_completado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Completado"
                    ),
                ),
                (
                    "ruta_archivo",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Ruta del Archivo Generado",
                    ),
                ),
                (
                    "tamaño_archivo",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Tamaño del Archivo (bytes)"
                    ),
                ),
                (
                    "datos_resumen",
                    models.JSONField(default=dict, verbose_name="Datos de Resumen"),
                ),
                (
                    "mensaje_error",
                    models.TextField(blank=True, verbose_name="Mensaje de Error"),
                ),
                (
                    "tiempo_procesamiento",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Tiempo de Procesamiento (segundos)",
                    ),
                ),
                (
                    "hash_archivo",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        verbose_name="Hash SHA256 del Archivo",
                    ),
                ),
                (
                    "accesos_descarga",
                    models.IntegerField(default=0, verbose_name="Número de Descargas"),
                ),
                (
                    "fecha_expiracion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Expiración"
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte Generado",
                "verbose_name_plural": "Reportes Generados",
                "db_table": "reportes_generados",
                "ordering": ["-fecha_solicitud"],
            },
        ),
        migrations.CreateModel(
            name="TipoReporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre del Reporte"),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Código Único"
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("estadistico", "Reporte Estadístico"),
                            ("paciente", "Reporte de Paciente"),
                            ("institucional", "Reporte Institucional"),
                            ("regulatorio", "Reporte Regulatorio"),
                            ("clinico", "Reporte Clínico"),
                            ("financiero", "Reporte Financiero"),
                        ],
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "frecuencia",
                    models.CharField(
                        choices=[
                            ("diario", "Diario"),
                            ("semanal", "Semanal"),
                            ("mensual", "Mensual"),
                            ("trimestral", "Trimestral"),
                            ("anual", "Anual"),
                            ("bajo_demanda", "Bajo Demanda"),
                        ],
                        default="bajo_demanda",
                        max_length=20,
                        verbose_name="Frecuencia de Generación",
                    ),
                ),
                (
                    "automatico",
                    models.BooleanField(
                        default=False, verbose_name="¿Generación Automática?"
                    ),
                ),
                (
                    "requiere_parametros",
                    models.BooleanField(
                        default=False, verbose_name="¿Requiere Parámetros?"
                    ),
                ),
                (
                    "parametros_esquema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Estructura JSON de parámetros requeridos",
                        verbose_name="Esquema de Parámetros",
                    ),
                ),
                (
                    "roles_autorizados",
                    models.JSONField(
                        default=list,
                        help_text="Lista de roles que pueden generar este reporte",
                        verbose_name="Roles Autorizados",
                    ),
                ),
                (
                    "confidencial",
                    models.BooleanField(
                        default=False, verbose_name="¿Reporte Confidencial?"
                    ),
                ),
                (
                    "plantilla_sql",
                    models.TextField(blank=True, verbose_name="Consulta SQL Base"),
                ),
                (
                    "campos_requeridos",
                    models.JSONField(default=list, verbose_name="Campos Requeridos"),
                ),
                (
                    "formato_salida",
                    models.JSONField(
                        default=list,
                        help_text="pdf, excel, csv, json",
                        verbose_name="Formatos de Salida Disponibles",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tipo de Reporte",
                "verbose_name_plural": "Tipos de Reporte",
                "db_table": "tipos_reporte",
                "ordering": ["categoria", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="AlertaMedica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=200, verbose_name="Título de la Alerta"
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción Detallada")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("valor_critico", "Valor Crítico"),
                            ("seguimiento_vencido", "Seguimiento Vencido"),
                            (
                                "medicamento_contraindicado",
                                "Medicamento Contraindicado",
                            ),
                            ("riesgo_alto", "Riesgo Alto Detectado"),
                            ("resultado_anormal", "Resultado Anormal"),
                            ("cita_perdida", "Cita Perdida"),
                            ("protocolo_incumplido", "Protocolo No Cumplido"),
                            ("auditoria", "Auditoría Requerida"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Alerta",
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                            ("emergencia", "Emergencia"),
                        ],
                        max_length=15,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activa", "Activa"),
                            ("revisada", "Revisada"),
                            ("resuelta", "Resuelta"),
                            ("descartada", "Descartada"),
                            ("escalada", "Escalada"),
                        ],
                        default="activa",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "paciente_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID del Paciente"
                    ),
                ),
                (
                    "embarazo_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID del Embarazo"
                    ),
                ),
                (
                    "medico_responsable_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID del Médico Responsable"
                    ),
                ),
                (
                    "modulo_origen",
                    models.CharField(max_length=50, verbose_name="Módulo de Origen"),
                ),
                (
                    "registro_origen_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID del Registro de Origen"
                    ),
                ),
                (
                    "datos_contexto",
                    models.JSONField(default=dict, verbose_name="Datos de Contexto"),
                ),
                (
                    "valor_actual",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Valor Actual"
                    ),
                ),
                (
                    "valor_umbral",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Valor Umbral"
                    ),
                ),
                (
                    "accion_recomendada",
                    models.TextField(verbose_name="Acción Recomendada"),
                ),
                (
                    "protocolo_seguimiento",
                    models.TextField(
                        blank=True, verbose_name="Protocolo de Seguimiento"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Vencimiento"
                    ),
                ),
                (
                    "fecha_revision",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Revisión"
                    ),
                ),
                (
                    "fecha_resolucion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Resolución"
                    ),
                ),
                (
                    "usuario_revision_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Usuario que Revisó"
                    ),
                ),
                (
                    "usuario_resolucion_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Usuario que Resolvió"
                    ),
                ),
                (
                    "comentario_revision",
                    models.TextField(blank=True, verbose_name="Comentario de Revisión"),
                ),
                (
                    "comentario_resolucion",
                    models.TextField(
                        blank=True, verbose_name="Comentario de Resolución"
                    ),
                ),
                (
                    "notificacion_enviada",
                    models.BooleanField(
                        default=False, verbose_name="¿Notificación Enviada?"
                    ),
                ),
                (
                    "recordatorio_enviado",
                    models.BooleanField(
                        default=False, verbose_name="¿Recordatorio Enviado?"
                    ),
                ),
                (
                    "escalamiento_automatico",
                    models.BooleanField(
                        default=False, verbose_name="¿Escalamiento Automático?"
                    ),
                ),
                (
                    "tiempo_escalamiento_horas",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Tiempo para Escalamiento (horas)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta Médica",
                "verbose_name_plural": "Alertas Médicas",
                "db_table": "alertas_medicas",
                "ordering": ["-fecha_creacion", "-prioridad"],
                "indexes": [
                    models.Index(
                        fields=["estado", "prioridad"],
                        name="alertas_med_estado_7131b1_idx",
                    ),
                    models.Index(
                        fields=["paciente_id", "estado"],
                        name="alertas_med_pacient_4c08eb_idx",
                    ),
                    models.Index(
                        fields=["fecha_creacion"], name="alertas_med_fecha_c_1da145_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditoriaReporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario_id", models.IntegerField(verbose_name="ID del Usuario")),
                (
                    "direccion_ip",
                    models.GenericIPAddressField(verbose_name="Dirección IP"),
                ),
                ("user_agent", models.TextField(verbose_name="User Agent")),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("generacion", "Generación"),
                            ("descarga", "Descarga"),
                            ("visualizacion", "Visualización"),
                            ("modificacion", "Modificación"),
                            ("eliminacion", "Eliminación"),
                            ("compartir", "Compartir"),
                        ],
                        max_length=20,
                        verbose_name="Acción Realizada",
                    ),
                ),
                (
                    "fecha_accion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y Hora"
                    ),
                ),
                (
                    "detalles",
                    models.JSONField(
                        default=dict, verbose_name="Detalles de la Acción"
                    ),
                ),
                (
                    "cumple_ley_3871",
                    models.BooleanField(default=True, verbose_name="¿Cumple Ley 3871?"),
                ),
                (
                    "justificacion_acceso",
                    models.TextField(
                        blank=True, verbose_name="Justificación del Acceso"
                    ),
                ),
                (
                    "reporte_generado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reportes.reportegenerado",
                        verbose_name="Reporte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoría de Reporte",
                "verbose_name_plural": "Auditorías de Reportes",
                "db_table": "auditoria_reportes",
                "ordering": ["-fecha_accion"],
            },
        ),
        migrations.AddField(
            model_name="reportegenerado",
            name="tipo_reporte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reportes.tiporeporte",
                verbose_name="Tipo de Reporte",
            ),
        ),
    ]
