# Generated by Django 5.1.3 on 2025-11-09 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dashboardkpi",
            options={
                "ordering": ["categoria", "orden_dashboard"],
                "verbose_name": "Indicador KPI",
                "verbose_name_plural": "Indicadores KPI Dashboard",
            },
        ),
        migrations.AddField(
            model_name="auditoriareporte",
            name="observaciones",
            field=models.TextField(blank=True, verbose_name="📋 Observaciones"),
        ),
        migrations.AddField(
            model_name="dashboardkpi",
            name="visible_administrador",
            field=models.BooleanField(
                default=True, verbose_name="👔 ¿Visible para administradores?"
            ),
        ),
        migrations.AddField(
            model_name="dashboardkpi",
            name="visible_director",
            field=models.BooleanField(
                default=True, verbose_name="🏢 ¿Visible para director?"
            ),
        ),
        migrations.AddField(
            model_name="dashboardkpi",
            name="visible_medico",
            field=models.BooleanField(
                default=True, verbose_name="👨\u200d⚕️ ¿Visible para médicos?"
            ),
        ),
        migrations.AddField(
            model_name="reportegenerado",
            name="observaciones",
            field=models.TextField(
                blank=True, verbose_name="📝 Observaciones adicionales"
            ),
        ),
        migrations.AddField(
            model_name="reportegenerado",
            name="total_registros",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="📊 Total de registros incluidos"
            ),
        ),
        migrations.AddField(
            model_name="tiporeporte",
            name="formato_csv",
            field=models.BooleanField(
                default=False,
                help_text="Formato simple para importar en otros sistemas",
                verbose_name="📋 ¿Disponible en CSV?",
            ),
        ),
        migrations.AddField(
            model_name="tiporeporte",
            name="formato_excel",
            field=models.BooleanField(
                default=True,
                help_text="Formato ideal para análisis de datos",
                verbose_name="📊 ¿Disponible en Excel?",
            ),
        ),
        migrations.AddField(
            model_name="tiporeporte",
            name="formato_json",
            field=models.BooleanField(
                default=False,
                help_text="Formato para integración con otros sistemas",
                verbose_name="⚙️ ¿Disponible en JSON?",
            ),
        ),
        migrations.AddField(
            model_name="tiporeporte",
            name="formato_pdf",
            field=models.BooleanField(
                default=True,
                help_text="Formato ideal para imprimir y compartir",
                verbose_name="📄 ¿Disponible en PDF?",
            ),
        ),
        migrations.AddField(
            model_name="tiporeporte",
            name="incluir_fecha_fin",
            field=models.BooleanField(
                default=True, verbose_name="📅 ¿Permitir filtrar por fecha de fin?"
            ),
        ),
        migrations.AddField(
            model_name="tiporeporte",
            name="incluir_fecha_inicio",
            field=models.BooleanField(
                default=True, verbose_name="📅 ¿Permitir filtrar por fecha de inicio?"
            ),
        ),
        migrations.AddField(
            model_name="tiporeporte",
            name="incluir_medico",
            field=models.BooleanField(
                default=False, verbose_name="👨\u200d⚕️ ¿Permitir filtrar por médico?"
            ),
        ),
        migrations.AddField(
            model_name="tiporeporte",
            name="incluir_paciente",
            field=models.BooleanField(
                default=False,
                verbose_name="👤 ¿Permitir filtrar por paciente específico?",
            ),
        ),
        migrations.AddField(
            model_name="tiporeporte",
            name="incluir_servicio",
            field=models.BooleanField(
                default=False, verbose_name="🏥 ¿Permitir filtrar por servicio médico?"
            ),
        ),
        migrations.AddField(
            model_name="tiporeporte",
            name="permitir_administrador",
            field=models.BooleanField(
                default=True,
                verbose_name="👔 ¿Los administradores pueden generar este reporte?",
            ),
        ),
        migrations.AddField(
            model_name="tiporeporte",
            name="permitir_director",
            field=models.BooleanField(
                default=True,
                verbose_name="🏢 ¿El director médico puede generar este reporte?",
            ),
        ),
        migrations.AddField(
            model_name="tiporeporte",
            name="permitir_enfermero",
            field=models.BooleanField(
                default=False,
                verbose_name="👩\u200d⚕️ ¿Los enfermeros pueden generar este reporte?",
            ),
        ),
        migrations.AddField(
            model_name="tiporeporte",
            name="permitir_medico",
            field=models.BooleanField(
                default=True,
                verbose_name="👨\u200d⚕️ ¿Los médicos pueden generar este reporte?",
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="accion_recomendada",
            field=models.TextField(verbose_name="💡 Acción recomendada"),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="comentario_resolucion",
            field=models.TextField(
                blank=True, verbose_name="💬 Comentario de resolución"
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="comentario_revision",
            field=models.TextField(
                blank=True, verbose_name="💬 Comentario de revisión"
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="datos_contexto",
            field=models.JSONField(
                default=dict,
                help_text="Datos internos de contexto",
                verbose_name="Datos de Contexto (Interno)",
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="descripcion",
            field=models.TextField(verbose_name="📄 Descripción detallada"),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="embarazo_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="🤰 ID del Embarazo"
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="escalamiento_automatico",
            field=models.BooleanField(
                default=False, verbose_name="🆙 ¿Escalamiento automático?"
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="estado",
            field=models.CharField(
                choices=[
                    ("activa", "🔴 Activa"),
                    ("revisada", "🟡 Revisada"),
                    ("resuelta", "🟢 Resuelta"),
                    ("descartada", "⚫ Descartada"),
                    ("escalada", "🟠 Escalada"),
                ],
                default="activa",
                max_length=15,
                verbose_name="📊 Estado actual",
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="🕐 Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="fecha_resolucion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="✅ Fecha de resolución"
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="fecha_revision",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="👀 Fecha de revisión"
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="fecha_vencimiento",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="⏰ Fecha límite"
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="medico_responsable_id",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="👨\u200d⚕️ ID del Médico Responsable",
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="modulo_origen",
            field=models.CharField(
                choices=[
                    ("pacientes", "👤 Módulo de Pacientes"),
                    ("embarazos", "🤰 Módulo de Embarazos"),
                    ("controles", "🩺 Controles Prenatales"),
                    ("ecografias", "📻 Ecografías"),
                    ("laboratorio", "🧪 Laboratorio"),
                    ("calculadoras", "🧮 Calculadoras Médicas"),
                    ("partos", "👶 Partos"),
                    ("sistema", "⚙️ Sistema"),
                ],
                max_length=50,
                verbose_name="📂 Módulo de origen",
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="notificacion_enviada",
            field=models.BooleanField(
                default=False, verbose_name="📧 ¿Notificación enviada?"
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="paciente_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="👤 ID del Paciente"
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="prioridad",
            field=models.CharField(
                choices=[
                    ("baja", "🟢 Baja"),
                    ("media", "🟡 Media"),
                    ("alta", "🟠 Alta"),
                    ("critica", "🔴 Crítica"),
                    ("emergencia", "🚨 EMERGENCIA"),
                ],
                max_length=15,
                verbose_name="⚡ Prioridad",
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="protocolo_seguimiento",
            field=models.TextField(
                blank=True, verbose_name="📋 Protocolo de seguimiento"
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="recordatorio_enviado",
            field=models.BooleanField(
                default=False, verbose_name="🔔 ¿Recordatorio enviado?"
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="registro_origen_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="🔗 ID del registro relacionado"
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="tiempo_escalamiento_horas",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="⏱️ Tiempo para escalamiento (horas)"
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("valor_critico", "🚨 Valor crítico detectado"),
                    ("seguimiento_vencido", "⏰ Seguimiento vencido"),
                    ("medicamento_contraindicado", "💊 Medicamento contraindicado"),
                    ("riesgo_alto", "⚠️ Riesgo alto detectado"),
                    ("resultado_anormal", "📊 Resultado anormal"),
                    ("cita_perdida", "📅 Cita perdida"),
                    ("protocolo_incumplido", "📋 Protocolo no seguido"),
                    ("auditoria", "🔍 Requiere auditoría"),
                ],
                max_length=30,
                verbose_name="🏷️ Tipo de alerta",
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="titulo",
            field=models.CharField(
                max_length=200, verbose_name="📢 Título de la alerta"
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="usuario_resolucion_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="👤 Usuario que resolvió"
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="usuario_revision_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="👤 Usuario que revisó"
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="valor_actual",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="📊 Valor actual"
            ),
        ),
        migrations.AlterField(
            model_name="alertamedica",
            name="valor_umbral",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="⚠️ Valor umbral"
            ),
        ),
        migrations.AlterField(
            model_name="auditoriareporte",
            name="accion",
            field=models.CharField(
                choices=[
                    ("generacion", "📄 Generación de reporte"),
                    ("descarga", "📥 Descarga"),
                    ("visualizacion", "👀 Visualización"),
                    ("modificacion", "✏️ Modificación"),
                    ("eliminacion", "🗑️ Eliminación"),
                    ("compartir", "📤 Compartir"),
                ],
                max_length=20,
                verbose_name="⚡ Acción realizada",
            ),
        ),
        migrations.AlterField(
            model_name="auditoriareporte",
            name="cumple_ley_3871",
            field=models.BooleanField(
                default=True, verbose_name="⚖️ ¿Cumple con la Ley 3871?"
            ),
        ),
        migrations.AlterField(
            model_name="auditoriareporte",
            name="detalles",
            field=models.JSONField(
                default=dict,
                help_text="Detalles internos de la acción",
                verbose_name="Detalles de la Acción (Interno)",
            ),
        ),
        migrations.AlterField(
            model_name="auditoriareporte",
            name="direccion_ip",
            field=models.GenericIPAddressField(verbose_name="🌐 Dirección IP"),
        ),
        migrations.AlterField(
            model_name="auditoriareporte",
            name="fecha_accion",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="🕐 Fecha y hora"
            ),
        ),
        migrations.AlterField(
            model_name="auditoriareporte",
            name="justificacion_acceso",
            field=models.TextField(
                blank=True, verbose_name="📝 Justificación del acceso"
            ),
        ),
        migrations.AlterField(
            model_name="auditoriareporte",
            name="reporte_generado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reportes.reportegenerado",
                verbose_name="📊 Reporte",
            ),
        ),
        migrations.AlterField(
            model_name="auditoriareporte",
            name="user_agent",
            field=models.TextField(verbose_name="💻 Navegador/Dispositivo"),
        ),
        migrations.AlterField(
            model_name="auditoriareporte",
            name="usuario_id",
            field=models.IntegerField(verbose_name="👤 Usuario"),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="activo",
            field=models.BooleanField(default=True, verbose_name="✅ ¿Está activo?"),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("pacientes", "👥 Pacientes"),
                    ("embarazos", "🤰 Embarazos"),
                    ("controles", "🩺 Controles Prenatales"),
                    ("partos", "👶 Partos"),
                    ("calculadoras", "🧮 Calculadoras Médicas"),
                    ("calidad", "⭐ Calidad de Atención"),
                    ("seguridad", "🛡️ Seguridad"),
                    ("productividad", "📈 Productividad"),
                ],
                max_length=20,
                verbose_name="📂 Categoría",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="codigo",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="🏷️ Código único"
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="consulta_sql",
            field=models.TextField(
                help_text="Query SQL que obtiene el valor del KPI",
                verbose_name="⚙️ Consulta para calcular el valor",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="descripcion",
            field=models.TextField(
                help_text="Explica qué mide este indicador",
                verbose_name="📄 Descripción",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="frecuencia_actualizacion",
            field=models.CharField(
                choices=[
                    ("tiempo_real", "⚡ Tiempo real"),
                    ("cada_hora", "🕐 Cada hora"),
                    ("diario", "📅 Diario"),
                    ("semanal", "📆 Semanal"),
                ],
                default="diario",
                max_length=20,
                verbose_name="🔄 ¿Con qué frecuencia se actualiza?",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="icono",
            field=models.CharField(
                blank=True,
                help_text="Nombre del icono (opcional)",
                max_length=50,
                verbose_name="🎨 Icono",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="meta_minima",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="🎯 Meta mínima aceptable",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="meta_optima",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="🏆 Meta óptima",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="nombre",
            field=models.CharField(
                help_text="Ej: Total de Pacientes Activos",
                max_length=200,
                verbose_name="📊 Nombre del Indicador",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="orden_dashboard",
            field=models.IntegerField(
                default=0, verbose_name="📋 Orden en el dashboard"
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="parametros_calculo",
            field=models.JSONField(
                default=dict,
                help_text="Parámetros internos de cálculo",
                verbose_name="Parámetros de Cálculo (Interno)",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="roles_autorizados",
            field=models.JSONField(
                default=list,
                help_text="Lista interna - se calcula automáticamente",
                verbose_name="Roles Autorizados (Interno)",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("numero", "🔢 Número simple"),
                    ("porcentaje", "📊 Porcentaje"),
                    ("tendencia", "📈 Tendencia"),
                    ("ratio", "⚖️ Proporción"),
                    ("tiempo", "⏱️ Tiempo promedio"),
                ],
                max_length=20,
                verbose_name="📈 Tipo de indicador",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="unidad_medida",
            field=models.CharField(
                blank=True,
                help_text="Ej: pacientes, %, minutos, días",
                max_length=20,
                verbose_name="📏 Unidad de medida",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="valor_actual",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="📊 Valor actual",
            ),
        ),
        migrations.AlterField(
            model_name="dashboardkpi",
            name="valor_anterior",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="📉 Valor anterior",
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="accesos_descarga",
            field=models.IntegerField(default=0, verbose_name="📥 Número de descargas"),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="datos_resumen",
            field=models.JSONField(
                default=dict,
                help_text="Resumen interno de los datos",
                verbose_name="Datos de Resumen (Interno)",
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "⏳ Pendiente"),
                    ("procesando", "⚙️ Procesando"),
                    ("completado", "✅ Completado"),
                    ("error", "❌ Error"),
                    ("expirado", "⏰ Expirado"),
                ],
                default="pendiente",
                max_length=20,
                verbose_name="📈 Estado del reporte",
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="fecha_completado",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="✅ Fecha de completado"
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="fecha_expiracion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="⏰ Fecha de expiración"
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="fecha_fin",
            field=models.DateField(
                blank=True, null=True, verbose_name="📅 Fecha de fin del período"
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="fecha_inicio",
            field=models.DateField(
                blank=True, null=True, verbose_name="📅 Fecha de inicio del período"
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="fecha_procesamiento",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="⚙️ Inicio de procesamiento"
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="fecha_solicitud",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="🕐 Fecha de solicitud"
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="filtro_medico",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="👨\u200d⚕️ Médico específico (ID)"
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="filtro_paciente",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="👤 Paciente específico (ID)"
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="filtro_servicio",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="🏥 Servicio médico"
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="formato",
            field=models.CharField(
                choices=[
                    ("pdf", "📄 PDF"),
                    ("excel", "📊 Excel"),
                    ("csv", "📋 CSV"),
                    ("json", "⚙️ JSON"),
                ],
                default="pdf",
                max_length=10,
                verbose_name="📄 Formato de descarga",
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="hash_archivo",
            field=models.CharField(
                blank=True,
                max_length=128,
                verbose_name="🔐 Hash de seguridad del archivo",
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="mensaje_error",
            field=models.TextField(blank=True, verbose_name="❌ Mensaje de error"),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="parametros",
            field=models.JSONField(
                default=dict,
                help_text="Parámetros internos del reporte",
                verbose_name="Parámetros del Reporte (Interno)",
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="ruta_archivo",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="📁 Ruta del archivo"
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="tamaño_archivo",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="📏 Tamaño del archivo (bytes)"
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="tiempo_procesamiento",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="⏱️ Tiempo de procesamiento (segundos)",
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="tipo_reporte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reportes.tiporeporte",
                verbose_name="📊 Tipo de Reporte",
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="usuario_solicitante",
            field=models.IntegerField(
                verbose_name="👤 Usuario que solicitó el reporte"
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="activo",
            field=models.BooleanField(default=True, verbose_name="✅ ¿Está activo?"),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="automatico",
            field=models.BooleanField(
                default=False,
                help_text="Si está activado, el reporte se generará según la frecuencia seleccionada",
                verbose_name="🤖 ¿Generar automáticamente?",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="campos_requeridos",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista interna - se calcula automáticamente",
                verbose_name="Campos Requeridos (Interno)",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("estadistico", "📊 Estadísticas y Métricas"),
                    ("paciente", "👤 Reportes de Pacientes"),
                    ("institucional", "🏥 Reportes Institucionales"),
                    ("regulatorio", "📋 Cumplimiento Regulatorio"),
                    ("clinico", "🩺 Reportes Clínicos"),
                    ("financiero", "💰 Reportes Financieros"),
                ],
                max_length=20,
                verbose_name="📂 Categoría del Reporte",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="codigo",
            field=models.CharField(
                blank=True,
                help_text="Código interno (se genera automáticamente si se deja vacío)",
                max_length=50,
                unique=True,
                verbose_name="🔖 Código Único",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="confidencial",
            field=models.BooleanField(
                default=False,
                help_text="Solo usuarios autorizados podrán ver este reporte",
                verbose_name="🔒 ¿Es confidencial?",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="descripcion",
            field=models.TextField(
                help_text="Describe qué información incluye este reporte",
                verbose_name="📄 Descripción",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="formato_salida",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista interna - se calcula automáticamente",
                verbose_name="Formatos de Salida (Interno)",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="frecuencia",
            field=models.CharField(
                choices=[
                    ("bajo_demanda", "🔄 Generar cuando se necesite"),
                    ("diario", "📅 Todos los días"),
                    ("semanal", "📆 Cada semana"),
                    ("mensual", "🗓️ Mensualmente"),
                    ("trimestral", "📊 Cada 3 meses"),
                    ("anual", "📈 Anualmente"),
                ],
                default="bajo_demanda",
                max_length=20,
                verbose_name="⏰ ¿Con qué frecuencia se genera?",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="nombre",
            field=models.CharField(
                help_text="Ej: Reporte de Pacientes del Mes",
                max_length=200,
                verbose_name="📝 Nombre del Reporte",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="parametros_esquema",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Estructura interna - no modificar manualmente",
                verbose_name="Parámetros Esquema (Interno)",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="plantilla_sql",
            field=models.TextField(
                blank=True,
                help_text="Dejar vacío para usar la consulta predeterminada",
                verbose_name="⚙️ Consulta SQL personalizada (Solo para expertos)",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="requiere_parametros",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el usuario debe configurar parámetros específicos",
                verbose_name="🔧 ¿Requiere parámetros adicionales?",
            ),
        ),
        migrations.AlterField(
            model_name="tiporeporte",
            name="roles_autorizados",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista interna - se calcula automáticamente",
                verbose_name="Roles Autorizados (Interno)",
            ),
        ),
    ]
