# Generated by Django 5.1.3 on 2025-12-27 01:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modulo",
                    models.CharField(
                        help_text="Nombre del módulo/modelo afectado", max_length=100,
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("crear", "Crear"),
                            ("actualizar", "Actualizar"),
                            ("eliminar", "Eliminar"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "registro_id",
                    models.IntegerField(help_text="ID del registro afectado"),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now,
                    ),
                ),
                (
                    "datos_anteriores",
                    models.JSONField(
                        blank=True,
                        help_text="Estado anterior del registro (solo para actualizar/eliminar)",
                        null=True,
                    ),
                ),
                (
                    "datos_nuevos",
                    models.JSONField(
                        blank=True,
                        help_text="Estado nuevo del registro (solo para crear/actualizar)",
                        null=True,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó el cambio",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auditorias_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Auditoría",
                "verbose_name_plural": "Registros de Auditoría",
                "db_table": "auditoria_registros",
                "ordering": ["-fecha"],
                "indexes": [
                    models.Index(
                        fields=["modulo", "-fecha"],
                        name="auditoria_r_modulo_c72e00_idx",
                    ),
                    models.Index(
                        fields=["usuario", "-fecha"],
                        name="auditoria_r_usuario_2f932a_idx",
                    ),
                    models.Index(
                        fields=["accion", "-fecha"],
                        name="auditoria_r_accion_85b194_idx",
                    ),
                ],
            },
        ),
    ]
