# Generated by Django 6.0.4 on 2026-05-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auditoria", "0002_revoke_auditlog_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="registroauditoria",
            name="checksum",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 del registro para detección de tampering",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="registroauditoria",
            name="detalle",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="registroauditoria",
            name="endpoint",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="registroauditoria",
            name="usuario_nombre",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="registroauditoria",
            name="usuario_rol",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="registroauditoria",
            name="accion",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Inicio de sesión"),
                    ("LOGOUT", "Cierre de sesión"),
                    ("LOGIN_FALLIDO", "Intento de login fallido"),
                    ("MFA_ACTIVADO", "MFA activado"),
                    ("MFA_FALLIDO", "Intento MFA fallido"),
                    ("MFA_DESACTIVADO", "MFA desactivado"),
                    ("CUENTA_BLOQUEADA", "Cuenta bloqueada por intentos"),
                    ("crear", "Crear"),
                    ("actualizar", "Actualizar"),
                    ("eliminar", "Eliminar"),
                    ("CREAR", "Creación de registro"),
                    ("EDITAR", "Modificación de registro"),
                    ("VER", "Visualización de registro"),
                    ("DESACTIVAR", "Desactivación (soft delete)"),
                    ("ACTIVAR", "Reactivación de registro"),
                    ("EXPORTAR", "Exportación de datos"),
                    ("CONSULTA_IA", "Consulta al chatbot IA"),
                    ("ANALISIS_CNN", "Análisis de imagen con CNN"),
                    ("CAMBIO_ROL", "Cambio de rol de usuario"),
                    ("BACKUP", "Respaldo de base de datos"),
                    ("DESACTIVAR_PACIENTE", "Desactivación de paciente"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="registroauditoria",
            name="datos_anteriores",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registroauditoria",
            name="datos_nuevos",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registroauditoria",
            name="modulo",
            field=models.CharField(
                blank=True, help_text="Módulo/modelo afectado", max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="registroauditoria",
            name="registro_id",
            field=models.CharField(
                blank=True, help_text="ID del registro afectado", max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="registroauditoria",
            name="user_agent",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
