# Generated by Django 5.1.3 on 2025-11-24 00:38

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("citas", "0001_initial"),
        ("pacientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TriajeEnfermeria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "peso_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Peso en kilogramos (20-300 kg)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("20.00")),
                            django.core.validators.MaxValueValidator(Decimal("300.00")),
                        ],
                    ),
                ),
                (
                    "talla_cm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Talla en centímetros (50-250 cm)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("50.00")),
                            django.core.validators.MaxValueValidator(Decimal("250.00")),
                        ],
                    ),
                ),
                (
                    "imc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Índice de Masa Corporal (calculado automáticamente)",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "perimetro_abdominal_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Perímetro abdominal en cm",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("40.0")),
                            django.core.validators.MaxValueValidator(Decimal("200.0")),
                        ],
                    ),
                ),
                (
                    "presion_sistolica",
                    models.PositiveIntegerField(
                        help_text="Presión arterial sistólica (60-250 mmHg)",
                        validators=[
                            django.core.validators.MinValueValidator(60),
                            django.core.validators.MaxValueValidator(250),
                        ],
                    ),
                ),
                (
                    "presion_diastolica",
                    models.PositiveIntegerField(
                        help_text="Presión arterial diastólica (40-150 mmHg)",
                        validators=[
                            django.core.validators.MinValueValidator(40),
                            django.core.validators.MaxValueValidator(150),
                        ],
                    ),
                ),
                (
                    "temperatura",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Temperatura en °C (34-42°C)",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("34.0")),
                            django.core.validators.MaxValueValidator(Decimal("42.0")),
                        ],
                    ),
                ),
                (
                    "frecuencia_cardiaca",
                    models.PositiveIntegerField(
                        help_text="Frecuencia cardíaca en latidos por minuto (40-200 lpm)",
                        validators=[
                            django.core.validators.MinValueValidator(40),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                (
                    "frecuencia_respiratoria",
                    models.PositiveIntegerField(
                        help_text="Frecuencia respiratoria en respiraciones por minuto (8-40 rpm)",
                        validators=[
                            django.core.validators.MinValueValidator(8),
                            django.core.validators.MaxValueValidator(40),
                        ],
                    ),
                ),
                (
                    "saturacion_oxigeno",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Saturación de oxígeno en porcentaje (70-100%)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(70),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "motivo_visita",
                    models.TextField(
                        help_text="Motivo de la visita referido por el paciente",
                    ),
                ),
                (
                    "dolor_escala",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Escala de dolor 0-10 (0=sin dolor, 10=dolor máximo)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "nivel_conciencia",
                    models.CharField(
                        choices=[
                            ("alerta", "Alerta"),
                            ("somnoliento", "Somnoliento"),
                            ("estuporoso", "Estuporoso"),
                            ("inconsciente", "Inconsciente"),
                        ],
                        default="alerta",
                        max_length=20,
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones adicionales de enfermería",
                        null=True,
                    ),
                ),
                (
                    "alerta_presion_alta",
                    models.BooleanField(
                        default=False,
                        help_text="Alerta automática: PA sistólica ≥140 o PAD ≥90",
                    ),
                ),
                (
                    "alerta_fiebre",
                    models.BooleanField(
                        default=False, help_text="Alerta automática: Temperatura ≥38°C",
                    ),
                ),
                (
                    "alerta_taquicardia",
                    models.BooleanField(
                        default=False, help_text="Alerta automática: FC >100 lpm",
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "cita",
                    models.OneToOneField(
                        blank=True,
                        db_column="cita_id",
                        help_text="Cita a la que corresponde este triaje",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triaje",
                        to="citas.cita",
                    ),
                ),
                (
                    "enfermera",
                    models.ForeignKey(
                        db_column="enfermera_id",
                        limit_choices_to={"rol": "enfermera"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="triajes_realizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        db_column="paciente_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="triajes",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Triaje de Enfermería",
                "verbose_name_plural": "Triajes de Enfermería",
                "db_table": "triaje_enfermeria",
                "ordering": ["-fecha_registro"],
                "indexes": [
                    models.Index(
                        fields=["paciente", "-fecha_registro"],
                        name="triaje_enfe_pacient_618b3d_idx",
                    ),
                    models.Index(
                        fields=["cita"], name="triaje_enfe_cita_id_4fe060_idx",
                    ),
                    models.Index(
                        fields=["-fecha_registro"],
                        name="triaje_enfe_fecha_r_dfa824_idx",
                    ),
                ],
            },
        ),
    ]
