# Generated by Django 5.1.3 on 2025-12-27 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("triaje", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="triajeenfermeria",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="triajes_creados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="triajeenfermeria",
            name="fecha_modificacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="triajeenfermeria",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="triajes_modificados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modificado por",
            ),
        ),
    ]
